### ISSUE TITLE
Can't connect to Server

### ISSUE THREAD

**Issue by Oratorian** [nextcloud/android#1067]
### Actual behaviour
Installed the App, entered my details. When entering my URL cloud.svr33nfun.de it tries to connect. After a few seconds it shows 
"Couldn't establish connection"

### Environment data
Android version: 7.0

Device model: Samsung Galaxy S7 edge ( SM-G935F )

Stock or customized system: Stock

Nextcloud app version:1.4.3

Nextcloud server version:12.0.0

**Comment by Oratorian** [comment]
My URL is cloud.scr33nfun.de not cloud.svr33nfun.de

**Comment by JSoko** [comment]
Please have a look in your bruteforce-table and switch off ipV6 on your router if possible...

**Comment by Oratorian** [comment]
It doesn't seem to be Brutforce. I deactivated IPV6 and it worked. Will there be a fix? Cause all my servers run on IPV6.

**Comment by AndyScherzinger** [comment]
@Oratorian not in the very near future since the used OSS library implementing the webDAV communication doesn't support IPv6

**Comment by AndyScherzinger** [comment]
Closed since IPv6 is a known issue

**Comment by kugel-** [comment]
@AndyScherzinger Is there a solution on the horizon? It's a joke that I can't use IPv6 in 2018.

Plus, I need to use IPv6 because when I'm at home the routers packet acceleration does not work with ipv4, making file sync really slow (since the hostname resolves to the external ipv4 address, for ipv6 there are only global addresses anyway).

**Comment by kugel-** [comment]
@AndyScherzinger so is this resolved in 3.0.0? The welcome screen mentioned ipv6 support

**Comment by AndyScherzinger** [comment]
@kugel- yes this is resolved with 3.0.0 which supports ipv6

**Comment by Grmume** [comment]
I still have this problem with version 3.0.1. My server is reachable using a browser on my phone, but the app is stuck at Testing Connection. The server uses ipv6.

**Comment by tobiasKaminsky** [comment]
Can you create us a test account and send the credentials to android at nextcloud dot com with a reference to this issue?

**Comment by Grmume** [comment]
I'm sorry the problem only exists when connected to WiFi(on the same network as the server). I will open a new issue. Thanks for the fast Response.

**Comment by simonbernard** [comment]
I have the same problem. My server uses IPv6, I can access it from a browser, also DAVDroid is working fine.
I can't connect with the app though.
Can I send you my domain somehow?

**Comment by tobiasKaminsky** [comment]
Send it to tobias at nextcloud dot com with a reference to this issue?

**Comment by simonbernard** [comment]
@bozicm Sorry for late reply. I can't test it any more as I switched everything to v4, sorry.

**Comment by tobiasKaminsky** [comment]
If anyone still experiences the problem, can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by kugel-** [comment]
It works for me since some (not so) recent update

**Comment by tobiasKaminsky** [comment]
@kugel- thanks for the info.
I'll close it then, and of course it still can be re-opened if another user has problems.
