### ISSUE TITLE
when renaming, input is hidden

### ISSUE THREAD

**Issue by mtournay** [nextcloud/android#11551]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. chose a random file
2. tap rename in menu
3. alert appears with input for filename.

### Expected behaviour

when keyboard apperas, alert must move to top of screen instead of height beeing reduced ?

### Actual behaviour

when keyboard pop, alert height is reduced, input is now hidden, impossible to see what I type

### Android version

11

### Device brand and model

Unitech EA520

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.1

### Nextcloud server version

24.0.12

### Using a reverse proxy?

Yes

### Additional information

Industrial device : https://www.ute.com/us/products/detail/EA520

**Comment by Miniman45** [comment]
Unable to reproduce this @mtournay @mario

**Comment by mtournay** [comment]
Hi @Miniman45 

Could this helps you ?

this is the alert for renamming ('Enter a new name')

without keyboard

![image](https://github.com/nextcloud/android/assets/27957889/569c51a1-c2d5-4c86-984d-0c113262d628)

with keyboard
![image](https://github.com/nextcloud/android/assets/27957889/c6bf075b-0811-4999-b251-2ce003721571)

as you can see it's quite difficult to enter a new name without seeing it! 🤣

**Comment by Miniman45** [comment]
Sure @mtournay will look into it

**Comment by Miniman45** [comment]
<img width="921" alt="Screenshot 2023-09-24 at 10 21 54 PM" src="https://github.com/nextcloud/android/assets/109476921/c3bfc0af-4af2-4258-8bcc-e03876b46449">
This should resolve the problem right? @tobiasKaminsky @ZetaTom

**Comment by ZetaTom** [comment]
> <img alt="Screenshot 2023-09-24 at 10 21 54 PM" width="921" src="https://user-images.githubusercontent.com/109476921/270179354-c3bfc0af-4af2-4258-8bcc-e03876b46449.png"> This should resolve the problem right? @tobiasKaminsky @ZetaTom

@Miniman45, thank you for suggesting this fix. Unfortunately, this suggestion didn't resolve the issue in my tests. I'm currently able to observe this behaviour using the Google Pixel 2 emulator.

**Comment by Miniman45** [comment]
@ZetaTom if yes i would like to work on this issue to resolve 
could you please assign this to me

**Comment by joshtrichards** [comment]
Related: #11453

**Comment by joshtrichards** [comment]
As far as I can tell this is fixed. Ping me back if not.

**Comment by mtournay** [comment]
Hello

I'll test next week on my Unitech PDA. Sorry I miss the github notifications in my mailbox...

**Comment by ZetaTom** [comment]
Unfortunately, this is still a current issue with the Nextcloud client running on certain versions of Android. If a dialogue requires text input, the text box itself may be squashed when the keyboard is opened on small devices. The simplest example is the file rename dialogue.

The screenshots below were taken on a Pixel 2 emulator running the AOSP API 30 (Android 11.0) image. This also applies to physical Pixel 2 devices.

Without virtual keyboard | With virtual keyboard
--- | ---
![Without virtual keyboard](https://github.com/user-attachments/assets/27e28d84-96ab-4da8-bcc7-a81e414a43e1) | ![With virtual keyboard](https://github.com/user-attachments/assets/6d85aa59-8f4c-4e2f-b20c-1614e37463a7)

Newer versions of Android, even those running on the previously affected devices, do not necessarily cause the same problem. The following screenshot was also taken on a Pixel 2 emulator, but using an AOSP API 34 (Android 14.0) image instead.

![With virtual keyboard on Android 14.0](https://github.com/user-attachments/assets/1c38b3af-c893-4fe2-a644-4604089fb4a7)
