### ISSUE TITLE
Release 3.28.0

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#12377]
**Planned RC1: 17.01.2024**
**Planned Release date: 30.01.2024**

**Bump (do this when creating new roadmap)**
- [x] create milestone
- [x] check if stable server version in drone.yml needs to be updated
- [x] bump version in MainApp
	- [x] ```OUTDATED_SERVER_VERSION``` according https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule (e.g. NC12)
	- [x] change if needed https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html#mobile-apps
	- [x] add these versions to changelog
- [x] App
    - [x] check if code is outdated due to last supported server version ```@NextcloudServer``` annotation
    - [x] remove support for server older ```MINIMUM_SUPPORTED_SERVER_VERSION```
    - [x] lower minimum version for FileUploader:useFilesUploadWorker(…)
- [x] Library
    - [x] check if code is outdated due to last supported server version ```@NextcloudServer``` annotation
    - [x] remove support for server older ```MINIMUM_SUPPORTED_SERVER_VERSION```
- [x] check if oldest Android version is EOL by Google and user usage <= 0.5% and drop it if so
  - [x] search for usage of Build.VERSION_CODES.xy
  - [x] announce it in changelog

**Create stable-x.y branch & use it for release (when releasing RC1)**
- [x] create branch ```stable-x.y```
	- [x] enable branch to be analyzed on codacy
- [x] change on App
	- [x] ```getBranchName.sh```
	- [x] ```analysis-wrapper.sh```
	- [ ] check that transifex bot still works
- [x] change on Lib
    - [x] create branch stable-2.x
    - [x] enable branch to be analyzed on codacy
	- [x] ```getBranchName.sh```
	- [x] ```analysis-wrapper.sh```
- [ ] Update version on master to next major version

**Test app with all supported Android version**
- access all activities
- auto upload
- upload / download files/folders
- use external sdcard
- what's new slides correctly shown on first start

All tests on
  - [x] Android 6
  - [x] Android 7
  - [x] Android 8
  - [x] Android 9
  - [x] Android 10
  - [x] Android 11

**RC1**
- [x] Bump version code in ```build.gradle``` file
- [x] add what's new slides
- [x] replace screenshots (https://github.com/nextcloud/screenshots/tree/master/android/phone)
- [x] release new library version with rc-2.x.y-01 tag & use this is in app
- [x] release new SSO if needed
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is enabled
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] release with fastlane: creates GH release, uploads to Gplay, creates Gitlab MR for F-Droid
- [x] Verify that it is shown on [F-Droid](https://f-droid.org/de/packages/com.nextcloud.client/) (within 24h)
- [x] inform marketing about changelog and expected release date

**Final Release, after two weeks time (max) of latest RC release**
- [x] Bump version code in ```build.gradle``` file
- [x] set library to final tag
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is disabled
- [x] Test that what's new is shown correctly on upgrade
- [x] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] release with fastlane: creates GH release, uploads to Gplay, creates Gitlab MR for F-Droid
- [ ] Verify that it is shown on [F-Droid](https://f-droid.org/de/packages/com.nextcloud.client/) (within 24h)

**After release**
- x.y-1
  - [x] delete ```stable-x.y-1``` branch
- x.y
  - [x] create milestone x.y.1
  - [x] schedule x.y.1 RC1 3 weeks after stable, release ~4 weeks
  - [x] create overview issue
- x.y+1
  - [x] create milestone x.y+1
  - [x] create overview issue & adjust date, handle bumps

Backports:
- [App](https://github.com/nextcloud/android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)
- [Library](https://github.com/nextcloud/android-library/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)

Open PRs:
- [Milestone](https://github.com/nextcloud/android/pulls?q=is%3Aopen+is%3Apr+milestone%3A%22Nextcloud+App+3.7.0%22)

Marketing:
@jospoortvliet

**Comment by tobinq** [comment]
just to note:
on https://github.com/nextcloud/android/releases/tag/rc-3.28.0-01
my browser shows me "3.28.0 RC1 (January 17, 2023)", i strongly believe it should be "2024" like it is shown here ;-)
just in case some scripts uses the data from there and then messes something up.
thanks for all the work!

**Comment by AndyScherzinger** [comment]
@tobinq fixed, thanks for noting 👍

**Comment by licaon-kter** [comment]
Can anyone look up this error: https://gitlab.com/fdroid/fdroiddata/-/jobs/6070052197#L461 ?

**Comment by licaon-kter** [comment]
> the gradle command would need to have  --write-verification-metadata pgp,sha256 help --export-keys at the end.

umm, explain why? :)

still fails: https://gitlab.com/fdroid/fdroiddata/-/jobs/6080581136#L1195

disabled autoupdates for now: https://gitlab.com/fdroid/fdroiddata/-/commit/707e5fb69328983a693137ec8984fa4059d69eb6

ping us when fixed

**Comment by AndyScherzinger** [comment]
@licaon-kter should be fixed now with https://github.com/nextcloud/android/pull/12479 having been merged

> umm, explain why? :)

Pleasure to do so

`--write-verification-metadata pgp,sha256 help --export-keys` in a gradle command will fetch or create if not publish the checksums of each dependency/package as well as getting the signatures of each package. Any gradle build will then validae checksums and signatures again the metadata file within the app's repo. Now since the former master-branch had a dependency `-SNAPSHOT` there wasn't and always an up to date checksum in the app repo hence the build fails. But with the above the missing checksum would get added on the fly. 

In any case as referened above it makes more sense to always link a fixed version, else if you run a build twice and the lib got updated `-SNAPSHOT` would not always point to the very same build/version. Now it does 👍

**Comment by licaon-kter** [comment]
still an issue with https://github.com/nextcloud/android/releases/tag/dev-20240207 fyi

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky the currently nightly mechanism breaks nightlies, see https://github.com/nextcloud/android/compare/dev-20240208...dev-20240209 you auto update the lib reference but not the verification metadata hence any local and f-droid build will always fail until the metadata got updated (!)

**Comment by AndyScherzinger** [comment]
@licaon-kter https://github.com/nextcloud/android/releases/tag/dev-20240212 works fine for me btw. Can't say if you also deactivated auto builds for the dev/nightly releases

**Comment by licaon-kter** [comment]
@AndyScherzinger I did, will test locally and re-enable if ok

**Comment by AndyScherzinger** [comment]
@licaon-kter 3.28.0 final should show up on F-Droid's m,eta data any time soon when the client team and @tobiasKaminsky will have found the time

**Comment by licaon-kter** [comment]
And again... https://gitlab.com/fdroid/fdroiddata/-/jobs/6168943079#L515

should I disable autoupdates or what's the plan?

**Comment by AndyScherzinger** [comment]
> should I disable autoupdates or what's the plan?

For the moment yes 😭 

I pinged @tobiasKaminsky about it yesterday since the nightly builds logic on our end seems to just update the lib-dependency but does not update the verification metadata. So as long as this isn't fixed on our end, builds will keep failing every time a PR gets merged in the lib project...

However this is just the case for the nightlies, the final releases don't suffer from this logic while the finals also don't auto-update afaik.

**Comment by licaon-kter** [comment]
>  the final releases don't suffer from this logic while the finals also don't auto-update

conundrum :)

**Comment by licaon-kter** [comment]
disabled autoupdate for now https://gitlab.com/fdroid/fdroiddata/-/commit/ce410d7f7e6216af9cc5b0030f309944ecae3047

ping us when fixed I guess

**Comment by AndyScherzinger** [comment]
Will do! 👍

**Comment by Keessaus** [comment]
In the 3.28.0 release, I saw a fix I am eagerly waiting for. The tag for 3.28.0 was from two days ago, but no release on Github (<https://github.com/nextcloud/android/releases>) nor on the Playstore has been made. Is this the usual work flow and should I just sit tight or has something gone wrong?

**Comment by Keessaus** [comment]
> The tag for 3.28.0 was from two days ago, but no release on Github (https://github.com/nextcloud/android/releases) nor on the Playstore has been made.

As at least four other people are interested in this: 3.28.0 has become available from the Playstore. I had to manually install the update. For me, it fixed the issue (namely #12338).

**Comment by ne20002** [comment]
Still no version on F-Droid.

**Comment by licaon-kter** [comment]
@ne20002 ref: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14551

Did you read https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client yet? :smile_cat: _(the monitor site is inaccessible at the moment)_
