### ISSUE TITLE
Useless ' caracters in sentences

### ISSUE THREAD

**Issue by ldmpub** [nextcloud/android#1395]
### Actual behaviour
Strange two useless caracters => see screen shot attached.
Note: this is not due to french translation.

### Expected behaviour
Remove double ' to get, for instance: "Il y a 3 jours à 9:30" (instead of current "Il y a 3 jours 'à' 9:30").
 
### Steps to reproduce
Open Android App main Window (ie Files).

### Environment data
Android version: 7
Device model: S7

![useless around a](https://user-images.githubusercontent.com/1452146/29534126-1ee6b73c-86b5-11e7-8ac0-bedcb5b9ebe2.png)

**Comment by ldmpub** [comment]
The same problem occurs on a 2d screen => see attachment.

![useless around a - 2d example](https://user-images.githubusercontent.com/1452146/29654125-404ef116-88ac-11e7-82ab-53bec427ffe7.png)

**Comment by ldmpub** [comment]
Hi, 

This seems to have been corrected in last Nexcloud Android version pushed through Google Play beta channel.
Who is responsible for this "hidden" bug correction ;-) ?

**Comment by AndyScherzinger** [comment]
Nobody since we didn't fix anything. The Text comes from an internal Android API... ;-)

**Comment by ldmpub** [comment]
Ok I see. I'm running the same Nextcloud App V2.0 RC5 on 2 devices:
- on Android 7.0 => useless ' are displayed (see screenshots above)
- on Android 6.0.1 => the sentences are slightly different without any 'à' (in french).

**Comment by AndyScherzinger** [comment]
@ldmpub yeah this is then due to the different implementations of Android itself :/

@tobiasKaminsky @mario any idea / proposals? Technically we could check for the locale and then remove certain characters but that would mean working around an Android internal API and might even differ for OEM versions of Android, so even it it might fix the issue in some cases the issue might still remain on certain devices...

**Comment by ldmpub** [comment]
Maybe you can try to use an other Andoid API to build these sentences?

**Comment by AndyScherzinger** [comment]
We can have a look while I doubt there is a non-self-implemented solution since we basically ask Android for the localized relative/absolute date/time string and Android likely doesn't offer 2 APIs doing the same thing :/

Another idea (own implementation then) would be to port the code from the webUI in case it is not done via a lib/framework.

**Comment by ldmpub** [comment]
on Android 8.0 Oreo => useless ' are still displayed

Maybe it's a good idea to manage display here "without" the Android API?
