### ISSUE TITLE
Can't login to nextcloud with ldap backend

### ISSUE THREAD

**Issue by tribut** [nextcloud/android#1419]
### Actual behaviour
NC app replaces login username with ldap id.

### Expected behaviour
App should use the username as I entered it.
 
### Steps to reproduce
1. (I have accounts on two OC instances, one with a regular database backend and one which authenticates against Active Directory.)
2. Add AD account as second account to NC app. Login works. Files are displayed.
3. Switch to normal account.
4. In the side drawer the name of the other account changes to the ldap id (screenshot 1).
5. Switching back does lead to a password prompt, the incorrect username cannot be changed (screenshot 2). Login is no longer possible.

### Environment data
Android version: 6.0.1

Device model: Moto X Play

Stock or customized system: Stock

Nextcloud app version: 2.0.0RC4

Nextcloud server version: Database backend: 12.0.2 , AD backend: 10.0.6

![1](https://user-images.githubusercontent.com/719105/29652889-e30596da-88a7-11e7-9289-199db9e7bc24.png)
![2](https://user-images.githubusercontent.com/719105/29652892-e45deae6-88a7-11e7-8b33-79fd5aff8b10.png)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky is this the issue you fixed?

**Comment by tobiasKaminsky** [comment]
We will include a ldap fix for RC5, but I am unsure if this fixes the described problem.
Once it is release, I'll ping you.

**Comment by AndyScherzinger** [comment]
@tribut Does 2.0.0 RC5 fix this issue for you?

**Comment by tribut** [comment]
No, the behavior is unchanged.

**Comment by tribut** [comment]
No, unfortunately not. The behavior is unchanged.

**Comment by tobiasKaminsky** [comment]
Can you create us a test account for the ldap backend and send the credentials with a link to this issue to android at nextcloud dot com?

**Comment by tribut** [comment]
Unfortunately I do not have the authority to do that. I could mitm the communication of the app with the NC instance if that's helpful?

**Comment by tobiasKaminsky** [comment]
Then it is very hard to debug it.

> Nextcloud server version: Database backend: 12.0.2 , AD backend: 10.0.6

Does this mean that it is working on NC12 (without LDAP) and on NC10 (with LDAP) not?
NC10 is end of life and maybe this ldap bug was fixed in one of the newer version, so please upgrade before we spent more time in debugging this.

**Comment by tribut** [comment]
> Does this mean that it is working on NC12 (without LDAP) and on NC10 (with LDAP) not?

Yes. I have since updated the LDAP-based NC instance to 12.0.2 and the problem remains.

I'll see if I can find something interesting from the http traffic. Otherwise I'll setup another ldap server with only my users' data in it to maybe reproduce it. Creating a test account there would be no problem.

**Comment by tribut** [comment]
Just FYI: I just got feedback that the iOS Nextcloud app has the same behavior: It logs in very briefly and then disconnects. The server shows multiple login attempts with the ldap ID as username.

This also explains why some users were complaining about slow login times, because brute force detection is also kicking in.

**Comment by mario** [comment]
@tribut yes. Explanations have been made by all relevant parties so this will be improved.

cc @tobiasKaminsky

**Comment by tribut** [comment]
Great! :+1:
So further information from me is no longer needed to reproduce this?

**Comment by mario** [comment]
Hopefully not, but you will be needed to test still ;) @tribut

**Comment by marvinwankersteen** [comment]
I have also the same problem. Backend is samba4 with AD.
Server: 12.0.2.
Android: 2.0.0.RC5

**Comment by mario** [comment]
@marvinwankersteen have you deleted your comment? If so, can I get a test account to mario@nextcloud.com?

**Comment by marvinwankersteen** [comment]
@mario yes I deleted my comment because I thought its the wrong issue. If I wipe all data of the nextcloud app, I can login but after that I have to relogin. Its this issue: https://github.com/nextcloud/android/issues/1458
Do you still want a test account?

**Comment by mario** [comment]
Better with RC6?

**Comment by marvinwankersteen** [comment]
Yes, it looks more stable and faster. I will test the next days and give you feedback.
Thanks!

**Comment by tribut** [comment]
Can confirm that I can no longer reproduce this issue on RC6. Thanks everyone!

**Comment by AndyScherzinger** [comment]
@tribut I the ID also replaced with the proper username in the menu (like shown in your screenshots, when you reported this issue)?

**Comment by marvinwankersteen** [comment]
I can confirm that the full name is show in the menu, and not the ID.

**Comment by AndyScherzinger** [comment]
@marvinwankersteen what does get displayed? Number or Character in a colored circle (which one)?

**Comment by tribut** [comment]
It's a character in a colored circle (matching full name on the server. Image from non-ldap server appears to continue to work. 
![img_20170914_085447](https://user-images.githubusercontent.com/719105/30416058-f651c2c0-992a-11e7-9211-7a32c761dee6.jpg)

**Comment by AndyScherzinger** [comment]
@tribut is the avatar image available on the server?

**Comment by marvinwankersteen** [comment]
On the server the image is available

**Comment by AndyScherzinger** [comment]
@mario @tobiasKaminsky any way to reproduce this? I don't have a server with ldap etc. @marvinwankersteen can/did you provide a test account where we could debug this behavior?

**Comment by mario** [comment]
I tried on 8 available servers, both LDAP and non-LDAP. All works as expected. So I'd need a test account on mario@nextcloud.com and a confirmation that latest RC6 is used.
cc @tribut

**Comment by marvinwankersteen** [comment]
@AndyScherzinger @mario 
Who wants the test account? @mario I can reenable your account.

**Comment by tobiasKaminsky** [comment]
Any update @mario?
As I understand it is "only" a problem of not showing the correct avatar? Then we can also postpone it to 2.0.1, or?

**Comment by mario** [comment]
Ah yes, I forgot ... will check today.

**Comment by mario** [comment]
This has bigger issues @tobiasKaminsky that you might be able to debug...

09-20 09:16:29.902 1258-1360/com.nextcloud.client D/ExistenceCheckRemoteOperation: Existence check for https://bla.bla.net/remote.php/webdav/ targeting for  existence finished with HTTP status 401(FAIL)
09-20 09:16:29.902 1258-1360/com.nextcloud.client D/DetectAuthenticationMethodOperation: Authentication method found: BASIC_HTTP_AUTH

cc @marvinwankersteen 
o.O

![screen shot 2017-09-20 at 11 17 44](https://user-images.githubusercontent.com/5810/30636310-5dd8a066-9df5-11e7-893f-792b1b5075e1.png)

**Comment by mario** [comment]
I have to say that the login via web browser does work, but the above is what is shown in our "internal" webview.

**Comment by marvinwankersteen** [comment]
@mario: Tell me if you need logs from the server.

**Comment by mario** [comment]
Sure @marvinwankersteen

**Comment by swalladge** [comment]
I have a similar problem - nextcloud 12.0.3, ldap integration, android app 2.0.0RC6. If I try to login to an ldap account, the app crashes (at least it doesn't correctly add the account). Works fine if I create a non-ldap test user and attempt to login from the app with that.

(Please let me know if I should create a new issue?)

**Comment by tobiasKaminsky** [comment]
@mario can you send me the credentials of marvinwankersteen so that I can debug it?

**Comment by tobiasKaminsky** [comment]
To keep track of it: @swalladge is discussed in https://github.com/nextcloud/android/issues/1458#issuecomment-331077969

**Comment by tobiasKaminsky** [comment]
@mario can you send me the credentials of marvinwankersteen so that I can debug it?

**Comment by tobiasKaminsky** [comment]
@mario can you send me the credentials?
As I am next week only working on monday, I would like to fix this until then and release RC8 on monday.
After that we can release final 2.0 the week after.

**Comment by mario** [comment]
@tobiasKaminsky on it.

**Comment by mario** [comment]
@marvinwankersteen can you please send me an email in the same thread where you've sent me the credentials? I can't seem to find the email right now...

**Comment by marvinwankersteen** [comment]
@mario I resent the mail with the credentials.

**Comment by mario** [comment]
@marvinwankersteen got nothing o.O mario AT nextcloud.com? You can also try mario AT lovelyhq.com.

**Comment by marvinwankersteen** [comment]
Hm strange. I can see in the logs that the mail is sent to the MX of nextcloud.com...

```
Sep 29 23:00:12 529115bbb2c9 postfix/smtp[1627]: 442D35C6: to=<mario@nextcloud.com>, relay=mx.nextcloud.com[88.198.160.131]:25, delay=1.1, delays=0.06/0.01/0.96/0.04, dsn=2.0.0, status=sent (2
50 2.0.0 Ok: queued as 4FCDDD402BA)
```

I resent the mail again.

**Comment by mario** [comment]
Re-tried with master, works like a charm. Thanks @marvinwankersteen.

**Comment by AndyScherzinger** [comment]
@marvinwankersteen @tribut @swalladge we just released 2.0.0RC8 on Google Play. Would you mind giving it a test drive to check if LDAP matters have been resolved for you please? Highly appreciate your help! 😃

**Comment by tribut** [comment]
Still not seeing the profile picture with the ldap account but otherwise no issues I can find.

**Comment by tribut** [comment]
The profile picture still won't show up for the ldap account, otherwise I cannot find any issues.

**Comment by marvinwankersteen** [comment]
Same here. Still no profile picture.

**Comment by mario** [comment]
@marvinwankersteen and @tribut fixed via https://github.com/nextcloud/android/pull/1620, sorry - forgot this!

**Comment by AndyScherzinger** [comment]
@tribut @marvinwankersteen we just released RC9 with an avatar fix on Google Play. Does that version fix the issue for you?

**Comment by mario** [comment]
Awesome, thanks for the account!

**Comment by AndyScherzinger** [comment]
Sweet and kudos to @mario for fixing it 🏆
