### ISSUE TITLE
Keeps asking me to log and relog again

### ISSUE THREAD

**Issue by PhieF** [nextcloud/android#1458]
Using latest git version

Nextcloud keeps asking me to relog, using NextCloud 12.0.2
The app is also slower than ever, unusable when browsing files

**Comment by AndyScherzinger** [comment]
@PhieF can you check for db entries in Nextcloud's bruteforce table and remove them?

**Comment by PhieF** [comment]
It worked for this issue, thanks !
But there is still the problem that it's asking me to relog again each time my server isn't available, and once it is available, it keeps asking me to relog so

1 I log
2 everything is ok
3 my server isn't available
4 asks to relog 
5 I don't relog
6 server is available
7 keeps asking to relog

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky do you know how the client behaves and should behave in this situation?

**Comment by tobiasKaminsky** [comment]
Strange. 
- I connected to a NC12 instance with the new login method.
- turn off data
- refresh data -> not working -> timeout
- closing, opening app
- cycling through existing accounts
- entering folders -> no content as no internet connection
- enabling data connection -> instantly everything is working

@PhieF "server isn't available" what is happening here? Is really the server not available or the device has no internet connection?

**Comment by marvinwankersteen** [comment]
I have the same problem. Server is 12.0.2, Android-App is the dev-Version 2.0.0RC5 from Playstore.

The app continuously wants to relogin. I already checked the bruteforce-db and deleted all entries. Also added my IPs to the whitelist. The app is unusable slow, slow loading, no loading, no content is displayed.

I logged in, press "Grant access", type in my credentials, click "stay logged in", short Popup "Der Versuch, sich anzumelden", short loading of content and than again "Grant access". I tried already to delete app-settings, but some things where not deleted like the URL.

I would like to help you but I dont know where to start...

**Comment by DOWAIZA** [comment]
I have the same problem, on my iPhone too, so maybe a server site problem?

**Comment by DOWAIZA** [comment]
This Problem seems only to appear when i login with an LDAP (openLDAP) user. When i use the local admin user i stay logged in.

**Comment by PhieF** [comment]
My method

- I login
- Server is unavailable BUT my mobile has the internet (issue with DNS in
my case)
- that leads to the problem
Le 31 août 2017 8:58 AM, "Tobias Kaminsky" <notifications@github.com> a
écrit :

Strange.

   - I connected to a NC12 instance with the new login method.
   - turn off data
   - refresh data -> not working -> timeout
   - closing, opening app
   - cycling through existing accounts
   - entering folders -> no content as no internet connection
   - enabling data connection -> instantly everything is working

@PhieF <https://github.com/phief> "server isn't available" what is
happening here? Is really the server not available or the device has no
internet connection?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nextcloud/android/issues/1458#issuecomment-326207898>,
or mute the thread

**Comment by swalladge** [comment]
I'm having similar problems. Randomly gets me to login again, also with LDAP users. This is on Android nougat, after upgrade from lollipop (haven't tried wiping files, but did clear all though settings)

**Comment by mario** [comment]
This should be fixed with latest RC. Please confirm.

**Comment by tobiasKaminsky** [comment]
@PhieF @swalladge can you reply if this is working with RC6?

**Comment by swalladge** [comment]
@tobiasKaminsky no, problem is not resolved. Now it won't let me login at all with an ldap user (app crashes).

**Comment by tobiasKaminsky** [comment]
@swalladge Is it possible that you send us test credentials to android at nextcloud dot com?
Then we can test this.

**Comment by swalladge** [comment]
@tobiasKaminsky certainly! :)

**Comment by tobiasKaminsky** [comment]
@swalladge thank you for your mail.
I tried it twice with latest master (which will be soon RC7) and login worked. 
After that I did some basic test, favorite a file, upload three files, delete a file, download 2 files.

As you mentioned in your email, the account is working :/
Sorry that I have no "better" news for you.

Can you tell something more about the account? I assume this is an "old" one? Is it created with nextcloud or even with ownCloud?

**Comment by swalladge** [comment]
@tobiasKaminsky thanks for testing it out. :)

Some details about the account I can't login with:

- created with ldap the same way as the test ldap user
- two external samba folders (none of which are currently working since security updates after wannacry - can't work out how to fix it)
- no 'special files' that i can think of

Also, strangely, I can login ok with a different ldap account (same setup, samba external folders) on the same android device...

Another thing that may be of interest - I have davdroid syncing the calendar/contacts for the problem account (works fine), but it notifies of an error instantly after I attempt to login with the nextcloud app (and the login fails). Brute force prevention kicking in?

Lol maybe I should just wipe the account and start over... :\

**Comment by tobiasKaminsky** [comment]
Can you uninstall the app and delete/rename also the /sdcard/nextcloud?
If you have root on the phone can you then also try to delete /data/data/com.nextcloud.client as there is the database in it.
I am wild guessing that maybe the account is somehow corruptly stored and the leftovers are killing every new attempt. This then could also explain why a new account is working.

**Comment by swalladge** [comment]
Well well well! Yep confirmed, I can login on a different android device no worries. (This device has never had nextcloud installed.). Time to try deleting nextcloud related data off my phone!

As a side note, clearing the data for nextcloud from the android settings seems to also launch the app - and the button says "manage space" instead of "clear data". Maybe something is overriding it and not allowing the database to be removed?

**Comment by tobiasKaminsky** [comment]
Yes "manage space" retains the database & all account setups. (this was wanted way back)
To have these completely deleted you have to uninstall the app.

**Comment by swalladge** [comment]
Gah this is ridiculous - I still can't login as that user, after uninstalling/reinstalling the app, removing the nextcloud files (couldn't find the /data/data/com.nextcloud.client/ files though). Where do you reckon the problem lies?

The only difference between the two devices that I can think of is that my phone is on Nougat, while the other device is Lollipop.

**Comment by tobiasKaminsky** [comment]
IRC sounds good: #nextcloud-mobile, my name is TobiasK

**Comment by tobiasKaminsky** [comment]
So closing for now :-)

**Comment by infernocs** [comment]
I have this same problem, running the server under freenas and using latest android version and oneplus 5.

**Comment by Iippa** [comment]
Did You find the solutions to this problem? I'm having same problem with Android 8.1.0. Other phone with older Android version works fine.

**Comment by infernocs** [comment]
No, I doubt it will work since the server version is so old.

**Comment by AndyScherzinger** [comment]
@infernocs you ned at least 11.0.8 for the client to work (which is end of life also, so it should be a v12 server on latest patch level at least to be safe).
