### ISSUE TITLE
Linee break not parser and float button alignment error on Tablet

### ISSUE THREAD

**Issue by Deltafox79** [nextcloud/android#1501]
### Actual behaviour
1) the string <string name="auth_register"> not parse \n linee break in italian I read

Non hai ancora un server?**\n**Fai clic qui per ottenerne uno da un fornitore

![screenshot_20170906-150433](https://user-images.githubusercontent.com/2518850/30113928-8ad400ae-9316-11e7-8f7e-b3d706ead578.png)

2) The Float + Button is disallign on Tablet Portrai mode..

![screenshot_20170906-150245](https://user-images.githubusercontent.com/2518850/30113929-8ad70510-9316-11e7-89e4-92481fb054f7.png)

Regards

### Environment data
Android version: 8.0.0 and 7.1.2

Device model: **Nexus 6P - Samsung Tab-S805**

Stock or customized system:

**Stock**

Nextcloud app version:
**1.4.3**

**Comment by AndyScherzinger** [comment]
Hi @Deltafox79,

thanks for your report! :)

1. \n line break is afaik already fixed in the latest release candidate 2.0.0RC5
2. Is actually correct since the FAB belongs to the list which is only filling the left pane while the right pane is to show previews, file details, etc.

Hope this clears things up :)

**Comment by Deltafox79** [comment]
hi I have compiled today the **v2.0.0Rc6** but the issue number 2 is already present.. is not fixed..

![screenshot_20170907-114821](https://user-images.githubusercontent.com/2518850/30157679-3482f98c-93c3-11e7-9157-446ceb000d7f.png)

Best regards

**Comment by AndyScherzinger** [comment]
@Deltafox79 sorry if I didn't elaborate enough. If you have the file listing on the left and e.g. for a file choose "Details" via the long press it will be shown on the right pane see for example the screenshots in #912. The FAB belongs to the left pane.

pinging @nextcloud/designers for further input since this is in general related to the overall tablet UI discussion e.g. #912

**Comment by jancborchardt** [comment]
@AndyScherzinger maybe for tablets (or when both file list and detail view are visible) let's move the FAB to the left instead of right in the list?

**Comment by jancborchardt** [comment]
(Or is there a different design consensus in other Material apps?)

**Comment by AndyScherzinger** [comment]
Hard to tell since imho there hasn't been a single pattern that evolved as a standard. According to Material it should be put into an extended Toolbar (top right), see https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions while that would mean for our layouts that we loose some space due to a larger (in height) toolbar just for the FAB or we always just put it in the bottom right corner for tablet screens.
I'd say either way is fine while I'd go for the larger toolbar simply because the FAB provides actions for the file listing not the details pane so bottom right is missleading since at least I would then expect to have actions linked to the details pane.

**Comment by AndyScherzinger** [comment]
See also https://material.io/guidelines/layout/responsive-ui.html#responsive-ui-patterns at the very bottom of the page.

**Comment by jancborchardt** [comment]
@AndyScherzinger on tablet there's enough space, and it will also feel more light and nicer with more breathing space. So I'd say let's go for the larger top bar with fab in top right. :)

**Comment by AndyScherzinger** [comment]
sounds good to me 👍

**Comment by AndyScherzinger** [comment]
issue for FAB positioning on tablet UIs: #1509
