### ISSUE TITLE
Automatic Upload only works with default Folders (Android 16)

### ISSUE THREAD

**Issue by fsesterh** [nextcloud/android#15291]
### ⚠️ Before posting ⚠️

- [x] This is a **bug**, not a question or an enhancement.
- [x] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [x] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. create a custom folder "photos"
2. set the camera path to sync photos to this folder

RESULT: Nothing gets synced.

- Nextcloud HAS full access to ALL files.
- Manually Sharing a photo/file and selecting the folder configured for automatic sync works instantly!

### Expected behaviour

This should work.

### Actual behaviour

What seems to happen instead is that nextcloud wants to shove everything under SofortUpload/[App/Folder]. I.e. if you activate automatic upload for WhatsApp Images and you DO NOT change the path the App will create

"./SofortUpload/WhatsApp Images"

! Then files are uploaded immediately !

Changing the path breaks uploads for WhatsApp images.

Even worse, if you disable the sync and remove "./SofortUpload/WhatsApp Images" and then reactivate the sync nextcloud will not create the folder again. Manualle creating "./SofortUpload/WhatsApp Images" does not help. You cannot sync this stuff again, ever.

### Android version

16

### Device brand and model

Pixel 9 Pro

### Stock or custom OS?

Stock

### Nextcloud android app version

3.32.2

### Nextcloud server version

31.0.7

### Using a reverse proxy?

I don't know

### Server error logs

```bash

```

**Comment by akavkl** [comment]
Same issue on Pixel 7 Pro.

**Comment by Canuteson** [comment]
Automatic backups of photos used to organize my photos by year and month:
This worked through May. This week i discovered "Automatic Upload" was not activated in my NextCloud mobile app and my photos have not been backing up automatically. I turned it back on, and my photos now default to uploading to an "InstantUpload/Camera" directory, and are not further organized automatically. What changed? Am I crazy? I thought maybe it had been the NextCloud Photos mobile app that was backing up my photos but I don't even see an option there. I definitely don't want to have to manually sort all of my photos in NextCloud by date.

**Comment by Ihon75** [comment]
Same issue for Signal, Threema and, if you change the folder structure by using alternative Gallery, also for the standard gallery

**Comment by fsesterh** [comment]
Update: After a while the client startet upload to my manually created "SofortUpload/Camera" again. Idk why or when exactly. But at least this means that if you break this once you have the chance of it starting to work again. Still not able to move the folder out of the "SofortUpload/" path though.

**Comment by WarnerV** [comment]
Being on the English version, ./InstantUpload/Camera/ is suggested. However, for me it:

- It doesn't create the remote folders
- After I manually create the matching remote folder, the 'autoupload' icon appears on the folder
- Nothing is ever synced

Manual upload works fine though. I'm on OnePlus 13 (Android 15).

**Comment by devlux** [comment]
it's really sad to see such basic use cases just break by installing a new version.

the user chosen folder is not used and also the config to store the files in subfolders is not respected.

**Comment by WarnerV** [comment]
I can unfortunately confirm that also on 3.34.0 RC2 the behavior hasn't changed: not a single auto-upload has been made (OnePlus 13, Android 15)

**Comment by devlux** [comment]
I've found a manual workaround:

* reinstall the app from scratch
* before activating auto upload make sure to have the settings defined properly

so for me the issue seems that somehow the settings were resetted during the update and that I then reactivated auto upload before checking the settings first.

**Comment by MatthiasJSchmidt** [comment]
> I've found a manual workaround:
> 
>     * reinstall the app from scratch
> 
>     * before activating auto upload make sure to have the settings defined properly
> 
> 
> so for me the issue seems that somehow the settings were resetted during the update and that I then reactivated auto upload before checking the settings first.

same here.
Worked after manual remove/reinstall and reconfigure with 3.32.0.
Upgraded to 3.33.0 -> again only partial uploads on one device, no upload on other device.
Now 3.34.0 is coming, would mean to reinstall and reconfigure again -> quite umcomfortable

the only device that works properly is the one that as Beta-Program enabled.

**Comment by WarnerV** [comment]
@MatthiasJSchmidt @devlux 

This doesn't seem to work for me.

-> Do you use custom folders for upload? If not, what's the folder name? Might it be that "SofortUpload" works but "AutoUpload" doesn't?
-> Are you getting the app from Google or from F-Droid (and is there any difference)?

**Comment by fsesterh** [comment]
For me it started working with "SofortUpload" after a couple of days again after I ran into this issue. Has been working since then. Just...weird.

**Comment by devlux** [comment]
@WarnerV yes, I use a custom folder (Photos) and I use the f-droid version but I think the only difference between f-droid and google play is that the first does not rely on google play services and does not support push notifications (logic wise I think they should behave the same).

**Comment by alperozturk96** [comment]
@devlux @fsesterh @WarnerV @MatthiasJSchmidt 

Hello.

We’ve made several fixes to the auto-upload logic and would appreciate your feedback. You can download the updated QA version [here](https://cloud.nextcloud.com/s/H9pqDFSBXj74ibK):

**Comment by epiniguin** [comment]
Hi!
I my case in Android 16 not all photos from the default Camera folder are synchronized. "All permissions" is turned on.
Sometimes Nextcloud synchronizes all photos that I made, sometimes it synchronizes only part of them.

For example, I made 4 photos 2 hours ago. There was not wifi connection at that time.
After the WIFI appeared, Nextcloud synchronized only 1 photo from these 4 photos. I have been waiting for 30 minutes but it does not synchronize other 3 photos and there is nothing in the queue.

**Comment by alperozturk96** [comment]
Hello

The entire auto-upload logic has been updated with significant improvements and enhancements. These changes will be included in version 3.35.0. 

In the meantime, you can test the latest [development version](https://f-droid.org/en/packages/com.nextcloud.android.beta/) available on F-Droid. 

We would greatly appreciate your feedback once we release the 3.35.0 RC1.

**Comment by alperozturk96** [comment]
Hello 

We released RC versions. Could you please try with [3.35.0 RC2](https://github.com/nextcloud/android/releases/tag/rc-3.35.0-02) and share your feedback with us?

**Comment by devlux** [comment]
hi @alperozturk96 unfortunately this is still broken with r3.35.2. see also https://github.com/nextcloud/android/issues/16334

**Comment by alperozturk96** [comment]
Hello

Could you please try this [PR](https://github.com/nextcloud/android/pull/16393)?

And from Settings → Logs → via "auto upload", "upload", "ContentObserverWork" keyword filter logs and share with us the logs. This is important to find issues.

**Comment by alperozturk96** [comment]
Hey,

Could you please try to reproduce the issue described in the first message using [35.0.0 RC2](https://github.com/nextcloud/android/releases/tag/rc-35.0.0-02) and let us know whether the issue has been resolved?

* If the issue is **resolved**, please share your feedback with us.
* If the issue is **still present**, please provide the relevant logs and any additional details that might help us investigate.

To help us keep things organized and make sure we can track each issue properly, please keep this discussion focused on the issue described in the original report.

If you notice a different issue, have a separate feature request, or would like to discuss another improvement, please create a **separate issue** for it. This will help us investigate and track each topic individually.

Thank you for your help and feedback! 🙌
