### ISSUE TITLE
AutoUpload Duplicate File Uploads

### ISSUE THREAD

**Issue by alperozturk96** [nextcloud/android#15572]
### ⚠️ Before posting ⚠️

- [x] This is a **bug**, not a question or an enhancement.
- [x] I've [searched for similar issues](https://github.com/nextcloud/android/issues) and didn't find a duplicate.
- [x] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

???

### Expected behaviour

Uploaded file should not re-uploaded again.

### Actual behaviour

Uploaded file should not re-uploading again.

### Android version

16

### Device brand and model

Google Pixel 9

### Stock or custom OS?

Stock

### Nextcloud android app version

3.32.3

### Nextcloud server version

???

### Using a reverse proxy?

I don't know

### Server error logs

```bash

```

**Comment by gschenck** [comment]
This is really annoying and spams the server log with thousands of messages.

**Comment by wrenix** [comment]
And all the changes per hand to cleanup the changes.

**Comment by eskopp** [comment]
> And all the changes per hand to cleanup the changes.


You can use fdupes

**Comment by alperozturk96** [comment]
@gschenck @wrenix @eskopp 

Hello.

We’ve made several fixes to the auto-upload logic and would appreciate your feedback. You can download the updated QA version [here](https://cloud.nextcloud.com/s/H9pqDFSBXj74ibK):

**Comment by alperozturk96** [comment]
Hello 

We released the RC versions. Auto-Upload logic completely redesigned. Could you please try with [3.35.0 RC2](https://github.com/nextcloud/android/releases/tag/rc-3.35.0-02) and share your feedback with us?

**Comment by eskopp** [comment]
Sorry, I forgot about RC2. I now have RC3 installed. This does not solve the problem (for me), at least. I can now manage the duplicates well with fdupes. However, I get the message “Unknown Error” for 90% of the automatic upload images. If desired, I can take a screenshot of the Android app.

**Comment by alperozturk96** [comment]
@eskopp 

Hello

Thank you for taking the time to share your feedback with us.

The Auto Upload feature works based on multiple conditions, and the expected outcome can vary depending on how it is configured. To better understand your setup, your expectations, and whether the current behavior matches them, or where we can improve, I need the following informations.

1. What is your auto upload configuration?
    Only upload on un-metered wi-fi on or off?
    Only upload when charging on or off?
    Also upload existing file on or off?
    Use sub-folders on or off?
    Exclude hidden on or off?
    Original file will be...?  Kept in original folder, moved to app folder, deleted
    What to do if file already exists? Ask me every time (which means create a notification for each file conflict), overwrite remote version, rename new version, skip uploading

2. What is the Android version and phone model?

3. Which storage permission do you have? All files access or media files or limited media files?

4. Was it custom folder, or you directly press the cloud button for specific folder from overview page (Settings → Auto upload)?

5. What is your expectation if you choose to ask me every time for file already exist option? Do you expect to see new notification for each conflict to resolve conflict or do you expect from app to not attempt re-upload those cancelled, failed uploads, but user should be able to resolve them from the upload list?

And lastly from Settings → Logs → via "auto upload" or "upload" keyword filter logs and share with us the logs. This is important to debug the “Unknown error” message. Before sharing logs, please don't forget to remove sensitive information.

Looking forward to your reply.

**Comment by barts2108** [comment]
Feedback on 3.35.2 Android app.

Camera folder :
Auto upload: ON
Only upload on unmetered Wi-Fi : ON
Only upload when charging : OFF
Also upload existing files : ON
Use subfolders : OFF
Original file will be :  Kept in original folder
What to do if file already exists:  Ask me every time

Phone : Samsung galaxy A52 5G, Android 14, One UI 6.1

Today : 

- WiFi is ON, but not connected to any network
- Mobile Data is ON
- 11:23:10 made a photo with the camera
- 17:45 back home, WiFi connects to home network
- Conflict notification
- Checking cloud folder : 20260217_112310.jpg exists on the cloud folder with timestamp 11:23:11

Bug:
- Even though the setting is ONLY Unmetered WiFi, the upload occurs immediatley over Mobile data.
Bug:
- When connecting to WiFi it tries to upload again (probably because of the same setting)
