### ISSUE TITLE
Auto upload - Button to manually scan files in the file system and re-upload missing files.

### ISSUE THREAD

**Issue by roasted-watermelon** [nextcloud/android#15782]
**Is your feature request related to a problem? Please describe.**
Nextcloud auto upload is buggy and often misses some files. This is an issue that is present since several months / years. See the following discussions:  
https://help.nextcloud.com/t/auto-upload-is-skipping-random-pics/222184  
https://help.nextcloud.com/t/android-client-does-not-auto-upload-all-images/216849  
https://github.com/nextcloud/android/issues/13792  
https://github.com/nextcloud/android/issues/14365  

There are many more.

**Describe the solution you'd like**
It is observed that if the auto upload is deleted and created again (with the option of uploading existing files) the missing files are uploaded. Since there does not seem an easy fix for this problem, it would be better to surface a button to rescan the file system. That button may internally just delete the auto upload and create it again.

**Describe alternatives you've considered**
Already mentioned above - deleting and recreating the auto upload.

**Additional context**
N/A

**Comment by alperozturk96** [comment]
@roasted-watermelon 

Hello.

We’ve made several fixes to the auto-upload logic and would appreciate your feedback. You can download the updated QA version [here](https://cloud.nextcloud.com/s/H9pqDFSBXj74ibK):

**Comment by roasted-watermelon** [comment]
@alperozturk96 thanks for the link, but it doesn't open for me, keeps loading. Nevermind, I will wait for the fixes to come to stable. Thnx.

**Comment by alperozturk96** [comment]
Hello 

We released the RC versions. Auto-Upload logic completely redesigned. Could you please try with [3.35.0 RC2](https://github.com/nextcloud/android/releases/tag/rc-3.35.0-02) and share your feedback with us?

**Comment by roberthr74** [comment]
This is getting even worse. Only one out of 4 photos came through.

**Comment by sideshowbob84** [comment]
i think the button would be a good help. I created the issue #13792 the problem still persists with the new auto upload logic. I am back from holidays and approx half of the photos is missing.

**Comment by ludekvodicka** [comment]
I have exactly same issue unfortunately. some photos are correctly uploaded and some are missing. Any way how to fix it?

**Comment by ohthehugemanatee** [comment]
Flaky detection for auto-upload has been a frequent report for years, despite lots of effort and now a complete rebuild of this very user-visible feature. A manual re-scan trigger is trivial to implement and would catch a lot of these cases. A simple workaround like this would reduce the severity of all those reports.

I cheekily threw together #17462 as an example: this feature is just 20 lines, entirely using existing code paths. If this issue is Approved that PR is a reasonable starting point.

**Comment by tobiasKaminsky** [comment]
We at Nextcloud try to have as less manual user interaction as possible.
Thus we aim for fixing the edge cases of auto upload instead of having a manual sync button.

So while this is a nice quick win, we do not think this will benefit in long(er) run for users.

Thus I encourage you to work with @alperozturk96 to double check why you are missing some uploads.
He can also create specific debug builds for you, which can be used as a direct drop-in replacement, so that we can enhance the app for all, with your help.

**Comment by alperozturk96** [comment]
You can also test via latest QA APK and share your feedback. Thank you.

https://github.com/nextcloud/android/pull/17401

**Comment by ohthehugemanatee** [comment]
Thanks for the fast response, and automation that works over manual action is a very sensible policy.

That said, in a GA feature I suggest that the scale, persistence, and diagnostic state makes this a poor fit for a hard line "no manual failover option" policy.

For scale: a GH query for issues in this repo with "auto upload", "autoupload" or "instant upload" in the title returns 749 unique issues from 589 distinct reporters, opened continuously from #25 in June 2016 through this month. Filter titles for detection-failure wording (missing, skipped, ignored, not detected, not uploaded, randomly, unreliable, stopped working) and 147 issues from 129 reporters remain, 48 of them open. Every year since 2016 has at least 28 new titled issues, and 2025 had 91. This class of bug has persisted through an enormous amount of work and a decade of releases. 

#16550 is the right way to address a category of hard-to-reproduce bugs, thank you for your work! It argues even more strongly for a failover option though: 6 months of work by two maintainers has surfaced 18 linked issues, 5 closed, and new ones keep arriving after 33.0.1, 33.1.0, 33.1.1 and 34.1.0. The combined tracker (correctly) communicates to users that *right now a missed file is a common, unrecoverable failure, and there's no date to wait for.*

If there's no date to wait for, #16550 should include the 20 lines of code to make it a "common, *recoverable* failure" while the rest of the issues runs their course.

Alternatively, Nextcloud could target a milestone or release for #16550, so it's "unrecoverable until". 

FWIW: in my case, I have 2052 files in my camera folder that auto upload missed, dating back to 2022-04-01. I have disabled and re-enabled the folder many times since then, with "upload existing files" turned on. It sometimes catches some files, sometimes not. My other users have similar stories; most have gone back to google photos for camera backups.

**Comment by ludekvodicka** [comment]
> We at Nextcloud try to have as less manual user interaction as possible. Thus we aim for fixing the edge cases of auto upload instead of having a manual sync button.
> 
> So while this is a nice quick win, we do not think this will benefit in long(er) run for users.
> 
> Thus I encourage you to work with [@alperozturk96](https://github.com/alperozturk96) to double check why you are missing some uploads. He can also create specific debug builds for you, which can be used as a direct drop-in replacement, so that we can enhance the app for all, with your help.

Nextcloud is a great product, but this auto-upload issue is honestly very annoying. It is not the first time I have found missing photos, and sometimes I do not even notice it immediately.

I understand that the long-term goal is to fix auto upload completely. But until then, a simple **rescan/resync button under Settings → Debug** would be very useful as a fallback.

After a longer vacation this became a real problem for me. I eventually had to use another app for photo sync and then move the files back into Nextcloud on the server with a script. It works, but it is obviously not ideal.

So even as a temporary/debug feature, a manual rescan button would be very welcome.
