### ISSUE TITLE
Android App (from f-droid terminates while login)

### ISSUE THREAD

**Issue by ip6li** [nextcloud/android#1958]
### Actual behaviour

1. Start app
1. Enter username/PIN (or password)

then wait circle appears for a few seconds, after that app terminates without message.

### Expected behaviour

App should display Nextcloud server contents in case of successful login or error message if login has failed.
 
### Steps to reproduce

1. Install app from f-droid
2. Enter server url
3. Enter credentials

### Environment data
Android version: 7.1.2

Device model: Samsung S7 (SM-G935F)

Stock or customized system: LinageOS 14.1-20180110-NIGHTLY-hero2lte
(problem occurs with older versions, also)

Nextcloud app version: 2.0.1 (from f-droid)

Nextcloud server version: 12.0.4

#### Web server error log
```
192.168.0.6 - - [13/Jan/2018:09:57:32 +0000] "GET /status.php HTTP/1.1" 200 157 "-" "Mozilla/5.0 (Android) ownCloud-android/2.0.1"
192.168.0.6 - - [13/Jan/2018:09:57:32 +0000] "HEAD /remote.php/webdav/ HTTP/1.1" 401 0 "-" "Mozilla/5.0 (Android) ownCloud-android/2.0.1"
192.168.0.6 - - [13/Jan/2018:09:57:32 +0000] "GET /index.php/login/flow HTTP/1.1" 200 7599 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /core/vendor/select2/select2.css?v=1a0cd508968dd9ddc503a04bef24d197-0 HTTP/1.1" 200 17686 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /core/vendor/jquery-ui/themes/base/jquery-ui.css?v=1a0cd508968dd9ddc503a04bef24d197-0 HTTP/1.1" 200 32269 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /core/css/jquery-ui-fixes.css?v=1a0cd508968dd9ddc503a04bef24d197-0 HTTP/1.1" 200 3612 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /apps/files_versions/css/versions.css?v=1a0cd508968dd9ddc503a04bef24d197-0 HTTP/1.1" 200 1208 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /apps/files_pdfviewer/css/style.css?v=1a0cd508968dd9ddc503a04bef24d197-0 HTTP/1.1" 200 140 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /apps/files_videoplayer/css/style.css?v=1a0cd508968dd9ddc503a04bef24d197-0 HTTP/1.1" 200 7473 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /core/css/login/authpicker.css?v=1a0cd508968dd9ddc503a04bef24d197-0 HTTP/1.1" 200 157 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /core/css/jquery.ocdialog.css?v=1a0cd508968dd9ddc503a04bef24d197-0 HTTP/1.1" 200 1491 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /core/css/guest.css?v=1a0cd508968dd9ddc503a04bef24d197-0 HTTP/1.1" 200 16488 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /core/search/js/search.js?v=1a0cd508968dd9ddc503a04bef24d197-0 HTTP/1.1" 200 12062 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /core/vendor/core.js?v=1a0cd508968dd9ddc503a04bef24d197-0 HTTP/1.1" 200 1037663 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /core/l10n/de_DE.js?v=1a0cd508968dd9ddc503a04bef24d197-0 HTTP/1.1" 200 41736 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /apps/encryption/l10n/de_DE.js?v=1a0cd508968dd9ddc503a04bef24d197-0 HTTP/1.1" 200 10016 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /apps/encryption/js/encryption.js?v=1a0cd508968dd9ddc503a04bef24d197-0 HTTP/1.1" 200 816 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /apps/files_pdfviewer/js/previewplugin.js?v=1a0cd508968dd9ddc503a04bef24d197-0 HTTP/1.1" 200 5028 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /apps/files_videoplayer/js/viewer.js?v=1a0cd508968dd9ddc503a04bef24d197-0 HTTP/1.1" 200 3634 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /apps/gallery/l10n/de_DE.js?v=1a0cd508968dd9ddc503a04bef24d197-0 HTTP/1.1" 200 8415 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /core/js/oc.js?v=1a0cd508968dd9ddc503a04bef24d197 HTTP/1.1" 200 3559 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /core/js/jquery-ui-fixes.js?v=1a0cd508968dd9ddc503a04bef24d197-0 HTTP/1.1" 200 260 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /core/js/files/fileinfo.js?v=1a0cd508968dd9ddc503a04bef24d197-0 HTTP/1.1" 200 2141 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /core/js/files/client.js?v=1a0cd508968dd9ddc503a04bef24d197-0 HTTP/1.1" 200 20300 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /core/js/contactsmenu.js?v=1a0cd508968dd9ddc503a04bef24d197-0 HTTP/1.1" 200 13409 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /core/js/login/authpicker.js?v=1a0cd508968dd9ddc503a04bef24d197-0 HTTP/1.1" 200 524 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /apps/theming/styles?v=0 HTTP/1.1" 200 768 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /js/core/merged-template-prepend.js?v=1a0cd508968dd9ddc503a04bef24d197-0 HTTP/1.1" 200 39515 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /js/core/merged-share-backend.js?v=1a0cd508968dd9ddc503a04bef24d197-0 HTTP/1.1" 200 22561 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /apps/theming/js/theming?v=0 HTTP/1.1" 200 207 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /core/img/background.jpg?v=0 HTTP/1.1" 200 95212 "https://nextcloud.example.net/apps/theming/styles?v=0" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:33 +0000] "GET /core/img/logo.svg?v=0 HTTP/1.1" 200 1232 "https://nextcloud.example.net/apps/theming/styles?v=0" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:34 +0000] "GET /core/fonts/OpenSans-Light.woff HTTP/1.1" 200 62844 "https://nextcloud.example.net/core/css/guest.css?v=1a0cd508968dd9ddc503a04bef24d197-0" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:34 +0000] "GET /core/img/actions/confirm-white.svg?v=2 HTTP/1.1" 200 841 "https://nextcloud.example.net/core/css/guest.css?v=1a0cd508968dd9ddc503a04bef24d197-0" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:34 +0000] "GET /core/fonts/OpenSans-Semibold.woff HTTP/1.1" 200 69888 "https://nextcloud.example.net/core/css/guest.css?v=1a0cd508968dd9ddc503a04bef24d197-0" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:57:34 +0000] "GET /core/img/favicon.ico HTTP/1.1" 200 3262 "-" "Samsung SM-G935F"
192.168.0.6 - - [13/Jan/2018:09:58:14 +0000] "GET /status.php HTTP/1.1" 200 157 "-" "Mozilla/5.0 (Android) ownCloud-android/2.0.1"
192.168.0.6 - - [13/Jan/2018:09:58:14 +0000] "HEAD /remote.php/webdav/ HTTP/1.1" 401 0 "-" "Mozilla/5.0 (Android) ownCloud-android/2.0.1"
192.168.0.6 - *** [13/Jan/2018:09:58:15 +0000] "HEAD /remote.php/webdav/ HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Android) ownCloud-android/2.0.1"
192.168.0.6 - *** [13/Jan/2018:09:58:15 +0000] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 352 "-" "Mozilla/5.0 (Android) ownCloud-android/2.0.1"
```

#### Nextcloud log (data/nextcloud.log)
```
01-13 10:57:05.703 8790-8790/com.nextcloud.client W/System: ClassLoader referenced unknown path: /mnt/expand/84a2f432-9c0c-4d92-b1ea-cfed53b220d3/app/com.nextcloud.client-1/lib/arm64
01-13 10:57:05.745 8790-8790/com.nextcloud.client I/MultiDex: VM with version 2.1.0 has multidex support
01-13 10:57:05.745 8790-8790/com.nextcloud.client I/MultiDex: Installing application
01-13 10:57:05.745 8790-8790/com.nextcloud.client I/MultiDex: VM has multidex support, MultiDex support library is disabled.
01-13 10:57:05.828 8790-8790/com.nextcloud.client I/SQL: Entering in onCreate
01-13 10:57:05.828 8790-8814/com.nextcloud.client D/ThumbnailsCacheManager: create dir: /storage/emulated/0/Android/data/com.nextcloud.client/cache/thumbnailCache
01-13 10:57:05.993 8790-8790/com.nextcloud.client D/JobProxy24: Schedule periodic jobInfo success, request{id=1, tag=FilesSyncJob}, interval 00:15:00, flex 00:05:00
01-13 10:57:06.063 8790-8790/com.nextcloud.client V/FileDisplayActivity: onCreate() start
01-13 10:57:06.070 8790-8790/com.nextcloud.client W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
01-13 10:57:06.074 8790-8790/com.nextcloud.client D/FileDisplayActivity: onCreate(Bundle) starting
01-13 10:57:06.201 8790-8790/com.nextcloud.client I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
01-13 10:57:06.315 8790-8790/com.nextcloud.client V/FileDisplayActivity: onCreate() end
01-13 10:57:06.317 8790-8790/com.nextcloud.client D/FileDisplayActivity: onStart() starting
01-13 10:57:06.329 8790-8817/com.nextcloud.client D/ExternalLinks: links disabled
01-13 10:57:06.357 8790-8790/com.nextcloud.client E/FileDisplayActivity: Access to unexisting list of files fragment!!
01-13 10:57:06.360 8790-8790/com.nextcloud.client V/FileDisplayActivity: onResume() start
01-13 10:57:06.360 8790-8790/com.nextcloud.client D/FileDisplayActivity: onResume() starting
01-13 10:57:06.361 8790-8790/com.nextcloud.client I/OCFileListFragment: onAttach
01-13 10:57:06.365 8790-8790/com.nextcloud.client I/OCFileListFragment: onCreateView() start
01-13 10:57:06.365 8790-8790/com.nextcloud.client D/ExtendedListFragment: onCreateView
01-13 10:57:06.468 8790-8790/com.nextcloud.client I/OCFileListFragment: onCreateView() end
01-13 10:57:06.468 8790-8790/com.nextcloud.client I/OCFileListFragment: onActivityCreated() start
01-13 10:57:06.494 8790-8790/com.nextcloud.client V/FileDisplayActivity: onResume() end
01-13 10:57:06.518 8790-8821/com.nextcloud.client D/JobRescheduleService: Reschedule service started
01-13 10:57:06.545 8790-8790/com.nextcloud.client D/OperationsService: Creating service
01-13 10:57:06.546 8790-8806/com.nextcloud.client I/AccountAuthenticator: Adding account with type nextcloud and auth token null
01-13 10:57:06.550 8790-8790/com.nextcloud.client D/FileDownloader: Creating service
01-13 10:57:06.570 8790-8790/com.nextcloud.client D/FileUploader: Creating service
01-13 10:57:06.578 8790-8790/com.nextcloud.client V/UploadsStorageManager: Updating state of any killed upload
01-13 10:57:06.582 8790-8790/com.nextcloud.client V/UploadsStorageManager: No upload was killed
01-13 10:57:06.585 8790-8790/com.nextcloud.client D/FileObserverService: onCreate
01-13 10:57:06.588 8790-8790/com.nextcloud.client D/FileObserverService: Starting command Intent { act=com.owncloud.android.services.observer.FileObserverService.action.START_OBSERVATION cmp=com.nextcloud.client/com.owncloud.android.services.observer.FileObserverService }
01-13 10:57:06.588 8790-8790/com.nextcloud.client D/FileObserverService: Loading all kept-in-sync files from database to start watching them
01-13 10:57:06.595 8790-8790/com.nextcloud.client V/FileDisplayActivity: onPause() start
01-13 10:57:06.598 8790-8790/com.nextcloud.client D/FileDisplayActivity: onPause() ending
01-13 10:57:06.598 8790-8790/com.nextcloud.client V/FileDisplayActivity: onPause() end
01-13 10:57:06.711 8790-8790/com.nextcloud.client D/FileActivity: Operations service connected
01-13 10:57:06.711 8790-8790/com.nextcloud.client D/FileDisplayActivity: Download service connected
01-13 10:57:06.712 8790-8790/com.nextcloud.client D/FileDisplayActivity: Upload service connected
01-13 10:57:06.717 8790-8790/com.nextcloud.client D/AuthenticatorActivity: onCreate(Bundle) starting
01-13 10:57:06.726 8790-8795/com.nextcloud.client I/art: Do partial code cache collection, code=21KB, data=30KB
01-13 10:57:06.726 8790-8795/com.nextcloud.client I/art: After code cache collection, code=20KB, data=29KB
01-13 10:57:06.726 8790-8795/com.nextcloud.client I/art: Increasing code cache capacity to 128KB
01-13 10:57:06.733 8790-8790/com.nextcloud.client W/System: ClassLoader referenced unknown path: /system/app/webview/lib/arm64
01-13 10:57:06.734 8790-8790/com.nextcloud.client D/ApplicationLoaders: ignored Vulkan layer search path /system/app/webview/lib/arm64:/system/app/webview/webview.apk!/lib/arm64-v8a:/system/lib64:/vendor/lib64 for namespace 0x7fb0d7e0f0
01-13 10:57:06.737 8790-8790/com.nextcloud.client I/WebViewFactory: Loading com.android.webview version 63.0.3239.111 (code 1)
01-13 10:57:06.775 8790-8790/com.nextcloud.client I/cr_LibraryLoader: Time to load native libraries: 2 ms (timestamps 4849-4851)
01-13 10:57:06.779 8790-8790/com.nextcloud.client I/chromium: [INFO:library_loader_hooks.cc(36)] Chromium logging enabled: level = 0, default verbosity = 0
01-13 10:57:06.779 8790-8790/com.nextcloud.client I/cr_LibraryLoader: Expected native library version number "63.0.3239.111", actual native library version number "63.0.3239.111"
01-13 10:57:06.808 8790-8790/com.nextcloud.client I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
01-13 10:57:06.822 8790-8790/com.nextcloud.client I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
01-13 10:57:06.824 8790-8790/com.nextcloud.client I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
01-13 10:57:06.825 8790-8790/com.nextcloud.client I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
01-13 10:57:06.831 8790-8790/com.nextcloud.client I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
01-13 10:57:06.841 8790-8790/com.nextcloud.client D/AuthenticatorActivity: onStart() starting
01-13 10:57:06.843 8790-8790/com.nextcloud.client D/AuthenticatorActivity: onResume() starting
01-13 10:57:06.904 8790-8820/com.nextcloud.client I/OpenGLRenderer: Initialized EGL, version 1.4
01-13 10:57:06.904 8790-8820/com.nextcloud.client D/OpenGLRenderer: Swap behavior 1
01-13 10:57:06.905 8790-8790/com.nextcloud.client D/AuthenticatorActivity: onPause() ending
01-13 10:57:06.916 8790-8820/com.nextcloud.client D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1440x2560]-format:1
01-13 10:57:07.121 8790-8790/com.nextcloud.client D/WhatsNewActivity: onCreate(Bundle) starting
01-13 10:57:07.159 8790-8790/com.nextcloud.client D/WhatsNewActivity: onStart() starting
01-13 10:57:07.161 8790-8790/com.nextcloud.client D/WhatsNewActivity: onResume() starting
01-13 10:57:07.497 8790-8820/com.nextcloud.client D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1440x2560]-format:1
01-13 10:57:08.024 8790-8790/com.nextcloud.client D/AuthenticatorActivity: onSaveInstanceState(Bundle) starting
01-13 10:57:08.031 8790-8790/com.nextcloud.client D/AuthenticatorActivity: onStop() ending
01-13 10:57:08.036 8790-8790/com.nextcloud.client V/FileDisplayActivity: onSaveInstanceState() start
01-13 10:57:08.042 8790-8790/com.nextcloud.client D/FileDisplayActivity: onSaveInstanceState(Bundle) starting
01-13 10:57:08.043 8790-8790/com.nextcloud.client D/ExtendedListFragment: onSaveInstanceState()
01-13 10:57:08.048 8790-8790/com.nextcloud.client V/FileDisplayActivity: onSaveInstanceState() end
01-13 10:57:08.049 8790-8790/com.nextcloud.client D/FileDisplayActivity: onStop() ending
01-13 10:57:15.619 8790-8790/com.nextcloud.client D/WhatsNewActivity: onPause() ending
01-13 10:57:15.630 8790-8790/com.nextcloud.client D/AuthenticatorActivity: onStart() starting
01-13 10:57:15.631 8790-8790/com.nextcloud.client D/AuthenticatorActivity: onResume() starting
01-13 10:57:15.668 8790-8820/com.nextcloud.client D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1440x2560]-format:1
01-13 10:57:15.738 8790-8820/com.nextcloud.client D/OpenGLRenderer: endAllActiveAnimators on 0x7fa02c5c00 (RippleDrawable) with handle 0x7f8f973040
01-13 10:57:16.006 8790-8790/com.nextcloud.client D/WhatsNewActivity: onStop() ending
01-13 10:57:16.013 8790-8790/com.nextcloud.client D/WhatsNewActivity: onDestroy() ending
01-13 10:57:16.527 8790-8821/com.nextcloud.client D/JobRescheduleService: Reschedule 0 jobs of 1 jobs
01-13 10:57:32.300 8790-8790/com.nextcloud.client D/OperationsService: Starting command with id 1
01-13 10:57:32.301 8790-8790/com.nextcloud.client W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
01-13 10:57:32.302 8790-8822/com.nextcloud.client D/SimpleFactoryManager: getClientFor(OwnCloudAccount ... : 
01-13 10:57:32.305 8790-8822/com.nextcloud.client D/NetworkUtils: Searching known-servers store at /mnt/expand/84a2f432-9c0c-4d92-b1ea-cfed53b220d3/user/0/com.nextcloud.client/files/knownServers.bks
01-13 10:57:32.306 8790-8822/com.nextcloud.client D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
                                                                           
                                                                           [ 01-13 10:57:32.320  8790: 8840 W/         ]
                                                                           g2d stretchFimgApi_v5 function does not exist
01-13 10:57:32.339 8790-8822/com.nextcloud.client D/OwnCloudClient #0: Creating OwnCloudClient
01-13 10:57:32.340 8790-8822/com.nextcloud.client V/SimpleFactoryManager:     new client {@nextcloud.example.net, 252905648}
01-13 10:57:32.352 8790-8822/com.nextcloud.client D/OwnCloudClient #0: REQUEST GET /status.php
01-13 10:57:32.358 8790-8822/com.nextcloud.client D/AdvancedSslSocketFactory: Creating SSL Socket with remote nextcloud.example.net:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@7ca8c4f
01-13 10:57:32.358 8790-8822/com.nextcloud.client D/AdvancedSslSocketFactory:  ... with connection timeout 50000 and socket timeout 50000
01-13 10:57:32.412 8790-8822/com.nextcloud.client I/ServerNameIndicator: SSLSocket implementation: com.android.org.conscrypt.OpenSSLSocketImpl
01-13 10:57:32.413 8790-8822/com.nextcloud.client I/ServerNameIndicator: SNI done, hostname: nextcloud.example.net
01-13 10:57:32.669 8790-8822/com.nextcloud.client W/HttpMethodBase: Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
01-13 10:57:32.678 8790-8822/com.nextcloud.client I/GetRemoteStatusOperation: Connection check at https://nextcloud.example.net: Operation finished with HTTP status code -1 (success)
01-13 10:57:32.678 8790-8822/com.nextcloud.client D/GetServerInfoOperation: Trying empty authorization to detect authentication method
01-13 10:57:32.683 8790-8822/com.nextcloud.client D/OwnCloudClient #0: REQUEST HEAD /remote.php/webdav/
01-13 10:57:32.755 8790-8822/com.nextcloud.client I/AuthChallengeProcessor: basic authentication scheme selected
01-13 10:57:32.759 8790-8822/com.nextcloud.client I/HttpMethodDirector: No credentials available for BASIC 'Nextcloud'@nextcloud.example.net:443
01-13 10:57:32.761 8790-8822/com.nextcloud.client D/ExistenceCheckRemoteOperation: Existence check for https://nextcloud.example.net/remote.php/webdav/ targeting for  existence finished with HTTP status 401(FAIL)
01-13 10:57:32.762 8790-8822/com.nextcloud.client D/DetectAuthenticationMethodOperation: Authentication method found: BASIC_HTTP_AUTH
01-13 10:57:32.764 8790-8822/com.nextcloud.client D/OperationsService: Called 1 listeners
01-13 10:57:32.764 8790-8822/com.nextcloud.client D/OperationsService: Stopping after command with id 1
01-13 10:57:32.817 8790-8790/com.nextcloud.client I/cr_BrowserStartup: Initializing chromium process, singleProcess=true
01-13 10:57:32.904 8790-8814/com.nextcloud.client W/cr_CrashFileManager: /mnt/expand/84a2f432-9c0c-4d92-b1ea-cfed53b220d3/user/0/com.nextcloud.client/cache/WebView/Crash Reports does not exist or is not a directory
01-13 10:57:32.904 8790-8877/com.nextcloud.client E/chromium: [ERROR:devtools_http_handler.cc(249)] Cannot start http server for devtools. Stop devtools.
01-13 10:57:32.912 8790-8790/com.nextcloud.client I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$6>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/RenderProcessGoneDetail;
01-13 10:57:32.912 8790-8790/com.nextcloud.client I/art:     at void com.android.webview.chromium.WebViewChromium.init(java.util.Map, boolean) (WebViewChromium.java:4731)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:648)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:577)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:560)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:547)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at java.lang.Object java.lang.reflect.Constructor.newInstance0!(java.lang.Object[]) (Constructor.java:-2)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at java.lang.Object java.lang.reflect.Constructor.newInstance(java.lang.Object[]) (Constructor.java:430)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at android.view.View android.view.LayoutInflater.createView(java.lang.String, java.lang.String, android.util.AttributeSet) (LayoutInflater.java:645)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at android.view.View com.android.internal.policy.PhoneLayoutInflater.onCreateView(java.lang.String, android.util.AttributeSet) (PhoneLayoutInflater.java:58)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at android.view.View android.view.LayoutInflater.onCreateView(android.view.View, java.lang.String, android.util.AttributeSet) (LayoutInflater.java:717)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:785)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet) (LayoutInflater.java:727)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at void android.view.LayoutInflater.rInflate(org.xmlpull.v1.XmlPullParser, android.view.View, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:858)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at void android.view.LayoutInflater.rInflateChildren(org.xmlpull.v1.XmlPullParser, android.view.View, android.util.AttributeSet, boolean) (LayoutInflater.java:821)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at android.view.View android.view.LayoutInflater.inflate(org.xmlpull.v1.XmlPullParser, android.view.ViewGroup, boolean) (LayoutInflater.java:518)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup, boolean) (LayoutInflater.java:426)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup) (LayoutInflater.java:377)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at void android.support.v7.app.AppCompatDelegateImplV9.setContentView(int) (AppCompatDelegateImplV9.java:292)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at void com.owncloud.android.authentication.AuthenticatorActivity.onGetServerInfoFinish(com.owncloud.android.lib.common.operations.RemoteOperationResult) (AuthenticatorActivity.java:1414)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at void com.owncloud.android.authentication.AuthenticatorActivity.onRemoteOperationFinish(com.owncloud.android.lib.common.operations.RemoteOperation, com.owncloud.android.lib.common.operations.RemoteOperationResult) (AuthenticatorActivity.java:1313)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at void com.owncloud.android.services.OperationsService$1.run() (OperationsService.java:726)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at void android.os.Looper.loop() (Looper.java:154)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6186)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:889)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:779)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.RenderProcessGoneDetail" on path: DexPathList[[zip file "/system/app/webview/webview.apk"],nativeLibraryDirectories=[/system/app/webview/lib/arm64, /system/app/webview/webview.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at void com.android.webview.chromium.WebViewChromium.init(java.util.Map, boolean) (WebViewChromium.java:4731)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:648)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:577)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:560)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:547)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at java.lang.Object java.lang.reflect.Constructor.newInstance0!(java.lang.Object[]) (Constructor.java:-2)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at java.lang.Object java.lang.reflect.Constructor.newInstance(java.lang.Object[]) (Constructor.java:430)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at android.view.View android.view.LayoutInflater.createView(java.lang.String, java.lang.String, android.util.AttributeSet) (LayoutInflater.java:645)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at android.view.View com.android.internal.policy.PhoneLayoutInflater.onCreateView(java.lang.String, android.util.AttributeSet) (PhoneLayoutInflater.java:58)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at android.view.View android.view.LayoutInflater.onCreateView(android.view.View, java.lang.String, android.util.AttributeSet) (LayoutInflater.java:717)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:785)
01-13 10:57:32.913 8790-8790/com.nextcloud.client I/art:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet) (LayoutInflater.java:727)
01-13 10:57:32.914 8790-8790/com.nextcloud.client I/art:     at void android.view.LayoutInflater.rInflate(org.xmlpull.v1.XmlPullParser, android.view.View, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:858)
01-13 10:57:32.914 8790-8790/com.nextcloud.client I/art:     at void android.view.LayoutInflater.rInflateChildren(org.xmlpull.v1.XmlPullParser, android.view.View, android.util.AttributeSet, boolean) (LayoutInflater.java:821)
01-13 10:57:32.914 8790-8790/com.nextcloud.client I/art:     at android.view.View android.view.LayoutInflater.inflate(org.xmlpull.v1.XmlPullParser, android.view.ViewGroup, boolean) (LayoutInflater.java:518)
01-13 10:57:32.914 8790-8790/com.nextcloud.client I/art:     at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup, boolean) (LayoutInflater.java:426)
01-13 10:57:32.914 8790-8790/com.nextcloud.client I/art:     at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup) (LayoutInflater.java:377)
01-13 10:57:32.914 8790-8790/com.nextcloud.client I/art:     at void android.support.v7.app.AppCompatDelegateImplV9.setContentView(int) (AppCompatDelegateImplV9.java:292)
01-13 10:57:32.914 8790-8790/com.nextcloud.client I/art:     at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
01-13 10:57:32.914 8790-8790/com.nextcloud.client I/art:     at void com.owncloud.android.authentication.AuthenticatorActivity.onGetServerInfoFinish(com.owncloud.android.lib.common.operations.RemoteOperationResult) (AuthenticatorActivity.java:1414)
01-13 10:57:32.914 8790-8790/com.nextcloud.client I/art:     at void com.owncloud.android.authentication.AuthenticatorActivity.onRemoteOperationFinish(com.owncloud.android.lib.common.operations.RemoteOperation, com.owncloud.android.lib.common.operations.RemoteOperationResult) (AuthenticatorActivity.java:1313)
01-13 10:57:32.914 8790-8790/com.nextcloud.client I/art:     at void com.owncloud.android.services.OperationsService$1.run() (OperationsService.java:726)
01-13 10:57:32.914 8790-8790/com.nextcloud.client I/art:     at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751)
01-13 10:57:32.914 8790-8790/com.nextcloud.client I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)
01-13 10:57:32.914 8790-8790/com.nextcloud.client I/art:     at void android.os.Looper.loop() (Looper.java:154)
01-13 10:57:32.914 8790-8790/com.nextcloud.client I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6186)
01-13 10:57:32.914 8790-8790/com.nextcloud.client I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
01-13 10:57:32.914 8790-8790/com.nextcloud.client I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:889)
01-13 10:57:32.914 8790-8790/com.nextcloud.client I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:779)
01-13 10:57:32.983 8790-8872/com.nextcloud.client W/cr_media: Requires BLUETOOTH permission
01-13 10:57:33.032 8790-8890/com.nextcloud.client E/libEGL: validate_display:99 error 3008 (EGL_BAD_DISPLAY)
01-13 10:57:33.042 8790-8890/com.nextcloud.client W/VideoCapabilities: Unrecognized profile/level 1/32 for video/mp4v-es
01-13 10:57:33.042 8790-8890/com.nextcloud.client W/VideoCapabilities: Unrecognized profile/level 32768/2 for video/mp4v-es
01-13 10:57:33.042 8790-8890/com.nextcloud.client W/VideoCapabilities: Unrecognized profile/level 32768/64 for video/mp4v-es
01-13 10:57:33.064 8790-8890/com.nextcloud.client W/VideoCapabilities: Unrecognized profile/level 1/32 for video/mp4v-es
01-13 10:57:33.064 8790-8890/com.nextcloud.client W/VideoCapabilities: Unrecognized profile/level 32768/2 for video/mp4v-es
01-13 10:57:33.065 8790-8890/com.nextcloud.client W/VideoCapabilities: Unrecognized profile/level 32768/64 for video/mp4v-es
01-13 10:57:33.084 8790-8890/com.nextcloud.client I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
01-13 10:57:33.101 8790-8890/com.nextcloud.client W/AudioCapabilities: Unsupported mime audio/ac3
01-13 10:57:33.102 8790-8890/com.nextcloud.client W/AudioCapabilities: Unsupported mime audio/alac
01-13 10:57:33.103 8790-8890/com.nextcloud.client W/AudioCapabilities: Unsupported mime audio/x-ape
01-13 10:57:33.105 8790-8890/com.nextcloud.client W/AudioCapabilities: Unsupported mime audio/ffmpeg
01-13 10:57:33.105 8790-8890/com.nextcloud.client W/AudioCapabilities: Unsupported mime audio/dts
01-13 10:57:33.107 8790-8890/com.nextcloud.client W/AudioCapabilities: Unsupported mime audio/mpeg-L2
01-13 10:57:33.108 8790-8890/com.nextcloud.client W/AudioCapabilities: Unsupported mime audio/vnd.rn-realaudio
01-13 10:57:33.109 8790-8890/com.nextcloud.client W/AudioCapabilities: Unsupported mime audio/x-ms-wma
01-13 10:57:33.110 8790-8890/com.nextcloud.client W/VideoCapabilities: Unsupported mime video/divx
01-13 10:57:33.113 8790-8890/com.nextcloud.client W/VideoCapabilities: Unsupported mime video/x-flv
01-13 10:57:33.119 8790-8890/com.nextcloud.client W/VideoCapabilities: Unsupported mime video/vnd.rn-realvideo
01-13 10:57:33.121 8790-8890/com.nextcloud.client W/VideoCapabilities: Unsupported mime video/vc1
01-13 10:57:33.122 8790-8890/com.nextcloud.client W/VideoCapabilities: Unsupported mime video/ffmpeg
01-13 10:57:33.124 8790-8890/com.nextcloud.client W/VideoCapabilities: Unsupported mime video/x-ms-wmv
01-13 10:57:34.029 8790-8790/com.nextcloud.client I/chromium: [INFO:CONSOLE(7)] "JQMIGRATE: Migrate is installed, version 1.4.0", source: https://nextcloud.example.net/core/vendor/core.js?v=1a0cd508968dd9ddc503a04bef24d197-0 (7)
01-13 10:58:14.997 8790-8899/com.nextcloud.client W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
01-13 10:58:15.028 8790-8790/com.nextcloud.client D/OperationsService: Starting command with id 2
01-13 10:58:15.029 8790-8822/com.nextcloud.client D/SimpleFactoryManager: getClientFor(OwnCloudAccount ... : 
01-13 10:58:15.030 8790-8822/com.nextcloud.client D/OwnCloudClient #1: Creating OwnCloudClient
01-13 10:58:15.030 8790-8822/com.nextcloud.client V/SimpleFactoryManager:     new client {@nextcloud.example.net, 175476711}
01-13 10:58:15.033 8790-8790/com.nextcloud.client W/chromium: [WARNING:render_frame_host_impl.cc(2646)] OnDidStopLoading was called twice.
01-13 10:58:15.034 8790-8822/com.nextcloud.client D/OwnCloudClient #1: REQUEST GET /status.php
01-13 10:58:15.039 8790-8822/com.nextcloud.client D/AdvancedSslSocketFactory: Creating SSL Socket with remote nextcloud.example.net:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@7ca8c4f
01-13 10:58:15.039 8790-8822/com.nextcloud.client D/AdvancedSslSocketFactory:  ... with connection timeout 50000 and socket timeout 50000
01-13 10:58:15.044 8790-8822/com.nextcloud.client I/ServerNameIndicator: SNI done, hostname: nextcloud.example.net
01-13 10:58:15.138 8790-8822/com.nextcloud.client W/HttpMethodBase: Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
01-13 10:58:15.142 8790-8822/com.nextcloud.client I/GetRemoteStatusOperation: Connection check at https://nextcloud.example.net: Operation finished with HTTP status code -1 (success)
01-13 10:58:15.143 8790-8822/com.nextcloud.client D/GetServerInfoOperation: Trying empty authorization to detect authentication method
01-13 10:58:15.145 8790-8822/com.nextcloud.client D/OwnCloudClient #1: REQUEST HEAD /remote.php/webdav/
01-13 10:58:15.209 8790-8822/com.nextcloud.client I/AuthChallengeProcessor: basic authentication scheme selected
01-13 10:58:15.211 8790-8822/com.nextcloud.client I/HttpMethodDirector: No credentials available for BASIC 'Nextcloud'@nextcloud.example.net:443
01-13 10:58:15.212 8790-8822/com.nextcloud.client D/ExistenceCheckRemoteOperation: Existence check for https://nextcloud.example.net/remote.php/webdav/ targeting for  existence finished with HTTP status 401(FAIL)
01-13 10:58:15.212 8790-8822/com.nextcloud.client D/DetectAuthenticationMethodOperation: Authentication method found: BASIC_HTTP_AUTH
01-13 10:58:15.212 8790-8822/com.nextcloud.client D/OperationsService: Called 1 listeners
01-13 10:58:15.213 8790-8822/com.nextcloud.client D/OperationsService: Stopping after command with id 2
01-13 10:58:15.217 8790-8917/com.nextcloud.client D/OwnCloudClient #2: Creating OwnCloudClient
01-13 10:58:15.219 8790-8917/com.nextcloud.client D/OwnCloudClient #2: REQUEST HEAD /remote.php/webdav/
01-13 10:58:15.302 8790-8820/com.nextcloud.client D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1344x518]-format:1
01-13 10:58:15.791 8790-8917/com.nextcloud.client D/ExistenceCheckRemoteOperation: Existence check for https://nextcloud.example.net/remote.php/webdav/ targeting for  existence finished with HTTP status 200
01-13 10:58:15.792 8790-8917/com.nextcloud.client D/OwnCloudClient #2: REQUEST GET /ocs/v1.php/cloud/user
01-13 10:58:16.304 8790-8917/com.nextcloud.client D/GetRemoteUserInfoOperation: Successful response: {"ocs":{"meta":{"status":"ok","statuscode":100,"message":"OK","totalitems":"","itemsperpage":""},"data":{"id":"cf","quota":{"free":124507676672,"used":75868211,"total":124583544883,"relative":0.06,"quota":-3},"email":"***@example.net","phone":"","address":"","website":"","twitter":"","groups":["Main User"],"language":"de_DE","display-name":"cf"}}}
01-13 10:58:16.330 8790-8790/com.nextcloud.client D/AuthenticatorActivity: Successful access - time to save the account
01-13 10:58:16.383 8790-8919/com.nextcloud.client D/ExternalLinks: links disabled
01-13 10:58:16.388 8790-8790/com.nextcloud.client D/AuthenticatorActivity: onPause() ending
01-13 10:58:16.425 8790-8790/com.nextcloud.client D/FileDisplayActivity: onDestroy() ending
01-13 10:58:16.452 8790-8790/com.nextcloud.client V/FileDownloader: Destroying service
01-13 10:58:16.453 8790-8790/com.nextcloud.client V/FileUploader: Destroying service
01-13 10:58:16.700 8790-8790/com.nextcloud.client D/AuthenticatorActivity: onStop() ending
01-13 10:58:16.705 8790-8790/com.nextcloud.client D/AuthenticatorActivity: onDestroy() ending
01-13 10:58:16.729 8790-8790/com.nextcloud.client E/ActivityThread: Activity com.owncloud.android.authentication.AuthenticatorActivity has leaked ServiceConnection com.owncloud.android.authentication.AuthenticatorActivity$OperationsServiceConnection@85540bb that was originally bound here
                                                                    android.app.ServiceConnectionLeaked: Activity com.owncloud.android.authentication.AuthenticatorActivity has leaked ServiceConnection com.owncloud.android.authentication.AuthenticatorActivity$OperationsServiceConnection@85540bb that was originally bound here
                                                                        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1336)
                                                                        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1231)
                                                                        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1450)
                                                                        at android.app.ContextImpl.bindService(ContextImpl.java:1422)
                                                                        at android.content.ContextWrapper.bindService(ContextWrapper.java:636)
                                                                        at com.owncloud.android.authentication.AuthenticatorActivity.onResume(AuthenticatorActivity.java:958)
                                                                        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
                                                                        at android.app.Activity.performResume(Activity.java:6788)
                                                                        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3431)
                                                                        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3494)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2757)
                                                                        at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
01-13 10:58:16.737 8790-8790/com.nextcloud.client V/OperationsService: Destroying service
01-13 11:07:40.668 8790-9203/com.nextcloud.client D/PlatformJobService: Run job, request{id=1, tag=FilesSyncJob}, waited 00:10:34, interval 00:15:00, flex 00:05:00
01-13 11:07:40.670 8790-9203/com.nextcloud.client I/JobExecutor: Executing request{id=1, tag=FilesSyncJob}, context PlatformJobService
01-13 11:07:40.716 8790-9204/com.nextcloud.client I/JobExecutor: Finished job{id=1, finished=true, result=SUCCESS, canceled=false, periodic=true, class=FilesSyncJob, tag=FilesSyncJob}
01-13 11:07:40.742 8790-9203/com.nextcloud.client D/PlatformJobService: Finished job, request{id=1, tag=FilesSyncJob} SUCCESS
```

### Note

Problem does not occur on Nexus 6 (shamu), also LineageOS-Nightly.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky do you have the time to look into this one?

**Comment by tobiasKaminsky** [comment]
This is strange.

> D/AuthenticatorActivity: Successful access - time to save the account

says that new weblog flow succeed. I also do not see an error that the account could not be stored.
The normal behaviour is that the AuthActivity closes itself after account creation and then FDA should start.

**Comment by bastei** [comment]
Same problem here. The logs look similar, especially this error:
`E/ActivityThread: Activity com.owncloud.android.authentication.AuthenticatorActivity has leaked ServiceConnection`

Maybe #1970 or even #1950 are related problems.?

There is a problem with the [Nextcloud News Android](https://github.com/nextcloud/news-android) app with syncing, too (nextcloud/news-android#600). It seems that the problems appeared with an Android update to 7.x. That is at least the case for me with both apps. Maybe there is some kind of incompatibility with the latest Android / LineageOS versions here, too.

**Comment by tobiasKaminsky** [comment]
There will be soon a 3.0.0 RC2 where we fixed some stuff related to adding Account. I am unsure if this helps, but it is worth a try.

**Comment by bastei** [comment]
Unfortunately I get still the same error with nextcloud-dev-20180121.

**Comment by AndyScherzinger** [comment]
> same error with nextcloud-dev-20180121.

Then it isn't fixed on the actual master and won't be fixed with 3.0.0 RC2 :(

**Comment by tobiasKaminsky** [comment]
> won't be fixed with 3.0.0 RC2

@AndyScherzinger I fixed at least some NPE during account creation, so maybe it helps.
Or do you have more stack traces / info that my fixes are not working?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I don't need stacktraces if yesterdays nightly didn't fix it I'd say ;P since then it is basically tested with master.

**Comment by tobiasKaminsky** [comment]
Ah right. I overread this. Sorry :-)
Well, then I am a bit out of clue as the stacktrace does not show the real error.

I'll have a look at the two linked issues.

**Comment by bastei** [comment]
Turns out that I suffered from #1531 (removed nextcloud account and orphaned account-entry in accounts_ce.db). It works again after removing the entry in the db.

**Comment by tobiasKaminsky** [comment]
@bastei do you have an idea, how you ran into this issue?
We would need such steps to avoid this problem in the future...

**Comment by nightbluepn** [comment]
@tobiasKaminsky I ran into the same issue.
As in #1531 i am using encrypted adopted external sd, and fixed it by modifying the accounts_ce.db
I believe this might have been triggered because i revoked the app's session from the web interface.
So maybe it can be reproduced that way.

**Comment by tobiasKaminsky** [comment]
@nightbluepn thanks for the tip.
I tried it and revoked app session, but then I only got the login screen one time, which is correct. After log in there, everything still works.
So unfortunately this is not a way to trigger it.

**Comment by nightbluepn** [comment]
@tobiasKaminsky 
I didn't update my comment, sorry - in the meantime i found out that a restart is what is triggering the account to be 'invalidated'.

The Signal app has the same problem: 
https://github.com/signalapp/Signal-Android/issues/7681
https://jira.lineageos.org/browse/BUGBASH-1611

So after i reboot my phone, nextcloud will be logged out and Signal doesn't show any contacts - until i purge both from accounts_ce.db, then i can login to nextcloud and everything is be back to normal.
My DavDroid which uses the same server/account is unaffected though, the Nextcloud Notes app too.

**Comment by nightbluepn** [comment]
I have read about the internal storage solution but apparently i only tried it after the database was already broken.
So first making sure that the database does not contain an orphaned account and then moving the app to internal solved the problem for me - reinstalling or anything of the sort will not help since accounts_ce.db will still contain the orphaned account.
Thanks

**Comment by tobiasKaminsky** [comment]
Glad to hear, although it is still not the best fix.
