### ISSUE TITLE
Push: show real text instead of generic "new notification"

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/android#1964]
User want to see the real content of notification.
As I understand this was due to a server bug, but can now be fixed for next version.

**Comment by mario** [comment]
Haven't I fixed this already? xD

**Comment by tobiasKaminsky** [comment]
It shows the push subject, but not the content.
Would it also be possible to show the complete content (as many text as fits into the notification?)

**Comment by tobiasKaminsky** [comment]
Working.

**Comment by skjnldsv** [comment]
Is this released?
![Screenshot_20201102-083829](https://user-images.githubusercontent.com/14975046/97848202-06b2a880-1cf1-11eb-83ca-e493ca3bfd72.png)

**Comment by tobiasKaminsky** [comment]
Yes, since ages.
If you get this, it means that for some reason the content cannot be decrypted.
Can you check if there are wrong app tokens in web->settings?

**Comment by tobiasKaminsky** [comment]
After debugging with @skjnldsv it turns out that those strange notifications only happens when the app is not in foreground.

**Comment by MartinConsultingServicesInc** [comment]
I'm having this problem, too.  Running client version 3.14.0 against server 19.0.5.  I think it started after the upgrade from 19.0.4.

**Comment by scroom** [comment]
> I'm having this problem, too. Running client version 3.14.0 against server 19.0.5. I think it started after the upgrade from 19.0.4.

Same here.

**Comment by tobiasKaminsky** [comment]
As far as I remember new_notification is the default value of push proxy, if no message is set.
@nickvergessen do you have an idea why such messages might be sent?

**Comment by MartinConsultingServicesInc** [comment]
I thought it was occurring when NC apps had updates available, but I got 
one of these this morning and I don't have any apps needing updates.

I'm not familiar with the language NC is written in, but it may have 
something similar to the Perl "caller" routine, which allows a routine 
to determine who called it. If you have such a thing, you might consider 
changing the default value to include the caller name or other 
identifier. That would make future occurrences easier to debug.

If I learn anything about the source, I'll update the ticket.

             -Brian M

**Comment by tobiasKaminsky** [comment]
Have you removed account in question on Android or reset app token or something like that?

**Comment by MartinConsultingServicesInc** [comment]
I had not made any change there.  I know that the Nextcloud client still 
allowed me to access my files, make changes, etc. That suggests that the 
account credentials were operating normally, at least in some regards.

Nevertheless, I have now deleted the Android client account from the 
client, and then and re-added it using an app token.  I'll advise you as 
to whether the problem goes away or continues.

**Comment by MartinConsultingServicesInc** [comment]
The problem still occurs.  The NC web interface shows a proper notification (again all PhoneTrack in my case telling me I've reached my point quota, but I think that's just because I don't get many other notifications), but "NEW_NOTIFICATION NEW_NOTIFICATION" in the Android notification bar.

**Comment by nickvergessen** [comment]
> do you have an idea why such messages might be sent?

Just to answer this publicly here as well. The subject is the default subject we set. The encrypted subject should be decrypted and displayed instead by the client. However in this case it seems it either fails to decrypt or to load more information from the server.

**Comment by tobiasKaminsky** [comment]
> However in this case it seems it either fails to decrypt or to load more information from the server.

At least on Android side we only show a notification if we can decrypt it and if we can get real info from server:
https://github.com/nextcloud/android/blob/f0f467d2a10ffe0dc36663a2e81beb9ac96d578f/src/main/java/com/nextcloud/client/jobs/NotificationWork.kt#L245-L250

I have no real idea how this could happen…

**Comment by tobiasKaminsky** [comment]
> The subject is the default subject we set.

This is also encrypted, or?

**Comment by nickvergessen** [comment]
This is what we do:
```go
	p := fcm.Notification{
		Title:       "NEW_NOTIFICATION",
		TitleLocKey: "NEW_NOTIFICATION_TITLE",
		Body:        "NEW_NOTIFICATION",      // Required for iOS
		BodyLocKey:  "NEW_NOTIFICATION_BODY", // Required for iOS
		Sound:       "default",
	}
	d := map[string]string{
		"subject":   n.Subject,
		"signature": n.Signature,
	}

	return fcm.Message{
		Notification:     p,
		Data:             d,
		To:               n.pushToken,
		ContentAvailable: true,
		MutableContent:   true,
		Priority:         priority,
	}
```

So `data` contains the original encrypted subject, and the `title` + `body` are unencrypted, untranslated, generic placeholders

**Comment by tobiasKaminsky** [comment]
This is what I suspect:
if for $strange reason, push proxy sends a notification to Android device with an old token, the Android device tries to match the token, but fails, then Android (!) still shows the notification, not our app.

I discussed this with @skjnldsv who even had removed any c.nc.c account, but still received a NEW_NOTIFICATION message, but in logcat none NotificationWork related info was shown.

**Comment by tobiasKaminsky** [comment]
@MartinConsultingServicesInc can you test this APK:
https://cloud.nextcloud.com/s/ssyPYM346rz7QSc

Can you first uninstall the app, then test it?

**Comment by tobiasKaminsky** [comment]
I removed my last message, as it was a wrong assumption and thus the test would not have helped.

**Comment by tobiasKaminsky** [comment]
So we changed something in the way push messages are transferred to google cloud messaging.
@MartinConsultingServicesInc can you try it again? Just create one push.

**Comment by MartinConsultingServicesInc** [comment]
Notifications happen spontaneously. I don't know how to manually trigger one. I should have a spontaneous one later today, but if you want to tell me of a trick to force one, I'm happy to do it. Otherwise, I'll let you know how the next one goes.

**Comment by MartinConsultingServicesInc** [comment]
That fixed it.  Since late yesterday my notifications are coming in with the correct text.

I don't see that my Android Nextcloud client software has been updated in the last several days, and I haven't updated my server software.  How am I seeing this change, then?

**Comment by nickvergessen** [comment]
The Android app is registering with incorrect data/user agent on some android versions. The push proxy database had a lot of entries with type "unknown". After checking the patterns of the push tokens it seemed like those should all be from the android app and we manually reset the typo for them. It will be fixed in the next android app update. Until then we will observe and manually fix the type from time to time for newly registered devices.

**Comment by MartinConsultingServicesInc** [comment]
Excellent.  Thanks to you both for the prompt response.

**Comment by apg1980** [comment]
The NEW_NOTIFICATONS are still sent on 3.14.3

**Comment by K4ds3** [comment]
Can confirm, that this issue still persists.

App version: 3.14.3
Nextcloud Version: 20.0.5
Phone: Oneplus 8T
Android Version: Oxygen OS 11.0.6.8.KB05AA

**Comment by AndyScherzinger** [comment]
This is fixed with the upcoming 3.15.0

**Comment by XueSheng-GIT** [comment]
I've updated to 3.15 and still get NEW_NOTIFICATION instead of a proper notification text!

**Comment by leptians** [comment]
I'm also getting the same message and I'm behind NGINX

Android App: 3.15
Nextcloud: 20.0.7
Phone: Pixel 2 XL

**Comment by palight** [comment]
Hello,

 I just tested after reseting my app (data and cache) and revoking the autorisations for my device. When I register the device again, problem is still there.

It  was working fine before my update to android 11 (and the reset of my device

I'm on 20.0.8 for server and 3.15 for android app

**Comment by major-mayer** [comment]
This issue shouldn't be closed!
I am on Nextcloud 3.16.1 / Android 11 and use Nextcloud 21 on the server side and still get this notification very often in the last weeks.
Here is a screenshot:
![Screenshot_20210614-114030](https://user-images.githubusercontent.com/17907799/121872832-073f0300-cd06-11eb-8006-f29d3b15a758.png)

**Comment by scrampker** [comment]
I have this as well, and I wonder if there's any connection to using MicroG on a de-googled device?

**Comment by roboticsalign** [comment]
> This issue shouldn't be closed!
> I am on Nextcloud 3.16.1 / Android 11 and use Nextcloud 21 on the server side and still get this notification very often in the last weeks.
> Here is a screenshot:
> ![Screenshot_20210614-114030](https://user-images.githubusercontent.com/17907799/121872832-073f0300-cd06-11eb-8006-f29d3b15a758.png)
> 

Same problem here with Samsung S10 and German UI.

**Comment by Pilzinsel64** [comment]
For me the same. It happens since a few days without an update of the app. So, maybe a temporary thing?
Nextcloud 22.0.0 with latest Client Push app configured and Android app Version 3.16.1.

If I have time and a more empty brain the next days I would try re-installing the app, maybe that helps (would notify you when I did). Because simply clear the app data isn't possible. The Nextcloud app provides its own data removeal function in the Android App Settings.

**Comment by major-mayer** [comment]
That's actually a good hint, I also configured the client push app roughly the same time when this issue occurred.
Maybe it has something to do with the push notifications sent from the client push service (the Rust based one/ "Files High Performance Backend"). 
IIRC this new push notifications do not contain any information but just say "Hey something changed here", at least that's what you see when you inspect the WebSockets connection in the browser.

**Comment by Pilzinsel64** [comment]
Maybe as additional information about my android device:
Samsung Galaxy S10
_-> fingerprinted and simulated as Google Pixel 4 with MagiskHideProps to get banking push tan app and Galaxy Wearable app working; and working SafetyNet check_
LineageOS 18.1 (Android 11)
_-> with Google Play Services & Store installed_

If you now think that my constallation of my installed system would have to do something with the problem ... I have this constallation about two years now. The Nextcloud app wokred great. The problem appeared one week before now.

**Comment by tchernobog** [comment]
For me, uninstalling the app and installing it again was a workable workaround.

**Comment by chadblose** [comment]
I'm also receiving these notifications on my Google Pixel 5. Uninstalled the app and reinstalled. Just got a new "NEW_NOTIFICATION" message.

**Comment by tehCrush** [comment]
> 
> 
> I'm also receiving these notifications on my Google Pixel 5. Uninstalled the app and reinstalled. Just got a new "NEW_NOTIFICATION" message. I checked my recent notifications inside the app and it was trying to tell me there was an update available for Contacts to version 4.0.1

can confirm, pixel 5 as well. Uninstalling Nextcloud, restarting the phone and reinstalling it fixed it for me.
First occurence was the switch from my old Galaxy S7 to my current Pixel 5. I would guess it had to do something with the data transfer from old to new.

**Comment by kagbasi-aerwireless** [comment]
Adding my two cents to this topic as well.  I, too, am experiencing this problem on my Samsung Galaxy S10.  Nextcloud App version 3.17.0.

**Here's a screenshot:**
![Screenshot_20211003-110612_One UI Home](https://user-images.githubusercontent.com/86181386/135760646-f1daa9e5-0ea7-4369-8841-0518895b4f78.jpg)

**Comment by obbardc** [comment]
happening again on pixel 6 pro, seems to be daily or so for me at about 22:30

**Comment by jakobroehrl** [comment]
Same problem since 3.18. see: https://github.com/nextcloud/android/issues/9352

**Comment by jakobroehrl** [comment]
> Same problem since 3.18. see: #9352

solved for me with reinstalling the app

**Comment by EnderArchery** [comment]
I have reinstalled it, but I just hot another one of them.
Nextcloud-App on Android 11 (OnePlus 8 Pro)
Nextcloud version 23.0.2.
Nothing found in the servers log.

In this specific case it was a notification about an update of Breeze Dark.

**Comment by Pkshields** [comment]
This issue has just occurred for me as well on a days old installation of Nextcloud and the Android app.

Nextcloud Android app version 3.19.1, installed through the Play Store.
Pixel 5, running Android 12
Nextcloud version 23.0.3

The notification in my case was for updating Nextcloud to 23.0.4.

**Comment by ariselseng** [comment]
Happens to me as well. Reinstalling the app does not help.
I am using the client push on the server like some other reports here. Maybe it is related?

**Comment by Webbeh** [comment]
Same issue. Appeared a few weeks ago, couldn't tell when exactly.

Started appearing with server v23.x.x and still occurs now with server 24.0.1.

Have not installed the "client push" service.

**Comment by fastballiron** [comment]
Still an issue in Nextcloud 24.0.2

**Comment by Webbeh** [comment]
![image](https://user-images.githubusercontent.com/1530837/176898723-aa029a13-e415-4188-8d99-fb233a9d4b60.png)

First notification (bottom) before opening the app, second after opening the app.
Note that I was on the "Uploads" screen, not even on the "Notifications" screen (of the Nextcloud app) when the second appeared.

**Comment by hamidout** [comment]
Still an issue on Nextcloud Server v24.0.3.2, Nextcloud Android App v3.20.3 and Android 12.

**Comment by jficz** [comment]
I'm getting these as well with NC server 24.0.3 and app version 3.20.3. Clearing app data helps for a few new notifications but after some (short) time the notifications beak again.
Android 10, microg

**Comment by mercury1337** [comment]
Nextcloud 24.0.4 / Android 12 on OnePlus 8 Pro => still does not work only shows "NEW_NOTIFICATION" - tried app reinstall but did not help.

**Comment by Siggi0904** [comment]
Same here with Google Pixel 6 Pro, Android 13, Nextcloud 24.0.5 and latest Android app from google Store.

**Comment by LaGGi97** [comment]
I've had this Problem for some time now too. I run an nextcloud instance with about 30 Users and i was the only one with this problem. The only difference i found was 2FA. I was the only user with 2FA enabled. After disabling it, all notifications on my phone are readable.

**Possible bandaid fix: disable all 2FA methods**

Server: Nextcloud 24.0.5
Client: Android App 3.21.2 (Google Play Beta) on Google Pixel 6 Pro

**Comment by mercury1337** [comment]
I don't have 2FA enabled and I am seeing the problem.

**Comment by Zocker1999NET** [comment]
@mercury1337 Are you using OAuth / SAML / LDAP / … ? Maybe it has something to do with using "non-default" login methods ...

**Comment by palight** [comment]
As q-wertz, i have the issue and I'm on LDAP. Issue is inconsisitent between users os the same ldap backend.

**Comment by mercury1337** [comment]
> @mercury1337 Are you using OAuth / SAML / LDAP / … ? Maybe it has something to do with using "non-default" login methods ...

Nope - ordinary login via username & pw

**Comment by EnderArchery** [comment]
The issue has stopped appearing for me.
I've upgraded NextCloud, added missing indexes, used the repair command and several other things over a period of multiple months.
Unfortunately I don't know since when it's been fixed.

Did anybody notice a pattern for which types of notification the error occurs?

**Comment by lfom** [comment]
Maybe it is related to App Passcode? I have seen other apps where the notification content is not shown if the app is locked.

**Comment by EnderArchery** [comment]
I have notification contents on the lockscreen blocked and don't have a passcode set for the app. Both before and after the fix.

Oooo, but I am running on LineageOS now. I was running on OnePlus' OxygenOS before. (Could be unrelated, or fixed by the reinstall after another thing has changed)

**Comment by mercury1337** [comment]
I checked: No notifications blocked and using Stock OxygenOS (Oneplus version of Android 12).

**Comment by jficz** [comment]
I did change my users backend from IMAP to internal DB and the bad notifications are gone _but_ I can't say for sure if it was because of the change or not because I simply don't remember :/ I do use 2FA and I did use it before, it was not affected by the change

**Comment by CaesarRulezzz** [comment]
The issu is still there on the latest stable build from Play Market

**Comment by felix-berlin** [comment]
I have had this problem for ages. Currently I am using: Pixel 4a (Android 13), Nextcloud 25.0.1, current Nextcloud app. 2FA is active.

**Comment by mercury1337** [comment]
Problem is still there - also on android 13

**Comment by rcmcronny** [comment]
I have this also, removed nextcloud app, and reinstalled it, also with all new data and issue persists.

**Comment by alireza-salehi** [comment]
issue persist with 3.23.0

**Comment by kakuy** [comment]
I'm having this problem too. It's actually not that better than having no notifications at all.

Until recently I was using https://gitlab.com/Nextcloud-Push and it worked almost flawlessly. It started to miss notifications after I updated to Nextcloud 25. It was specially great because it didn't depend from google.

Would it be possible to officially support this push notification proxy and app? So it could receive updates when needed? I'm sure many people would be thankful, at least those with google concerns, googleless devices or, those for whom google cloud messaging does not work as it should.

**Comment by R7JANV1** [comment]
Any Progress?

**Comment by EnderArchery** [comment]
Unfortunately not. It also has returned for me.
I've installed and removed a lot of apps in-between and even upgraded to NextCloud 25, so I don't know what triggered it.
So far, the only notifications affect were about available updates for apps.

**Comment by R7JANV1** [comment]
unfortunately all notifications are affected for me.

**Comment by mercury1337** [comment]
Got a new phone => still the same behavior
For other user on same Nextcloud installation it works properly

**Comment by Webbeh** [comment]
Same issue happened again.

I've got another app on the phone that allows us to renew the notifications service that I had to use after all notifications stopped working. Is this something we could have as a workaround for the Nextxlpid app ?

![Screenshot_20230302-205725.jpg](https://user-images.githubusercontent.com/1530837/222538584-30344243-f9cf-4f21-b0b2-f79e15f23ee4.jpg)

**Comment by starypatyk** [comment]
Hi @tobiasKaminsky,

I have been affected by this after upgrading to 3.25.0 RC1.

First I noticed that my app configuration was lost - supposedly due to the issue fixed by https://github.com/nextcloud/android/commit/8d0faaeca58e3ee16a49c2caa619f00b1fd594f0. So I had to re-register the app with the server.

A few days later when I got notifications about new version of the server and some apps, these were displayed as NEW_NOTIFICATION instead. Similar notifications were working fine for a long time before.

I suspect that this is related to inconsistency between Firebase device configuration (that might have survived on my phone) and the configuration on the server (supposedly generated fresh when re-registering).

I will try to diagnose it a bit more, to see if I can get some logs.

**Comment by XueSheng-GIT** [comment]
> I have been affected by this after upgrading to 3.25.0 RC1.

Same for me. I was able to get normal notifications again by removing the nextclozd app, deleting the existing device registration within the nextcloud security settings and finally install the last stable nextcloud app 3.24.2.
I Did not try with 3.25.0 RC1 again.

**Comment by lukynmatuska** [comment]
> Hi @tobiasKaminsky,
> 
> I have been affected by this after upgrading to 3.25.0 RC1.
> 
> First I noticed that my app configuration was lost - supposedly due to the issue fixed by [8d0faae](https://github.com/nextcloud/android/commit/8d0faaeca58e3ee16a49c2caa619f00b1fd594f0). So I had to re-register the app with the server.
> 
> A few days later when I got notifications about new version of the server and some apps, these were displayed as NEW_NOTIFICATION instead. Similar notifications were working fine for a long time before.
> 
> I suspect that this is related to inconsistency between Firebase device configuration (that might have survived on my phone) and the configuration on the server (supposedly generated fresh when re-registering).
> 
> I will try to diagnose it a bit more, to see if I can get some logs.
> 
> **Update** - here are the logs I got when sending a test notification via `occ notification:test-push`:
> 
> ```
> 05-27 23:28:07.225 30211 21690 W FirebaseMessaging: Unable to log event: analytics library is missing
> 05-27 23:28:07.227 30211 21690 W FirebaseMessaging: Missing Default Notification Channel metadata in AndroidManifest. Default value will be used.
> ```

This works fine.

**Comment by mercury1337** [comment]
> > I have been affected by this after upgrading to 3.25.0 RC1.
> 
> Same for me. I was able to get normal notifications again by removing the nextcloud app, deleting the existing device registration within the nextcloud security settings and finally install the last stable nextcloud app 3.24.2. I did not try with 3.25.0 RC1 again.

Tried this => did NOT work for me. Still same issues (on Galaxy S23 with Nextcloud 3.24.2)

**Comment by jtorqui74** [comment]
Ok. I have had this same problem some time ago with talk notifications, and for testing I have done the same procedure with the Nextcloud app. It has worked. Notifications reappear successfully. The problem lies in the Nextcloud database, specifically in the table _notifications_pushhash which it is structured as follows: 
Id 
uid 
Token 
deviceidentifier 
devicepublickey 
devicepublickeyhash 
Pushtokenhash 
ProxyServer 
apptype 
The fact is that what we need for the notifications to work again we must delete the entries that have the account to which the notifications do not work, for this we connect via console to the mysql server.
mysql -u root 
We select the nextcloud database. 
Use NextCloud; 
Let's first see if there are entries for a certain user.
SELECT * FROM oc_notifications_pushhash WHERE uid=' '; 
In case you return a record we will delete it. 
DELETE FROM oc_notifications_pushhash WHERE uid=' '; 
Delete accounts from the android app and log back in. For me this has worked.
Cheers.

**Comment by mrclschstr** [comment]
> Ok. I have had this same problem some time ago with talk notifications, and for testing I have done the same procedure with the Nextcloud app. It has worked. Notifications reappear successfully. The problem lies in the Nextcloud database, specifically in the table _notifications_pushhash which it is structured as follows: Id uid Token deviceidentifier devicepublickey devicepublickeyhash Pushtokenhash ProxyServer apptype The fact is that what we need for the notifications to work again we must delete the entries that have the account to which the notifications do not work, for this we connect via console to the mysql server. mysql -u root We select the nextcloud database. Use NextCloud; Let's first see if there are entries for a certain user. Replace mike with your user. SELECT * FROM oc_notifications_pushhash WHERE uid='mike'; In case you return a record we will delete it. DELETE FROM oc_notifications_pushhash WHERE uid='mike'; Delete accounts from the android app and log back in. For me this has worked.
> 
> Try now notifications with sudo -u www-data php occ notification:test-push
> 
> Cheers.

This worked for me as well, thank you very much!

**Comment by R7JANV1** [comment]
Unfortunately, this is not a nice solution and does not prevent the problem.  Please, dear Nextcloud team, take care of this bug.

**Comment by jficz** [comment]
> Delete accounts from the android app and log back in. For me this has worked.

This is where things become complicated, because of #11090

**Comment by R7JANV1** [comment]
I don't know if the following is known to the Nextcloud team, therefore a small description:

Steps to reproduce;
1. get a message or create one using administrator tools
2. see on your Android app that the generic "new notification" appears as notification
3. delete the notifications in the browser
4. see how for each deleted message your phone gets spammed with more generic "new notification" notifications

No matter if the message is already deleted in the app or not each time it will generate enormous amount of spam. I don't know how this is handled now with the messages (Firebase, or own infrastructure) But the way I see it is an unnecessary load on the system.

**Comment by koying** [comment]
@jtorqui74 

> Ok. I have had this same problem some time ago with talk notifications, and for testing I have done the same procedure with the Nextcloud app. It has worked. Notifications reappear successfully. The problem lies in the Nextcloud database, specifically in the table _notifications_pushhash 

Tricky fix, but worked for me, this has been bothering me for quite a while now. 
Thanks much for finding out !! 😍

**Comment by HammyHavoc** [comment]
Seeing this problem too.

**Comment by nursoda** [comment]
> ```
> DELETE FROM oc_notifications_pushhash WHERE uid='nursoda';
> Delete accounts from the android app and log back in.
> ```

Thanks! Since it helped some guys here, I tried that. Without success:

I deleted the rows in the DB and the corresponding account in the app (I use several accounts in the app). I then force-closed the app, re-started it and re-created the just deleted account. Result: Account is available again and does receive test notifications in-app. Yet, no Android notifications. The app does not re-register with the cloud:

```
nc-user@server /path/cloud $ occ notification:test-push nursoda
No devices found for user
```
This correlates with not an entry in the DB:

```
MariaDB [cloud]> SELECT * FROM oc_notifications_pushhash WHERE uid='nursoda';`
Empty set (0,000 sec)
```

Server: 27.0.1, App 3.25.0, Phone: Pixel 6a running GrapheneOS with their sandboxed Play Service. All other apps work fine including push, e.g. Signal, Threema, Bank apps.

What now? Do I need to wipe all data from the NC app? Might this be a Graphene Play Services bug? How to debug and find out which app or service to blame?

**Comment by lfom** [comment]
@nursoda It seems that NextCloud does not request another token unless it is removed and installed again. At least for me it was the only way to request another token using MicroG after removing the older (broken) token from the database. It's a pain, but since then notifications have working fine.

**Comment by nursoda** [comment]
Thanks for that hint. I deleted all data from the app (instead of deleting and re-installing it), and it worked. Quite painful if you use multiple NC instances like me.

**Comment by mercury1337** [comment]
Tried again on fresh installation - still not working:

> Trying to push to 1 devices
> 
> Language is set to en_GB
> Private user key size: 1704
> Public user key size: 451
> Identified 0 Talk devices and 1 others.
> 
> Device token:67636
> Device token is valid
> Device public key size: 451
> Data to encrypt is: {"nid":3437,"app":"admin_notifications","subject":"Testing push notifications","type":"admin_notifications","id":"64fd8129"}
> Signed encrypted push subject
> **Deleting device because it is unknown by the push server:** 12JrPiB9KvMQbE83xs2Q3dWURmblKztjKdP3o/DEcOyROzp8iIhFqFkj6B5g9QaFW+3+2SnBzIjlIdavTbegA==
> **Push notification sent, but 1 failed**

**Comment by EnderArchery** [comment]
Maybe it doesn't awake from sleep properly because of some internal
optimization that can't be turned of?
I know that on my Samsung, Maps didn't even continue to navigate sometimes
even though it was excluded from list of apps to be optimized.

*and it fixed itself again sometimes*,
at least as far as I can tell

Pablo Eisenhut ***@***.***> schrieb am Di., 12. Sept. 2023,
21:27:

**Comment by mercury1337** [comment]
I can confirm that the notification is shown properly when the app is in foreground. When it is in background I only get the generic text "NEW NOTIFICATION"

**Comment by HammyHavoc** [comment]
Is anybody currently investigating this and getting anywhere? If not, I might give this a poke this weekend and see where I get with it.

**Comment by PeggyFree** [comment]
I subscribe here as I never got a readable notification on my phone and I won't re-install it as I don't want to lose my settings

**Comment by sander85** [comment]
Would be nice to have an entry in the app settings like "Fix notifications" or something like that, that will trigger new registration with the server. There are other apps that can do it. My setup is quite complex on my phone, and wiping it all just doesn't make sense.

**Comment by qguv** [comment]
I've been dealing with this for quite some time. Is there any plan to pick this up?

**Comment by kakuy** [comment]
I switched to this notifications app for Nextcloud and it works really well.

https://gitlab.com/Nextcloud-Push

It's a bit old and it does have some scalability shortcomings (they can be worked around but it needs some understanding of the webserver/php config)
I works perfectly for all notifications from the server (2FA, Talk, Calendar, etc.)... And the best part is that it does not depend on google services, so it works even on ungoogled devices.

**Comment by kakuy** [comment]
I know it is not a workaround, but it does solve most evident symptoms in this thread (show correct notifications on a phone).

I don't pretend to minimize the problematic behind reliable push notifications nor the complexities and priorities of the project but... I just don't understand why issues related to notifications take so much time to be addressed when there are alternatives that work and just need a little polish.

This ticket was opened more than 5 years ago, fixed and refixed and it keeps coming back. By the looks of the fixes it seems it's just a matter of following google's firebase dependency. There are other tickets asking for an official alternative to google handled notifications.

**Comment by Popkornium18** [comment]
I'm running into this issue again, unfortunately. :(

**Comment by EnderArchery** [comment]
Oh how weird, it hasn't happened to me in such a long time that I thought
it might have been fixed. (Android version 3.30.7)

Popkornium18 ***@***.***> schrieb am Di., 14. Jan. 2025,
00:05:

**Comment by tobiasKaminsky** [comment]
It seems that this is missing in our latest bugfix release.
I will add it and it will be in 3.30.8.

**Comment by bombz88** [comment]
have two devices 
device 01/user 01 = 3.30.7
> push notifications list as NEW_NOTIFICATION (NEW_NOTIFICATION)

device 02/user 02 = 3.30.8
> push notifications list as the content displayed (e.g. update for....) (update for....)

I am going to assume this has been addressed in 3.30.8 or does it pertain to tokes, db user, etc. ?

Look forward to hearing back

**Comment by jficz** [comment]
just fyi, notifications started to work for me out of the blue about a week or two ago. I can't recall if I made any changes, except I might have updated some Nextcloud apps (which included some push notifs). I'm on latest version from play store (3.30.8)

**Comment by bombz88** [comment]
> just fyi, notifications started to work for me out of the blue about a week or two ago. I can't recall if I made any changes, except I might have updated some Nextcloud apps (which included some push notifs). I'm on latest version from play store (3.30.8)

Appreciate the details & confirmation. Was doing some comparing in with the version variants / devices / db users the other day, and thought I'd confirm with the thread.

based on @tobiasKaminsky post, it seems the bugfix was added to 3.30.8 from the sounds of it?
My post was more of a sanity check to assume something else wasn't overlooked and confirmation on addressing the concern. 

Looking forward to the feedback :)

**Comment by bombz88** [comment]
Following up....
Both devices with two separate db users are showing proper notification updates/messages

Both Android client apps are on:
v. 3.31.0

Confirming this 'bug' is resolved based on the outcome described above.
Thank you for all the dev support!
