### ISSUE TITLE
Photos are stuck in the queue (instant upload)

### ISSUE THREAD

**Issue by schnello** [nextcloud/android#2055]
### Actual behaviour
App is set to "upload only with WiFi connection.
Turn off WLAN
make photo (Nextcloud app add the photo in the queue)
Turn on WLAN...
Nextcloud APP never starts the upload. 

### Expected behaviour
Nextcloud App should upload if the WiFi is accessible
 
### Steps to reproduce
see "### Actual behaviour"

### Environment data
Android version:
7.0

Device model: 
S8 Samsung

Stock or customized system:
Stock
Nextcloud app version:
3.0.0 RC2
Nextcloud server version:
Nextcloud 12.0.5

**Comment by mario** [comment]
@AndyScherzinger can you confirm this still happens with RC2?!

**Comment by AndyScherzinger** [comment]
@mario I do think so but I ran the master which we labeled RC2 earlier than the actual RC2 so I need to update to latest master tomorrow to be sure it is still happening with the actual master. But when testing your fixes for wifi and charging only it still happened as described. So that PR, code base still had the restart issue.

**Comment by tobiasKaminsky** [comment]
Should be fixed via #2062

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @mario auto restart is still not working for me on latest master, Android 8.

**Comment by mario** [comment]
@AndyScherzinger got you PR to test.

**Comment by AndyScherzinger** [comment]
@mario which PR (am on mobile only atm)

**Comment by mario** [comment]
@AndyScherzinger  https://github.com/nextcloud/android/pull/2066

**Comment by AndyScherzinger** [comment]
I can confirm (at least for my device running Android 8) that  #2066 fixes this issue. Ticket will be auto closed when  #2066 gets merged.

Fix is sheduled for 3.0.0RC3 cc @tobiasKaminsky
