### ISSUE TITLE
Capabilities update are not distributing on live view

### ISSUE THREAD

**Issue by przybylski** [nextcloud/android#2075]
When user is updating the list, it often happens that server capabilities are also updated.
Server capabilities for instance contains theming colors. After refreshing is completed FileDisplayActivity is refreshing its fragments, which are refreshing its list adapter.
The list adapter is getting the theme information directly from ThemeUtils, which has up to date information about coloring. So what happens if theme is changed between refreshes is that the icons are changing colors and app theming stays the same.
![zrzut ekranu 2018-01-30 o 17 30 17](https://user-images.githubusercontent.com/1734309/35578047-5140af8c-05e3-11e8-911e-16e28c961fbe.png)
This might lead to some bad user experience, from visual point of view, but could have more devastating causes, (undeleting?).
The question is do we care about such cases or should there be a mechanism which distributes the capabilities updates or at least the caller of update should be checking those and inform of potential updates?

**Comment by AndyScherzinger** [comment]
pinging @tobiasKaminsky since he implemented the theme capability of the client. Personally I'd say from an UX point of view either update everything or nothing (in between) while I think the nicest would of course be to re-theme the UI right away. Any comment @tobiasKaminsky ?

**Comment by tobiasKaminsky** [comment]
Capability update is only done during account switch or when refreshing the root folder.
I recently added some PRs to enhance the theming on the very first start.
Have you tried master, @przybylski?
If something is missing, this should be fixed as it is, as you said, a bad UX. Changing of the color should be done on all elements 👍

**Comment by przybylski** [comment]
I just tried on master and it is still the same:
1) Open app
2) change the theme color on server
3) refresh on mobile with pull to refresh

Result: only list elements applies the new theme.
@tobiasKaminsky which PR are you talking about? I probably missed it.

**Comment by tobiasKaminsky** [comment]
I only find this one, but I thought that there was more than one:
https://github.com/nextcloud/android/pull/1889

**Comment by przybylski** [comment]
https://github.com/nextcloud/android/pull/2084

**Comment by tobiasKaminsky** [comment]
As we do not show tinted header, this is not a problem any longer.
