### ISSUE TITLE
Contacts backup failing with "upload permission error"

### ISSUE THREAD

**Issue by gorn** [nextcloud/android#2245]
### Actual behaviour
- Contacts backup fails with "Permission error"

### Expected behaviour
- Contacts backup should happen succesfully and automatically on daily basis.
 
### Steps to reproduce
1. In  "Settings" (Nastavení) switch ON  "Contacts backup" (Zálohování kontaktů). 
2. In "Uploads" (Nahrání) I see lots of Failed uploads. One of them looks like this

```
 2018-02-27_14-37-36.vcf
Chyba oprávnění (Permisson error)
gorn @ cloud.example.com
/.Contacts-Backup
```

3. The backup never happens. 

Note: I use Czech version of app, so some of the menu items mentioned can be spelled differently, I always provide Czech original in parantheses.

### Environment data
Android version: 7.0 (kernel 3.18.14-12365438)
Device model: Samsung 7 - SM-G935F
Stock or customized system: stock
Nextcloud app version: 3.0.1
Nextcloud server version: 13.0.0.14

#### Web server error log
```
empty - no errors (in time +-2hours)
```

#### Nextcloud log (data/nextcloud.log)
```
empty (last line two days old)
```

**Comment by AndyScherzinger** [comment]
@gorn does this still happen with v3.0.2
cc @tobiasKaminsky for contact backup issues

**Comment by tobiasKaminsky** [comment]
I tested it with NC13 and 3.0.2 and it worked without a problem.

Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by DoubleODave** [comment]
I have the same issue, although in English and message is 'Connection error' rather than 'Permission error'. App v3.0.2 and NC 13, both freshly installed this week.

Logcat contains:

03-01 09:35:21.279  5234  5254 E VCardComposer: Cursor#moveToNext() returned false
03-01 09:35:21.284 14559 26882 D ContactsBackupJob: Storing: 2018-03-01_09-35-21.vcf
03-01 09:35:21.316 14559 14559 D FileUploader: Starting command with id 1
03-01 09:35:21.322  1370  1439 E NotificationService: No Channel found for pkg=com.nextcloud.client, channelId=null, id=411, tag=null, opPkg=com.nextcloud.client, callingUid=10166, userId=0, incomingUserId=0, notificationUid=10166, notification=Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0xff013c8f vis=PRIVATE)
03-01 09:35:21.324 14559 14559 V UploadsStorageManager: Inserting /data/user/0/com.nextcloud.client/cache/2018-03-01_09-35-21.vcf with status=UPLOAD_IN_PROGRESS
03-01 09:35:21.343 14559 26882 V ArbitraryDataProvider: Updating arbitrary data with cloud id: XXXX@XXXXX.XXX/nextcloud key: PREFERENCE_CONTACTS_LAST_BACKUP value: 1519896921321
03-01 09:35:21.344 14559 14559 D UploadsStorageManager: storeUpload returns with: content://org.nextcloud/uploads/1 for file: /data/user/0/com.nextcloud.client/cache/2018-03-01_09-35-21.vcf
03-01 09:35:21.344 14559 14559 D UploadsStorageManager: notifyObserversNow
03-01 09:35:21.345 14559 14559 D ContactsBackupJob: service connected
03-01 09:35:21.356 14559 26882 I JobExecutor: Finished job{id=2867, finished=true, result=SUCCESS, canceled=false, periodic=false, class=ContactsBackupJob, tag=ContactsBackupJob}
03-01 09:35:21.357 14559 26797 V UploadsStorageManager: Updating /data/user/0/com.nextcloud.client/cache/2018-03-01_09-35-21.vcf with status:UPLOAD_IN_PROGRESS and result:UNKNOWN (old:/data/user/0/com.nextcloud.client/cache/2018-03-01_09-35-21.vcf status:UPLOAD_IN_PROGRESS result:-1)
03-01 09:35:21.357 14559 26797 V UploadsStorageManager: Updating /data/user/0/com.nextcloud.client/cache/2018-03-01_09-35-21.vcf with status=UPLOAD_IN_PROGRESS
03-01 09:35:21.358 14559 26881 D PlatformAlarmService: Finished job, request{id=2867, tag=ContactsBackupJob, transient=false} SUCCESS
03-01 09:35:21.381 14559 26797 D UploadsStorageManager: updateUpload returns with: 1 for file: /data/user/0/com.nextcloud.client/cache/2018-03-01_09-35-21.vcf
03-01 09:35:21.381 14559 26797 D UploadsStorageManager: notifyObserversNow
03-01 09:35:21.396 14559 26797 W Notification: Use of stream types is deprecated for operations other than volume control
03-01 09:35:21.396 14559 26797 W Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-01 09:35:21.410 14559 26797 V UploadsStorageManager: Updating /data/user/0/com.nextcloud.client/cache/2018-03-01_09-35-21.vcf with status=UPLOAD_IN_PROGRESS
03-01 09:35:21.421  4620  4620 D NotificationListener: onNotificationPosted# hash: 159588542 sbn: StatusBarNotification(pkg=com.nextcloud.client user=UserHandle{0} id=2131296674 tag=null key=0|com.nextcloud.client|2131296674|null|10166: Notification(channel=NOTIFICATION_CHANNEL_UPLOAD pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x2 color=0xff013c8f vis=PRIVATE))
03-01 09:35:21.427 14559 26797 D UploadsStorageManager: updateUpload returns with: 1 for file: /data/user/0/com.nextcloud.client/cache/2018-03-01_09-35-21.vcf
03-01 09:35:21.427 14559 26797 D UploadsStorageManager: notifyObserversNow
03-01 09:35:21.431 14559 26797 E FileUploader: Error uploading
03-01 09:35:21.431 14559 26797 E FileUploader: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.owncloud.android.datamodel.OCFile.getFileId()' on a null object reference
03-01 09:35:21.431 14559 26797 E FileUploader: 	at com.owncloud.android.operations.UploadFileOperation.run(UploadFileOperation.java:374)
03-01 09:35:21.431 14559 26797 E FileUploader: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:145)
03-01 09:35:21.431 14559 26797 E FileUploader: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:149)
03-01 09:35:21.431 14559 26797 E FileUploader: 	at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:93)
03-01 09:35:21.431 14559 26797 E FileUploader: 	at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:1090)
03-01 09:35:21.431 14559 26797 E FileUploader: 	at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1023)
03-01 09:35:21.431 14559 26797 E FileUploader: 	at android.os.Handler.dispatchMessage(Handler.java:105)
03-01 09:35:21.431 14559 26797 E FileUploader: 	at android.os.Looper.loop(Looper.java:164)
03-01 09:35:21.431 14559 26797 E FileUploader: 	at android.os.HandlerThread.run(HandlerThread.java:65)
03-01 09:35:21.431 14559 26797 D UploadsStorageManager: updateDatabaseUploadResult uploadResult: com.owncloud.android.lib.common.operations.RemoteOperationResult@4236a0e upload: com.owncloud.android.operations.UploadFileOperation@2389c2f
03-01 09:35:21.434 14559 26797 V UploadsStorageManager: Updating /data/user/0/com.nextcloud.client/cache/2018-03-01_09-35-21.vcf with status:UPLOAD_FAILED and result:NETWORK_CONNECTION (old:/data/user/0/com.nextcloud.client/cache/2018-03-01_09-35-21.vcf status:UPLOAD_IN_PROGRESS result:-1)
03-01 09:35:21.434 14559 26797 V UploadsStorageManager: Updating /data/user/0/com.nextcloud.client/cache/2018-03-01_09-35-21.vcf with status=UPLOAD_FAILED
03-01 09:35:21.443 14559 26797 D UploadsStorageManager: updateUpload returns with: 1 for file: /data/user/0/com.nextcloud.client/cache/2018-03-01_09-35-21.vcf
03-01 09:35:21.443 14559 26797 D UploadsStorageManager: notifyObserversNow
03-01 09:35:21.443 14559 26797 D FileUploader: NotifyUploadResult with resultCode: HOST_NOT_AVAILABLE

**Comment by gorn** [comment]
Where can I get 3.0.2? Latest on F-droid is 3.0.1

**Comment by AndyScherzinger** [comment]
3.0.2 is available on GPlay and we are waiting for f-droid to also do a build&publish for it

**Comment by gorn** [comment]
Thanks ... I will wait when its published and test. I hestitate with logcat - my device is not rooted and I use it everyday + dunno how risky rooting is.

**Comment by gorn** [comment]
Ok, F-droid updated me to 3.0.2 and the problem still persist. The only visible difference is that now the error in "Uploads" is **Chyba připojení (Connection error)** and the application log is not empty. It is attached (I have only replaced my domain by example.com)

[currentLog.txt](https://github.com/nextcloud/android/files/1786493/currentLog.txt)

server log is still empty (not really, but does not grow while I try the contact backup thing).

**Comment by mario** [comment]
3.0.3 should fix this :)

**Comment by tobiasKaminsky** [comment]
Fdroid still have some hiccups, but this is not in our hand.
Please re-open once 3.0.3 tested an it did not fixed this.

**Comment by gorn** [comment]
Will be checking. No trace of 3.0.3 of F-droid yet :)

**Comment by gorn** [comment]
Unfortunately the problem persists. I attach the application log as screenshot - I just guess that this is the interesting part. When I try to press the "Odezva" (Feedback) option in Settings it responds "Error: can¨t ger files to be copied"

**Comment by tobiasKaminsky** [comment]
The screenshot is missing.

**Comment by gorn** [comment]
Sorry. Here is it
https://mrak.kub.cz/s/W2sewoJZrtDojWY

**Comment by tobiasKaminsky** [comment]
Does the folder exist on server?

Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by heikojansen** [comment]
I had the same problem and just found the solution (although it might not be the solution for you since there might be other reasons):
I had this rule in my nginx.conf:
```
location ~* /\.(?!well-known\/|file) {
    deny all;
}
```
Usually you do not want anybody to access hidden or temporary files on your webserver (like ".htpasswd", ".git" etc.) so I think this rule makes perfect sense. 

And I would really prefer Nextcloud **not** making use of directories or files with a dot as first char.

But since there is no way to configure the storage directory for the contacts backup I modified the nginx config like so:

```
location ~* /\.(?!well-known\/|Contacts-Backup|file) {
    deny all;
}
```

**Comment by gorn** [comment]
Just for record - I had the same problem as  @heikojansen. I was not aware that nextcloud needs access to dot files, so it was forbidden.

**Comment by fjna** [comment]
I am using a prehosted alternative thus I can't modify the server config.

Is there anyway to specifiy the output folder for the contacts backup?
