### ISSUE TITLE
No files on local folder selection for the custom local folder auto upload

### ISSUE THREAD

**Issue by SkyWheel** [nextcloud/android#2462]
Hi team,
I have 2 different devices with the latest F-Droid Nextcloud beta app.
On both devices I'm trying to choose custom local folder for auto upload. But it doesn't show files at all. Whether manual upload function works fine.

**Comment by tobiasKaminsky** [comment]
This is fixed via https://github.com/nextcloud/android/pull/2450 and is already available in newest 3.1 release, which will be soon in fdroid.

Dup of #2438

**Comment by SkyWheel** [comment]
I'm using Nextcloud Dev fdroid version 20180414, but the bug is still there.

**Comment by AndyScherzinger** [comment]
@SkyWheel the fix has not yet been merged so the you are still facing the issue. I hope we get it merged very soon. cc @mario
