### ISSUE TITLE
Missbehaviour on syncing big folders

### ISSUE THREAD

**Issue by gleichda** [nextcloud/android#2559]
### Actual behaviour
I have all my music synchronized to Nextcloud. This is quite a big folder having 43GB Containing 8835 Files in 776 subfolders (strucutred by artist/album/filename.mp3 if that is important)
Now when i want to Sync that folder to my Phone. I get the message Nextcloud not responding from Android. While I still see incoming requests from the app to Apache on the access.log and also notifications that files are downloaded.

### Expected behaviour
Nextcloud should sync in Background

### Steps to reproduce
1. create a folder containing many subfolders and files below it
2. sync the whole folder to Android

### Environment data
Android version: Android 8.1 Security Level 1st April 18

Device model: Nokia 5 TA-1053

Stock or customized system: Stock rom not rooted

Nextcloud app version: 3.1.0 (from F-Droid)

Nextcloud server version: 13.0.2

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by tobiasKaminsky** [comment]
Seems that somehow the sync process is blocking UI and therefore android is showing the "not response" warning.

**Comment by mario** [comment]
I think it's just that the upload/download services are really bad and just try to do everything at once.

**Comment by BinkaDroid** [comment]
Android P will crash not responding apps instead of showing the not-responding-warning ...

As the actual syncing isn't an issue here right now, it could get problematic if Android Phone decided to crash the app ...

**Comment by mirgleich** [comment]
I had a deeper look into it now. It seems that Android O is already terminating non responding apps, when the screen is dark or the app is not running in foreground. Therefore it is working as long as the screen is on and you are not doing something else on the phone. 
Probably a permanent notification while syncing could solve the issue?

**Comment by tobiasKaminsky** [comment]
As @mario said, we need to change the up/download service to a job based system, which then can be correctly used & triggered by android's doze syste.

**Comment by ReekyMarko** [comment]
This is pretty bad, and IMO should be fixed ASAP. Syncing files is one of the core features of any cloud service, and as of now, it's completely unusable.

**Comment by rcdailey** [comment]
Where are we 6 months later on this issue?

**Comment by DragonQ** [comment]
This is still an issue. I click a folder and choose Sync, then Android claims the Nextcloud app has crashed. I can click "wait" and it'll carry on syncing for a bit but after maybe 30-60 seconds the sync just stops and I have to start again.

Telling Android to stop optimising battery for the Nextcloud app doesn't help, it still stops syncing at some point.

**Comment by AndyScherzinger** [comment]
this is a duplicate of #2010

**Comment by DagNygren** [comment]
This is still happening. Any clues on what could be done?
