### ISSUE TITLE
Android 9 unable to start app

### ISSUE THREAD

**Issue by ictabc** [nextcloud/android#3257]
Nextcloud app crashes every time it is starting. No logging no error message.

Pixel 3 XL
Android 9 November update

**Comment by tobiasKaminsky** [comment]
I tried it with emulator and there it works…

Can you provide us additional infos via logcat? https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

**Comment by AndyScherzinger** [comment]
tried it with emulator and OP3T running Andorid 9, no crashes.

@ictabc please re-open in case crashes still occur during start _and_ you can provide a log.

**Comment by ictabc** [comment]
Finally had time for the locat:

02-04 06:05:48.738  6072  6072 E AndroidRuntime: FATAL EXCEPTION: main
02-04 06:05:48.738  6072  6072 E AndroidRuntime: Process: com.nextcloud.client, PID: 6072
02-04 06:05:48.738  6072  6072 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.owncloud.android.MainApp: android.database.sqlite.SQLiteException: duplicate column name: redirect (code 1 SQLITE_ERROR): , whil
e compiling: ALTER TABLE external_links ADD COLUMN redirect INTEGER
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5925)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6718)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
02-04 06:05:48.738  6072  6072 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteException: duplicate column name: redirect (code 1 SQLITE_ERROR): , while compiling: ALTER TABLE external_links ADD COLUMN redirect INTEGER
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:903)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:514)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1770)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1698)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at com.owncloud.android.providers.FileContentProvider$DataBaseHelper.onUpgrade(FileContentProvider.java:1741)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:398)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:322)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at com.owncloud.android.providers.FileContentProvider.query(FileContentProvider.java:485)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at android.content.ContentProvider.query(ContentProvider.java:1057)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at android.content.ContentProvider.query(ContentProvider.java:1149)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at android.content.ContentProvider$Transport.query(ContentProvider.java:241)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at android.content.ContentResolver.query(ContentResolver.java:802)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at android.content.ContentResolver.query(ContentResolver.java:752)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at android.content.ContentResolver.query(ContentResolver.java:710)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at com.owncloud.android.datamodel.SyncedFolderProvider.getSyncedFolders(SyncedFolderProvider.java:105)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at com.owncloud.android.datamodel.SyncedFolderProvider.updateAutoUploadPaths(SyncedFolderProvider.java:246)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at com.owncloud.android.MainApp.updateAutoUploadEntries(MainApp.java:556)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at com.owncloud.android.MainApp.initSyncOperations(MainApp.java:299)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at com.owncloud.android.MainApp.onCreate(MainApp.java:167)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
02-04 06:05:48.738  6072  6072 E AndroidRuntime:        ... 8 more

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
@ictabc which version did you tried? 
Can you try latest beta on gplay? I think this is already fixed via #3507

**Comment by ictabc** [comment]
Ok, installed the beta 3.5.0-RC1.

Still crashes but I now see the nextloud login page in the background.

The error I get now is:

02-06 12:26:05.621  1132  1162 I ActivityManager: Start proc 20725:com.nextcloud.client/u0a250 for activity com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity
02-06 12:26:05.627 20725 20725 E extcloud.clien: Not starting debugger since process cannot load the jdwp agent.
02-06 12:26:05.656 20725 20725 I extcloud.clien: The ClassLoaderContext is a special shared library.
02-06 12:26:05.671 20725 20725 I MultiDex: VM with version 2.1.0 has multidex support
02-06 12:26:05.671 20725 20725 I MultiDex: Installing application
02-06 12:26:05.671 20725 20725 I MultiDex: VM has multidex support, MultiDex support library is disabled.
02-06 12:26:05.680 20725 20725 D FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
02-06 12:26:05.681 20725 20725 D FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
02-06 12:26:05.681 20725 20725 D FirebaseApp: com.google.android.gms.measurement.AppMeasurement is not linked. Skipping initialization.
02-06 12:26:05.681 20725 20725 I FirebaseInitProvider: FirebaseApp initialization successful
02-06 12:26:05.697 20725 20725 E DisplayUtils: Failed to use reflection to enable proper vector scaling
02-06 12:26:05.701 20725 20725 D Debug   : start logging
02-06 12:26:05.709 20725 20725 I JobManager: Found pending job request{id=21, tag=FilesSyncJob, transient=false}, canceling
02-06 12:26:05.716 20725 20744 I extcloud.clien: The ClassLoaderContext is a special shared library.
02-06 12:26:05.718 20725 20744 I chatty  : uid=10250(com.nextcloud.client) AsyncTask #1 identical 1 line
02-06 12:26:05.720 20725 20744 I extcloud.clien: The ClassLoaderContext is a special shared library.
02-06 12:26:05.724 20725 20725 D JobProxy26: Schedule periodic jobInfo success, request{id=24, tag=FilesSyncJob, transient=false}, interval 00:15:00, flex 00:05:00
02-06 12:26:05.725 20725 20747 E AndroidRuntime: FATAL EXCEPTION: Thread-2
02-06 12:26:05.725 20725 20747 E AndroidRuntime: Process: com.nextcloud.client, PID: 20725
02-06 12:26:05.725 20725 20747 E AndroidRuntime: java.lang.NullPointerException: Attempt to get length of null array
02-06 12:26:05.725 20725 20747 E AndroidRuntime: 	at org.lukhnos.nnio.file.Files.walkFileTree(Files.java:342)
02-06 12:26:05.725 20725 20747 E AndroidRuntime: 	at com.owncloud.android.utils.FilesSyncHelper.insertAllDBEntriesForSyncedFolder(FilesSyncHelper.java:130)
02-06 12:26:05.725 20725 20747 E AndroidRuntime: 	at com.owncloud.android.MainApp.lambda$initiateExistingAutoUploadEntries$2(MainApp.java:620)
02-06 12:26:05.725 20725 20747 E AndroidRuntime: 	at com.owncloud.android.-$$Lambda$MainApp$Nk1X_HiHB--su1rAf_YxjHyEBKE.run(Unknown Source:0)
02-06 12:26:05.725 20725 20747 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
02-06 12:26:05.732 20725 20747 I Process : Sending signal. PID: 20725 SIG: 9
02-06 12:26:05.743   758   758 I Zygote  : Process 20725 exited due to signal (9)
02-06 12:26:05.743  1132  1143 I ActivityManager: Process com.nextcloud.client (pid 20725) has died: fore TOP 
02-06 12:26:05.743  1132  1163 W libprocessgroup: kill(-20725, 9) failed: No such process
02-06 12:26:05.743  1132  1163 I libprocessgroup: Successfully killed process cgroup uid 10250 pid 20725 in 0ms

**Comment by ictabc** [comment]
Ok new update. Was planning on clearing storage as I was going to App info, I saw that no permissions where given. I manually set the permissions and started it again, now it shows me the start page.

Now going to setup the app and see if that fixes my problem. Guess the app should ask for permission, but doesn't for some reason.

**Comment by tobiasKaminsky** [comment]
Hm. It should ask and normally it asks on first startup, but maybe due to the crashes this somehow got lost.
Anyway, I am glad that it fixed it!
