### ISSUE TITLE
An unknown error occured when logging in

### ISSUE THREAD

**Issue by Gerii** [nextcloud/android#342]
### Actual behaviour

App successfully connects to the server upon entering the address. But after inputting the right login credentials and clicking on Login an unknown error occurs.

Only happens on this device. Other devices (like Nexus 5, Jolla, BlackBerry Z30) connect successfully.
The client on the phone does work with an older ownCloud instance though.
### Expected behaviour

Login succeeds.
### Steps to reproduce
1. Input server URL
2. Input username & password
3. Click on Login
### Environment data

Android version: 6.0

Device model: LG G4

Stock or customized system: stock

Nextcloud app version: 1.3.1

Nextcloud server version: 10.0.1
#### Web server error log

no error happens on server side
#### Nextcloud log (data/nextcloud.log)

Logcat output:

```
10-16 16:42:44.277 31269-5692/? D/GetRemoteUserInfoOperation: Successful response: <!DOCTYPE html>
                                                              <html class="ng-csp" data-placeholder-focus="false" lang="en" >
                                                                <head data-user="username" data-user-displayname="username" data-requesttoken="token removed by me">
                                                                    <meta charset="utf-8">
                                                                    <title>
                                                                        Files - Cloud       </title>
                                                                    <meta http-equiv="X-UA-Compatible" content="IE=edge">
                                                                    <meta name="referrer" content="never">
                                                                    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
                                                                    <meta name="apple-itunes-app" content="app-id=1125420102">
                                                                    <meta name="apple-mobile-web-app-capable" content="yes">
                                                                    <meta name="apple-mobile-web-app-status-bar-style" content="black">
                                                                    <meta name="apple-mobile-web-app-title" content="ownCloud">
                                                                    <meta name="mobile-web-app-capable" content="yes">
                                                                    <meta name="theme-color" content="#102083">
                                                                    <link rel="icon" href="/owncloud/core/img/favicon.ico">
                                                                    <link rel="apple-touch-icon-precomposed" href="/owncloud/core/img/favicon-touch.png">
                                                                    <link rel="mask-icon" sizes="any" href="/owncloud/core/img/favicon-mask.svg" color="#0082c9">
                                                                                <link rel="stylesheet" href="/owncloud/core/css/styles.css?v=ddab49e9822f524c8df370e2da30677a">
                                                                                <link rel="stylesheet" href="/owncloud/core/css/inputs.css?v=ddab49e9822f524c8df370e2da30677a">
                                                                                <link rel="stylesheet" href="/owncloud/core/css/header.css?v=ddab49e9822f524c8df370e2da30677a">
                                                                                <link rel="stylesheet" href="/owncloud/core/css/icons.css?v=ddab49e9822f524c8df370e2da30677a">
                                                                                <link rel="stylesheet" href="/owncloud/core/css/fonts.css?v=ddab49e9822f524c8df370e2da30677a">
                                                                                <link rel="stylesheet" href="/owncloud/core/css/apps.css?v=ddab49e9822f524c8df370e2da30677a">
                                                                                <link rel="stylesheet" href="/owncloud/core/css/global.css?v=ddab49e9822f524c8df370e2da30677a">
                                                                                <link rel="stylesheet" href="/owncloud/core/css/fixes.css?v=ddab49e9822f524c8df370e2da30677a">
                                                                                <link rel="stylesheet" href="/owncloud/core/css/multiselect.css?v=ddab49e9822f524c8df370e2da30677a">
                                                                                <link rel="stylesheet" href="/owncloud/core/css/mobile.css?v=ddab49e9822f524c8df370e2da30677a">
                                                                                <link rel="stylesheet" href="/owncloud/core/vendor/jquery-ui/themes/base/jquery-ui.css?v=ddab49e9822f524c8df370e2da30677a">
                                                                                <link rel="stylesheet" href="/owncloud/core/css/jquery-ui-fixes.css?v=ddab49e9822f524c8df370e2da30677a">
                                                                                <link rel="stylesheet" href="/owncloud/core/css/tooltip.css?v=ddab49e9822f524c8df370e2da30677a">
                                                                                <link rel="stylesheet" href="/owncloud/core/css/share.css?v=ddab49e9822f524c8df370e2da30677a">
                                                                                <link rel="stylesheet" href="/owncloud/apps/files_versions/css/versions.css?v=ddab49e9822f524c8df370e2da30677a">
                                                                                <link rel="stylesheet" href="/owncloud/apps/audioplayer/css/3rdparty/fontello/css/fontello.css?v=ddab49e9822f524c8df370e2da30677a">
                                                                                <link rel="stylesheet" href="/owncloud/apps/audioplayer/css/style.css?v=ddab49e9822f524c8df370e2da30677a">
                                                                                <link rel="stylesheet" href="/owncloud/apps/files_pdfviewer/css/style.css?v=ddab49e9822f524c8df370e2da30677a">
                                                                                <link rel="stylesheet" href="/owncloud/apps/files_videoplayer/css/style.css?v=ddab49e9822f524c8df370e2da30677a">
                                                                                <link rel="stylesheet" href="/owncloud/apps/firstrunwizard/css/colorbox.css?v=ddab49e9822f524c8df370e2da30677a">
                                                                                <link rel="stylesheet" href="/owncloud/apps/firstrunwizard/css/firstrunwizard.css?v=ddab49e9822f524c8df370e2da30677a">
                                                                                <link rel="stylesheet" href="/owncloud/apps/gallery/css/slideshow.css?v=ddab49e9822f524c8df370e2da30677a">
                                                                                <link rel="stylesheet" href="/owncloud/apps/gallery/css/gallerybutton.css?v=ddab49e9822f524c8df370e2da30677a">
                                                                                <link rel="stylesheet" href="/owncloud/core/css/jquery.ocdialog.css?v=ddab49e9822f524c8df370e2da30677a">
                                                                                <link rel="stylesheet" href="/owncloud/apps/files/css/files.css?v=ddab49e9822f524c8df370e2da30677a">
                                                                                <link rel="stylesheet" href="/owncloud/apps/files/css/upload.css?v=ddab49e9822f524c8df370e2da30677a">
                                                                                <link rel="stylesheet" href="/owncloud/apps/fi
10-16 16:42:44.280 31269-5692/? E/GetRemoteUserInfoOperation: Exception while getting OC user information
                                                              org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
                                                                  at org.json.JSON.typeMismatch(JSON.java:111)
                                                                  at org.json.JSONObject.<init>(JSONObject.java:160)
                                                                  at org.json.JSONObject.<init>(JSONObject.java:173)
                                                                  at com.owncloud.android.lib.resources.users.GetRemoteUserInfoOperation.run(GetRemoteUserInfoOperation.java:77)
                                                                  at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136)
                                                                  at com.owncloud.android.authentication.AuthenticatorAsyncTask.doInBackground(AuthenticatorAsyncTask.java:84)
                                                                  at com.owncloud.android.authentication.AuthenticatorAsyncTask.doInBackground(AuthenticatorAsyncTask.java:41)
                                                                  at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                  at java.lang.Thread.run(Thread.java:818)
```

**Comment by derkostka** [comment]
Same happens on Nexus 7 (2013). No Login possible ...

**Comment by AndyScherzinger** [comment]
@derkostka do you see the same log entries?
@Gerii do you use the same user/credentials on all the devices you mentioned or do they differ? What I can read from the log you provided is that while the client tried to read an expected JSON reply the server replied with a HTML webpage which leads to the error.

@MorrisJobke @nickvergessen any idea what's happening here?
cc @tobiasKaminsky

**Comment by nickvergessen** [comment]
Seems like an exception page is being printed. Can you have a look at the nextcloud server log?

**Comment by Gerii** [comment]
@AndyScherzinger The same account works on a different device.
@nickvergessen There is nothing which would hint at an error in the nextcloud.log on the server.

**Comment by Gerii** [comment]
I looked through the Apache access logs and I think that's one of the failed login attempts:
`192.168.0.128 - username [16/Oct/2016:16:42:38 +0200] "HEAD /owncloud/remote.php/webdav/ HTTP/1.1" 200 1391 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
192.168.0.128 - username [16/Oct/2016:16:42:40 +0200] "GET /owncloud/index.php/ocs/cloud/user?format=json HTTP/1.1" 302 1502 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"
192.168.0.128 - username [16/Oct/2016:16:42:42 +0200] "GET /owncloud/index.php/apps/files/ HTTP/1.1" 200 43617 "-" "Mozilla/5.0 (Android) ownCloud-android/1.3.1"`
There is a 302 in there, so that explains the HTML site. I don't have a clue why it does this though.

**Comment by derkostka** [comment]
@AndyScherzinger same error-log for me:

> 10-17 22:30:12.947  9655 16874 E GetRemoteUserInfoOperation: org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
10-17 22:30:12.947  9655 16874 E GetRemoteUserInfoOperation: 	at org.json.JSON.typeMismatch(JSON.java:111)
10-17 22:30:12.947  9655 16874 E GetRemoteUserInfoOperation: 	at org.json.JSONObject.<init>(JSONObject.java:160)
10-17 22:30:12.947  9655 16874 E GetRemoteUserInfoOperation: 	at org.json.JSONObject.<init>(JSONObject.java:173)
10-17 22:30:12.947  9655 16874 E GetRemoteUserInfoOperation: 	at com.owncloud.android.lib.resources.users.GetRemoteUserInfoOperation.run(GetRemoteUserInfoOperation.java:77)
10-17 22:30:12.947  9655 16874 E GetRemoteUserInfoOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136)
10-17 22:30:12.947  9655 16874 E GetRemoteUserInfoOperation: 	at com.owncloud.android.authentication.AuthenticatorAsyncTask.doInBackground(AuthenticatorAsyncTask.java:84)
10-17 22:30:12.947  9655 16874 E GetRemoteUserInfoOperation: 	at com.owncloud.android.authentication.AuthenticatorAsyncTask.doInBackground(AuthenticatorAsyncTask.java:41)
10-17 22:30:12.947  9655 16874 E GetRemoteUserInfoOperation: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
10-17 22:30:12.947  9655 16874 E GetRemoteUserInfoOperation: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-17 22:30:12.947  9655 16874 E GetRemoteUserInfoOperation: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
10-17 22:30:12.947  9655 16874 E GetRemoteUserInfoOperation: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-17 22:30:12.947  9655 16874 E GetRemoteUserInfoOperation: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-17 22:30:12.947  9655 16874 E GetRemoteUserInfoOperation: 	at java.lang.Thread.run(Thread.java:818)

**Comment by nickvergessen** [comment]
> GET /owncloud/index.php/ocs/cloud/user?format=json

This URL is wrong. The correct URL is `ocs/v1.php/cloud/user?format=json` and `ocs/v2.php/cloud/user?format=json`

Can you check the redirects on your server?

**Comment by AndyScherzinger** [comment]
@nickvergessen .... hmmm, the client library uses the one mentioned:
https://github.com/nextcloud/android-library/blob/master/src/com/owncloud/android/lib/resources/users/GetRemoteUserInfoOperation.java#L49

--> ```private static final String OCS_ROUTE = "/index.php/ocs/cloud/user?format=json";```

which route would be save for Nextcloud and also let's say oC8.x?

**Comment by AndyScherzinger** [comment]
see also https://github.com/nextcloud/android-library/issues/18

**Comment by nickvergessen** [comment]
`ocs/v1.php/cloud/user?format=json` is the route, since ever! `index.php/ocs/` never worked (intended)

**Comment by AndyScherzinger** [comment]
@nickvergessen perfect :) --> https://github.com/nextcloud/android-library/pull/21/files#diff-edcf6967567594420549a81338e02d99R49 - will have to wait for jitpack to do the build/publish to test drive this for @tobiasKaminsky to do the review then :smiley:

**Comment by AndyScherzinger** [comment]
Hi @Gerii can you test our latest beta client release (can be installed in parallel to the regular app):
https://f-droid.org/repository/browse/?fdfilter=com.nextcloud&fdid=com.nextcloud.android.beta

It contains a fix for a login issue we found and which has been discussed in this issue, so this might solve your problem and will then also be integrated into the next regular/stable release 1.4.0

**Comment by Gerii** [comment]
I have already tested it, it's working now. Thanks!

**Comment by AndyScherzinger** [comment]
Fixed in beta,will be released with the next stable release

**Comment by Fade78** [comment]
Hello,

I tried the client on google play, I tried the client on F-droid (1.4.1) and the beta client on F-droid (20170214) and I still have the "unknown" error. I'm on a Galaxy S5 Android 4.4.2.

**Comment by tobiasKaminsky** [comment]
@Fade78 if you want you can write an email to android AT nextcloud DOT com with your server address and I will have a look, please refer to this issue.

**Comment by unalignedcoder** [comment]
Same problem here. App crashes upon login. Not sure it even logs in, as the login screen just suddenly disappears. I only tested this with my Samsung Note 3 with Android 4.4.2

**Comment by unalignedcoder** [comment]
FYI... the last update 1.4.2 still has this problem. Funny thing, I can perfectly login and handle files via Solid Explorer.

**Comment by tobiasKaminsky** [comment]
@unalignedcoder can you write to android at nextcloud dot com and give us your server address with a dummy test account?

**Comment by eqyiel** [comment]
This is happening to me too, AFAICT these are the relevant lines from logcat:

```
06-12 12:41:01.218 12318  6997 D OwnCloudClient #19: REQUEST GET /ocs/v1.php/cloud/user
06-12 12:41:02.245 12318  6997 W HttpMethodBase: Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
06-12 12:41:02.248 12318  6997 D GetRemoteUserInfoOperation: Successful response: {"ocs":{"meta":{"status":"failure","statuscode":998,"message":"Invalid query, please check the syntax. API specifications are here: http:\/\/www.freedesktop.org\/wiki\/Specifications\/open-collaboration-services. DEBUG OUTPUT:\n"},"data":[]}}
06-12 12:41:02.260 12318  6997 E GetRemoteUserInfoOperation: Exception while getting OC user information
06-12 12:41:02.260 12318  6997 E GetRemoteUserInfoOperation: org.json.JSONException: Value [] at data of type org.json.JSONArray cannot be converted to JSONObject
06-12 12:41:02.260 12318  6997 E GetRemoteUserInfoOperation:    at org.json.JSON.typeMismatch(JSON.java:100)
06-12 12:41:02.260 12318  6997 E GetRemoteUserInfoOperation:    at org.json.JSONObject.getJSONObject(JSONObject.java:613)
06-12 12:41:02.260 12318  6997 E GetRemoteUserInfoOperation:    at com.owncloud.android.lib.resources.users.GetRemoteUserInfoOperation.run(GetRemoteUserInfoOperation.java:79)
06-12 12:41:02.260 12318  6997 E GetRemoteUserInfoOperation:    at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136)
06-12 12:41:02.260 12318  6997 E GetRemoteUserInfoOperation:    at com.owncloud.android.authentication.AuthenticatorAsyncTask.doInBackground(AuthenticatorAsyncTask.java:84)
06-12 12:41:02.260 12318  6997 E GetRemoteUserInfoOperation:    at com.owncloud.android.authentication.AuthenticatorAsyncTask.doInBackground(AuthenticatorAsyncTask.java:41)
06-12 12:41:02.260 12318  6997 E GetRemoteUserInfoOperation:    at android.os.AsyncTask$2.call(AsyncTask.java:305)
06-12 12:41:02.260 12318  6997 E GetRemoteUserInfoOperation:    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-12 12:41:02.260 12318  6997 E GetRemoteUserInfoOperation:    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
06-12 12:41:02.260 12318  6997 E GetRemoteUserInfoOperation:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
06-12 12:41:02.260 12318  6997 E GetRemoteUserInfoOperation:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
06-12 12:41:02.260 12318  6997 E GetRemoteUserInfoOperation:    at java.lang.Thread.run(Thread.java:761)
```

**Comment by eqyiel** [comment]
@tobiasKaminsky sent

**Comment by tobiasKaminsky** [comment]
@eqyiel 
According to my emails the problem was due to a missing endpoint and can be fixed on server side.
If this bug is still valid, please re-open with more details.

**Comment by eqyiel** [comment]
@tobiasKaminsky Indeed, thank you!
