### ISSUE TITLE
Instant upload does not work in beta 20161026 S7 Edge

### ISSUE THREAD

**Issue by andykvakk** [nextcloud/android#363]
### Actual behaviour

-After upgrading til Beta 20161026 instant upload of camera photos is not working. Tried to configure upload folders as the app told me after upgrade, but i am not able to select my correct camerafolder.

My photos are stored in /storage/3338-6339/DCIM/Camera, but the app suggests /storage/emulated/0/DCIM/Camera, but this folder only contains Snapchat photos.

May be something of the same I experienced in OwnCloud after upgrade: https://github.com/owncloud/android/issues/1795#issuecomment-245013382
### Expected behaviour

-The photos should upload instantly
### Steps to reproduce
1. Take picture
2. Wait for upload
3. Not in upload queue
### Environment data

Android version: 6.0.1

Device model: Samsung Galaxy S7 Edge

Stock or customized system: Stock

Nextcloud app version: 20161026 beta

Nextcloud server version: 10.0.1 beta
### Logs

...
#### Web server error log

N/A
#### Nextcloud log (data/nextcloud.log)

N/A

**Comment by mr-bolle** [comment]
I can confirm this behaviour

**Environment data**

Android version: 6.0.1
Device model: Sony Xperia Z3 binary (D6633) 
Stock or customized system: Stock
Nextcloud app version: 20161026 beta
Nextcloud server version: 10.0.1 (stable)

**Comment by AndyScherzinger** [comment]
Hi @andykvakk and @mr-bolle am I guessing correctly that your 'other' camera folder is on your SD card?

**Comment by andykvakk** [comment]
Correct. The /storage/emulated/0... is internal memory, not extra sd card. Extra sd card with pictures from camera is /storage/3338...

**Comment by mr-bolle** [comment]
@AndyScherzinger Thanks for the hind. I have chosen the internal memory and it works. 

I have found that the instant upload of screenshots (image type .png) is not yet possible. When I change the screenshot in .jpg, the upload starts automatically.

best regards
Raiko

**Comment by AndyScherzinger** [comment]
Thanks for the png hint @mr-bolle. 

@tobiasKaminsky we should imho upload pngs too :) What do you think?

**Comment by andykvakk** [comment]
@AndyScherzinger, sorry, I misunderstod, but in instant upload settings, the sd camers folder is not visible. If i select internal storage in my camera app (defalt samsung) the pictures are showing in instant upload settings, but are not uploaded.

Anyway, I should be able to instant upload pictures from my sd card . @mr-bolle, is this the same behaviour you are seeing?

**Comment by mr-bolle** [comment]
Do you create a new picture with your camera app? The instant upload runs only if you add any new picture. Or you can try to copy with a file manager a new file. If you select the external sd card, the nextcloud app don't see any changes.

**Comment by andykvakk** [comment]
@mr-bolle Yes. I have also pasted a file with Total Commander, but still no luck. It is very much like the issue I had with OC before moving to NC.

A quick summary:
1. I have tried to change from SD to Internal memory in Samsungs Camera App. The pictures are stored correct depending on the camera settings.
2. Nextcloud only suggests one camerafolder in instantupload settings, this is not my sd card folder, but a camerafolder. In total commander, the SD card is named USB and the internal memory is named SD-card.
3. Instantupload does not work at all for me now, version 20161027 on my stock S7Edge.

![screenshot_20161031-092439](https://cloud.githubusercontent.com/assets/21997405/19848201/2425902a-9f4c-11e6-88b3-bb5ec6a14e63.png)
![screenshot_20161031-092451](https://cloud.githubusercontent.com/assets/21997405/19848200/24229cda-9f4c-11e6-8637-df510e3f4494.png)

**Comment by AndyScherzinger** [comment]
Hi @andykvakk I did a little digging and it seems "USB" in a valid "drive" but it is not considered an external space so Android isn't scanning through the files and thus we can't find these images/folders with the Android media queries.

So in this case USB drives can/will be supported at a later stage when we enable you to configure _any_ kind of folder pair. Then you can use it the way instant upload works with this implementation. We'll have to see if we can/should add this to the initial version since it adds complexity and thus adds to the risk of potential bugs.

What do you think @tobiasKaminsky ?

**Comment by andykvakk** [comment]
One thing i notice is thst google photo app is showing pictures from both sd and "usb" when selecting device folders. Also OC client had this same issue when they changed the upload method because of android L.

**Comment by AndyScherzinger** [comment]
No worries! :) 

If the images do not get uploaded than that is a bug we need to hunt down and if Google is able to also show image folder on USB drives than we will find a way to do that too :+1:

**Comment by AndyScherzinger** [comment]
As for OC they are relying on the camera intent as a fall back which is rendered obsolete by Android N so that will break at some point. 

Looking into it!

**Comment by andykvakk** [comment]
@AndyScherzinger 
I just noticed that NC storage path setting shows both storage options.

![screenshot_20161031-212053](https://cloud.githubusercontent.com/assets/21997405/19870760/48f5650e-9fb2-11e6-854b-6d45e0c229fb.png)

**Comment by AndyScherzinger** [comment]
Yes it does, that is the SD card support which uses the file system Api while the instant upload uses the media Api. This way we query Android's database for images on the device. The file system Api doesn't offer this so we would have to manually scan the complete file system which would not be a solution. 

I am trying to find out if and how USB mounts could be queried and or if we need to trigger a media scan upfront.

**Comment by AndyScherzinger** [comment]
@andykvakk what happens when/after you reboot your phone? This should trigger a media scan imho which would then also lead to the  media query finding your USB mounted camera folder.

**Comment by andykvakk** [comment]
Reboot does not help. Right now I don't understand anything. Nothing is uploaded instantly. I have downloaded opencamera to be able to specify storage folder exactly, but nothing happens. I must test some more, i don't understand this.

**Comment by AndyScherzinger** [comment]
@andykvakk does it work if you deselect wifiOnly? Are you running on a wifi connection you marked as metered?

**Comment by andykvakk** [comment]
Both tested. No limits on wifi or regular data. Trying to reinstall app, I will get back to you .

**Comment by mr-bolle** [comment]
And if you create a copy of the picture, the upload works? I can't remember in what case the instant upload works yesterday.

**Comment by andykvakk** [comment]
Aha. I copied a picture, then pasted in same folder. Pictures was uploaded immediatly. Using camera or open camera app for taking pictures, is not uploaded

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky please see comments above, this seems to be a service issue.

@andykvakk do your camera folders contain folders? (just asking since Android 7 does have quite the bug there which got resolved in 7.1.1)

**Comment by mr-bolle** [comment]
So you have the same behavior as currently with me, the upload does not start when the image is created.

**Comment by andykvakk** [comment]
@AndyScherzinger , No, There is No folders inside. I tried to remove the camerafolder now, took pictures to recreate the folder, but still No luck.

**Comment by tobiasKaminsky** [comment]
Strange, as far as I know the service does not distinguish who/what creates the file.
The service scans the folder and is triggered if a file is created.

Maybe something ugly made by Samsung ;-)

**Comment by mr-bolle** [comment]
Hi Tobias, 

I have with my Sony Xperia Z3 v6.0.1 the same issue. You can see it on this YouTube video from yesterday. 

Many thanks for your support

**Comment by andykvakk** [comment]
Hei. Just upgraded to 20161102 and now I kan select both camerafolders 😄, but upload still does not start, tested with both save locations.

**Comment by AndyScherzinger** [comment]
Can you try the same test with the Screenshots folder?

**Comment by mr-bolle** [comment]
Picture and Screenshot upload still didn't work with the new version

**Comment by andykvakk** [comment]
Same here

**Comment by tobiasKaminsky** [comment]
Do you see something in the log? 
Logging of new events, starting/stoping observer for folder, ... should be logged.

**Comment by mr-bolle** [comment]
[currentLogScreenshot.txt](https://github.com/nextcloud/android/files/570129/currentLogScreenshot.txt)

now i found the log :)   /storage/xxx/Android/data/com.nextcloud.android.beta/files/nextcloudbeta/log/current.txt

The Screenshot i create 20161103-22:06:51 and a copy from this screenshot i made 2016/11/03 22:07:09. And after that this copy nextcloud upload immediately. I can't find any issues into the log File.

**Comment by daymr** [comment]
Confirm same issue on Verizon galaxy s7 newest firmware... in the meantime using RC app 1.3.1 to sync.. and beta app to view pics...  :(

**Comment by ncyclon** [comment]
Auto upload works fine on stable version, from Google play. But doesn't work on last beta, on Samsung Galaxy s6.

**Comment by mr-bolle** [comment]
Hi, since the last beta 20161123 the instand upload almost works :)
i try with differend Camera Application and check the directory where the pictures are stored

instand upload works
HDR Camera+		/mnt/sdcard/DCIM/OpenCamera/2016-11-26_17-01-19_HDR.jpg
Sony Xperia Stock camera	  /storage/9FCB-96CF/DCIM/100ANDRO/DSC_2609.JPG 
OpenCamera	       /storage/emulated/0/DCIM/OpenCamera/IMG_20161127_202915.jpg

instand upload doesn't work
A Better camera	/storage/emulated/0/DCIM/100ANDRO/20161126_165433_HDR.jpg
Perfectly Clear	/storage/emulated/0/DCIM/PerfectlyClear_Camera/PC_20161126_170637_hdr.jpg

**Comment by AndyScherzinger** [comment]
@mr-bolle thanks for the update. What is the phone/Android version where the upload doesn't work? (Experia / Android 6.0.1 i guess).

**Comment by mr-bolle** [comment]
@AndyScherzinger yes you are right, the test i made with the Sony Xperia Z3 D6633 / Android 6.0.1

**Comment by AndyScherzinger** [comment]
@mr-bolle then the next beta version which will be build tonight might then again break the client since a update from the master branch (for release 1.4.0) basically deactivated the new "Auto upload" for devices on pre Android N which  the next release of the beta will reintroduce so "Auto upload" will be activated for Android Lollipop and up (again).

**Comment by ncyclon** [comment]
@AndyScherzinger confirm broken "Auto upload" on 20161129 with Samsung galaxy s6 edge.

**Comment by AndyScherzinger** [comment]
@ncyclon Do you see anything in the uploads view and/or log regarding photo uploads?

**Comment by ncyclon** [comment]
@AndyScherzinger, nothing in uploads

2016/11/29 12:24:48
Preferences : onSaveInstanceState(Bundle) starting

2016/11/29 12:24:48
Preferences : onStop() ending

2016/11/29 12:24:50
Preferences : onStart() starting

2016/11/29 12:24:50
Preferences : onResume() starting

2016/11/29 12:24:51
com.owncloud.android.files.InstantUploadBroadcastReceiver : Received: android.hardware.action.NEW_PICTURE

2016/11/29 12:24:51
com.owncloud.android.files.InstantUploadBroadcastReceiver : New photo received

2016/11/29 12:24:51
com.owncloud.android.files.InstantUploadBroadcastReceiver : Instant picture upload disabled, ignoring new picture

2016/11/29 12:24:51
com.owncloud.android.files.InstantUploadBroadcastReceiver : OFFICIAL processed: android.hardware.action.NEW_PICTURE

2016/11/29 12:24:57
Preferences : onPause() ending

2016/11/29 12:24:58
LogHistoryActivity : onCreate(Bundle) starting

2016/11/29 12:24:58
LogHistoryActivity : onStart() starting

2016/11/29 12:24:58
LogHistoryActivity : onResume() starting

2016/11/29 12:24:58
Preferences : onSaveInstanceState(Bundle) starting

2016/11/29 12:24:58
Preferences : onStop() ending

**Comment by ncyclon** [comment]
20161215 have this problem

**Comment by mario** [comment]
Please try newest beta:

**Comment by mr-bolle** [comment]
Hi, now I try the  the  branch 2017-02-09. 
And i can say the instant upload function works. 

For the test I use the internal and external storage, and after few seconds the upload starts. And success finishes as well. 

Many thanks

**Comment by tobiasKaminsky** [comment]
Glad to hear @mr-bolle
