### ISSUE TITLE
Autoupload - option: Original file... delete/keep

### ISSUE THREAD

**Issue by Excel1** [nextcloud/android#3722]
### Actual behaviour
install nextcloud
set battery optimization off
log in
set autoupload (pictures)
try to set "original file... delete".
cant change/choose.

### Expected behaviour
install nextcloud
set battery optimization off
log in
set autoupload (pictures)
try to set "original file... delete".
change/choose "Original file... delete"
 
### Steps to reproduce
1. install nextcloud
2. set battery optimization off
3. log in
4. set autoupload
5. choose remot folder
6. try to choose "Original file...
![screenshot_20190307-200627_nextcloud dev](https://user-images.githubusercontent.com/9309456/53982441-3a50c000-4115-11e9-8fbb-f1e2d6401007.jpg)

"

### Environment data
Android version: 9.0

Device model: SM-N950F

Stock or customized system: Stock

Nextcloud app version: 3.5.0 / 3.6.0 / 3.6.2 / 3.7.1

Nextcloud dev app version: 20190815

Nextcloud server version: 15.0.5 / 16.0.0 / 16.0.1 / 16.0.3

### Interesting
with latest iOS on iPhone 5S works

### Changelog
+ Added Nextcloud dev app version
~ Updated App/Server Version
--
~ Updated App/Server Version

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky could this be due to failing permission checks? (in case we can't change this setting due to the checks done, we should probably hide it then?)

**Comment by tobiasKaminsky** [comment]
Ah, indeed this seems to be a custom folder and this might lack write/delete permission.

To avoid confusion, I would not hide this, but show an explaining message, like on move/copy: source folder is read-only; files will only be uploaded.

**Comment by Excel1** [comment]
@tobiasKaminsky 
Yes. I proved it. The option is greyed for pictures in self created folders ( or folders created by galery) on SD Card by automatic upload. (even though the writing permissions are given).

The option is not greyed for pictures in folders on internal storage.

**Comment by feutl** [comment]
I had the same issue, moved everything back to the internal storage of my phone and voila it works again as expected.
Perhaps we could handle the SD Card so the option can also be used with SD card as the NC storage, there are phones out there with quite small internal storage.

**Comment by M4xTheMan** [comment]
I've the same issue on Lineage OS 14.1 / Android 7.1.2 / Samsung Galaxy S7 / Nextcloud Android App 3.8.1 / Nextcloud Server 16.0.4
![image](https://user-images.githubusercontent.com/37311539/73614241-99f16d00-45fd-11ea-855d-1cf52a7d3efe.png)

**Comment by DesktopMasters** [comment]
This issue over a year old.  Any thoughts as to when it will be fixed?  We need the app to request write/delete permission for the SD Card.

**Comment by arsenico13** [comment]
I'm having this same issue (but with manual upload, not auto-upload).

Nextcloud Android App: v.3.15.0
Android 10

**Comment by DesktopMasters** [comment]
Yup I have since switched phones and am STILL having the issue.  I am also on Android 10 now.   Auto or Not Auto still does not work.. why?  Because the app does not give you any way to ask the OS to give permissions to delete.  Other apps do it.  But not NextCloud.  This makes all of NextCloud mostly useless to me.  I have been waiting almost years now for them to add this one simple fix to the app so we can start using it.

**Comment by AlvaroBrey** [comment]
Hello, this should be working with Android 11+ and Nextcloud 3.18.0. Can anyone confirm that?

**Comment by joshtrichards** [comment]
>  Because the app does not give you any way to ask the OS to give permissions to delete. Other apps do it. But not NextCloud. This makes all of NextCloud mostly useless to me. I have been waiting almost years now for them to add this one simple fix to the app so we can start using it.

We do ask for permissions. We certainly do at installation time. But sometimes people pick the Media (read-only) option rather than All Files. There have been some differences in behavior - as well major underlying Android OS permission handling changes for various types of storage - over the time of this Issue being open.

You can manually add the permission too: Unfortunately the "All files access" permission doesn't show up under the normal app permissions in most Android OS variants and to make it more fun is labeled differently. See https://github.com/nextcloud/android/issues/12188#issuecomment-1819562190 for some hints.

In any case, is anywhere here still experiencing this? If not we'll close this out.

**Comment by KDDFKUFEI** [comment]
I am still having this issue on my xiaomi 11TPro OS version: 1.0.6.0.UKDEUXM android version: 14 UKQ 1.231207.002 in the settings it says that i have given all primissions there are to nextcloud but i dont know if i did when i installed

**Comment by KDDFKUFEI** [comment]
reinsalling dindnt fix
