### ISSUE TITLE
Can't build using new install of Ubuntu 18.04

### ISSUE THREAD

**Issue by ben423423n32j14e** [nextcloud/android#4504]
Steps to reproduce:

apt-get install openjdk-11-jdk
git clone https://github.com/nextcloud/android --recursive
cd android
./gradlew clean build

Error:
`android: 'annotationProcessor' dependencies won't be recognized as kapt annotation processors. Please change the configuration name to 'kapt' for these artifacts: 'org.projectlombok:lombok:1.18.8'.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':check'.
> Task with path 'spotbugs' not found in root project 'android'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 0s`

**Comment by cytown** [comment]
Same in command line mode in macos, but works with no issue in android studio, just has cannot found symbols issue in android studio.

**Comment by tobiasKaminsky** [comment]
We never used build, but only subsets of it.
I fixed this via #4597, if you want to give it a try.

**Comment by AndyScherzinger** [comment]
Now merged to master, please give it a go and reopend if still not working. Also any feedback in case it is working is highly appreciated ❤️
