### ISSUE TITLE
Notes fails to connect with HTTP status-code 301 or 302

### ISSUE THREAD

**Issue by danoost** [nextcloud/android#6465]
I believe this started happening when the shift to using Android accounts with the Files app happened, since it seemed that before that, Notes would do its own requests rather than piggy-backing on the Files account.

### Steps to reproduce
1. Successfully authorise account with Files app
2. Open Notes app
3. Attempt to authorise account
4. Observe failure

### Expected behaviour
- Notes should successfully connect

### Actual behaviour
- Notes gives "Oh no - What now? :disappointed:" error. Logs below.

### Can you reproduce this problem on https://try.nextcloud.com?
- Yes, they issue 302 redirects.

### Environment data
Android version: API 29

Device model: Xiaomi Mi 9T (davinci)

Stock or customized system: Stock

Nextcloud app version: Files app 3.12.1, Notes app 2.16.3 (F-droid)

Nextcloud server version: Nextcloud 18.0.6, Notes version 3.6.0

Reverse proxy: Apache, via RewriteRule [L,R=301]. Also occurs when issuing 302 redirects.

Apache and Nextcloud are both running within Docker. The linux client and web interface work properly. My docker image is based off nextcloud:18-apache, approximately following this example: https://github.com/nextcloud/docker/tree/master/.examples/dockerfiles/cron/apache

#### Web server access log
```
apache_1       | <domain>:80 130<ip> - - [12/Jul/2020:22:46:43 +0000] "GET /ocs/v2.php/cloud/capabilities?format=json HTTP/1.1" 301 572 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.12.1"
```

#### Nextcloud log (data/nextcloud.log)
No entries

#### try.nextcloud.com

```
App Version: 2.16.3
App Version Code: 2016003
App Flavor: fdroid

Files App Version Code: 30120190

---

OS Version: 4.14.117-perf+(V11.0.5.0.QFJMIXM)
OS API Level: 29
Device: davinci
Manufacturer: Xiaomi
Model (and Product): Mi 9T (davinci)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 302
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:167)
	at it.niedermann.owncloud.notes.persistence.NotesClientV02.getNotes(NotesClientV02.java:31)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pullRemoteChanges(NoteServerSyncHelper.java:434)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:348)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:306)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.IllegalStateException: 
	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:108)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:134)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

```

#### My host

```
App Version: 2.16.3
App Version Code: 2016003
App Flavor: fdroid

Files App Version Code: 30120190

---

OS Version: 4.14.117-perf+(V11.0.5.0.QFJMIXM)
OS API Level: 29
Device: davinci
Manufacturer: Xiaomi
Model (and Product): Mi 9T (davinci)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 301
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.CapabilitiesClient.getCapabilities(CapabilitiesClient.java:64)
	at it.niedermann.owncloud.notes.main.MainActivity.lambda$null$20$MainActivity(MainActivity.java:791)
	at it.niedermann.owncloud.notes.main.-$$Lambda$MainActivity$4HeEjJCK6xYZ8GdVmxdXI3hCjBw.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.IllegalStateException: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://fakeurl.tld/ocs/v2.php/cloud/capabilities?format=json">here</a>.</p>
</body></html>

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:108)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:134)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

```

**Comment by AndyScherzinger** [comment]
Cc @tobiasKaminsky @David-Development @stefan-niedermann probably move it to SSO repo?

**Comment by stefan-niedermann** [comment]
We had a few of those cases in the past, @tobiasKaminsky always told me, that this has to be a defect server setup and it should not even be possible at this point :smile:

@danoost have you tried to clear the storage of your both apps and reimport your account as [described here](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#i-have-experienced-an-error)?

**Comment by danoost** [comment]
Yes, I did that a few times while I was trying out different status code responses for my HTTP -> HTTPS redirect in Apache, plus another time just now after updating the Notes app to the recent F-droid 2.16.4 version.

**Comment by AndyScherzinger** [comment]
@stefan-niedermann I'd guess/hope that SSO or the http client respectively would deal with 301 or 308 in the way that they update to the new location provided in the header (given the new url is in fact provided by the server).

Any input/feedback @tobiasKaminsky @David-Development ?

**Comment by tobiasKaminsky** [comment]
Is there the possibility that you have an old url? 
Can you try to re-setup Android Files ap with the new url?

**Comment by danoost** [comment]
I've never changed the URL on this instance. I re-setup the Files app a few times in my initial debugging process, as well as trying a try.nextcloud.com instance. I also noticed in the apache logs that the request never makes it to the nextcloud server, so I doubt the issue is to do with any server version updates.

**Comment by stefan-niedermann** [comment]
> the Notes app that isn't handling HTTP redirects properly.

Yep. The Notes app doesn't handle HTTP redirects at all, because the statement was always, that the Files app handles this 🤷‍♂️  Interesting though, that you are able to reproduce the issue with try.nextcloud.com - Because the "Notes" server app isn't installed there.

@danoost have you installed the [server app](https://apps.nextcloud.com/apps/notes)?

**Comment by danoost** [comment]
Ah, that'll explain the different error message I got from try.nextcloud..! But yes, the notes app is installed on the server. It's at version 3.6.0. I'd like to reiterate that the request does not make it to the nextcloud server, since the 301 is served by my reverse proxy server. The android app then never makes another request.

**Comment by stefan-niedermann** [comment]
@tobiasKaminsky i am getting more users complaining about `302` errors, see https://github.com/stefan-niedermann/nextcloud-notes/issues/926 (already re-setup the files app)

**Comment by mar565** [comment]
Ist there a fix for this already?

**Comment by danoost** [comment]
Since the last time I commented, I've switched reverse proxy to HAProxy, updated to Nextcloud 21, and updated Nextcloud Notes to whatever the most recent F-droid version was about two weeks ago, and this is still an issue, identical to how I originally described it. 

This is not an issue with the main nextcloud app, despite claims that they use the same login methods.

**Comment by stefan-niedermann** [comment]
@mar565 & @danoost which version of the [Notes server app](https://apps.nextcloud.com/apps/notes) exactly do you have installed?

**Comment by danoost** [comment]
Server app version 4.0.4 on nextcloud 21.0.2. Brand new app error log below. 

```
App Version: 3.4.4
App Version Code: 3004004
App Flavor: fdroid

Files App Version Code: 30160090

---

OS Version: 4.14.117-perf+(V12.0.8.0.QFJMIXM)
OS API Level: 29
Device: davinci
Manufacturer: Xiaomi
Model (and Product): Mi 9T (davinci)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 301
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.CapabilitiesClient.getCapabilities(CapabilitiesClient.java:32)
	at it.niedermann.owncloud.notes.importaccount.ImportAccountActivity.lambda$null$3$ImportAccountActivity(ImportAccountActivity.java:93)
	at it.niedermann.owncloud.notes.importaccount.-$$Lambda$ImportAccountActivity$b473V25pLTttu0j5h7eieiNY4qY.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.IllegalStateException: 
	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:108)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
```

**Comment by stefan-niedermann** [comment]
You can create a test account and send the credentials to info@niedermann.it. Can't promise anything because i am quite busy, but if i have some time i'll have a look.

**Comment by mar565** [comment]
> @mar565 & @danoost which version of the [Notes server app](https://apps.nextcloud.com/apps/notes) exactly do you have installed?

I recently did a clean nextloud reinstall and didnt even have the notes App installed..
Works Like a charm. Thank you and sorry for the fud..

**Comment by danoost** [comment]
@stefan-niedermann No problem. I'll get them to you tomorrow, it's bedtime where I am :)

**Comment by deathblade666** [comment]
Based off my testing if you setup your reverse proxy config similarly to below if should fix the issue. Please note I am using nginx instead of Apache.

`location / {                                                             
                                                                           
                                                                           
                                                                           
                                                                           
    # Force SSL                                                            
    include conf.d/include/force-ssl.conf;                                 
                                                                           
                                                                           
                                                                           
                                                                           
  # HSTS (ngx_http_headers_module is required) (63072000 seconds = 2 years)
  add_header Strict-Transport-Security "max-age=63072000; preload" always; 
                                                                           
    proxy_buffering off;                                                   
                                                                           
                                                                           
                                                                           
                                                                           
    proxy_set_header Upgrade $http_upgrade;                                
    proxy_set_header Connection $http_connection;                          
    proxy_http_version 1.1;                                                
                                                                           
                                                                           
    # Proxy!                                                               
    include conf.d/include/proxy.conf;                                     
  }`

**Comment by tdfischer** [comment]
Is the official response from the project that this is a server configuration error?? For real?

How can the app still not handle a basic 301 redirect? I can't use the Notes app for this same exact bug. 100% reproducable on my stock fedora nextcloud install.
