### ISSUE TITLE
Beta (gh) logging not working

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/android#654]
### Actual behaviour
- In the log, I'm only seeing entries for 06/02 (2017) and have done for several days. Trying to delete them looks like it works, but they're back when I return to the log page.

### Expected behaviour
- Up to date logs

### Environment data
Android version: Everything presumably from build 06022017

Device model: Vodafone VFD 900

Stock or customized system: Stock

Nextcloud app version: 13022017

Nextcloud server version: 11.0.1

**Comment by jasonbayton** [comment]
@tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
Fixed. Please verify in next beta.

**Comment by tobiasKaminsky** [comment]
@jasonbayton can you test if it is working now as expected?

**Comment by jasonbayton** [comment]
Afraid not, just grabbed the latest.apk again and still crashing.

**Comment by tobiasKaminsky** [comment]
So...Now really there is a new version.

**Comment by jasonbayton** [comment]
Well, I've done some uploads and whatnot, it's not showing anything in logs at the moment.

**Comment by tobiasKaminsky** [comment]
@jasonbayton https://kaminsky.me/nc-nightly/latest.apk here is a new dev version

**Comment by jasonbayton** [comment]
Logs work with that version 👍

**Comment by tobiasKaminsky** [comment]
Finally :-)
Thank you!
