### ISSUE TITLE
[3.13.0 RC*] Filedownload is broken: File/s got "ServernameCloudnameNull" as local filename

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/android#6589]
* Client NC Android 3.13.0 RC 1/2/3

When I download (several mobile phones) a file or a folder with files, this does not work. All downloads result in filename like "ServernameCloudnameNull" as local filename.

Regression which makes this version of the Nextcloud client unusable.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky is this related to the E2EE change and the fix you did for the upcoming RC2?

**Comment by tobiasKaminsky** [comment]
This is fixed via #6557

**Comment by Wikinaut** [comment]
This regression problem is still present in 3.13.0 RC3 , renders any download via the App _unusable_.

**Comment by tobiasKaminsky** [comment]
@Wikinaut is this also happening for new files? 
Can you remove an old file via delete -> local only and then re-download it?

**Comment by Wikinaut** [comment]
@tobiasKaminsky 
>  Can you remove an old file via delete -> local only and then re-download it?

I confirm, that this works.

**Comment by tobiasKaminsky** [comment]
Glad to hear.
It might also work if you go into the folder and pull down to force refresh.

**Comment by Wikinaut** [comment]
I don't see a Refresh icon.

**Comment by Wikinaut** [comment]
Negativ. This does not work. Download of a file again results in a file SomethingNull.

**Comment by AndyScherzinger** [comment]
@Wikinaut did you do a pull-to-refresh beforehand on the folder containing the file you download? This is (from what I understand) what @tobiasKaminsky means, your folder is in a corrupt state (which I think he fixed with the latest RC) but the data corruptions is fixed via a folder refresh. At least this is my interpretation. As for "I don't see a Refresh icon." there is non, you need to do a pull-down-to-refresh on the list view.

**Comment by Wikinaut** [comment]
What exactly do you mena by "pull-to-refresh"?
What do you mean by pull-down-to-refresh?

**Comment by Wikinaut** [comment]
I see "synchronize" on many of my files (a red x is shown on these), which were not locally present, this is incorrect in my view. When I now click "synchronize", the xxxxNull file is the result.

This function is not buggy.

**Comment by Wikinaut** [comment]
And synchronizing a folder does not work.

**Comment by AndyScherzinger** [comment]
https://en.wikipedia.org/wiki/Pull-to-refresh

In short: put your finger at the top of the files list and swipe-downwards. 

_If_ you don't do this any files will still not be handled properly. Synchronize is a "download all". 

If the pull works you should see a little circle with an error animating a refresh processing.

**Comment by tobiasKaminsky** [comment]
A bit background: if you do not sync metadata for a folder, then the app will still download it to the wrong place.
So either go into a folder where you have never been before, and test a download there.
Or if you have a folder which was previously synced, please use above refresh method to get new metadata and then download any file.

**Comment by Wikinaut** [comment]
I did everything as explained by you. I have new obsersavtions which confirm my severe concerns that a huge bug is lurking as a regression which you overlooked so far. At the moment, I can only tell you that I

* did the pull-to-refresh
* when downloading any arbitrary file, the download results in a single file "username@mynextcloudserverNull in the Android Internal Memory inside the Nextcloud App folder but outside my user@nextcloud folder
* even deletion of a subfolder like "pdf" inside the Nextcloud App does not help
* even deleteion of the Null file does not help
* the only help is this cycle: 1. download 2. delete locally 3. download a second time - this makes the file resulting as file in the wrong subfolder.

Again: something is really wrong with this 3.13.0 RC1, 2, 3.

**Comment by tobiasKaminsky** [comment]
>     * when downloading any arbitrary file, the download results in a single file "username@mynextcloudserverNull in the Android Internal Memory inside the Nextcloud App folder but outside my user@nextcloud folder

can you explain this a bit more? Maybe with absolute paths?

**Comment by tobiasKaminsky** [comment]
Can you try to add another account, which is then a clean database for this account?

**Comment by tobiasKaminsky** [comment]
Please try this
- upgrade to RC4
- Android -> setting -> app -> Nextcloud -> clean cache
- open up app and see if it still happens

**Comment by Wikinaut** [comment]
@tobiasKaminsky Already on RC4 - cleared app cache - same problem.

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky Already on RC4 - cleared app cache - same problem.

That is indeed totally strange.
Are you sure that this is not just an old file that is leftover? 
Can you delete this file, then download another file?

If this does not help, can you uninstall and re-install the app? Sorry for the trouble… :-(
And thanks for being beta tester :+1:

**Comment by tobiasKaminsky** [comment]
Should be fixed, if not please re-open.

**Comment by Wikinaut** [comment]
I decided to deinstall the beta and reinstall the App, however, reupload of my images started, so I had to re-configure every setting for the upload. (There should be a _global_ upload setting-switch to prevent upload of existing images, can be thousands in many directories.)
