### ISSUE TITLE
Sometimes getting a conflict on new files in automatic upload

### ISSUE THREAD

**Issue by PVince81** [nextcloud/android#7811]
### Steps to reproduce
0. Enable automatic upload for pictures
1. Go outside and offline, take a bunch of pictures of beautiful nature in the cold of winter
2. Go back home and enable wifi
3. Wait for sync
4. Be unlucky :four_leaf_clover: 

### Expected behaviour
All pics uploaded

### Actual behaviour
When astral bodies are aligned in some parallel universe, a conflict dialog appears on one of the new pictures to be uploaded, asking me if I want to overwrite it. The picture did not exist on the server before.

### Versions
Nextcloud app 3.14.1
Android 10
Nokia 6.1
Nextcloud 20.0.4 running on a Raspberry pi 4 with 64-bit Raspbian

### Notes

This is not reproducible consistently but happened to me a few times by surprise.
I did not observe a pattern yet but also failed to take note of the picture names, so I don't have any debug info.
Still, I wanted to report this and will keep it updated if this happens again.

When uploading, what are the criteria that prompt the client to trigger a conflict dialog ?

**Comment by rttmax** [comment]
+1

**Comment by PVince81** [comment]
If anyone else has some logs, feel free to post it also.

I think what we should do whenever a conflict happens next:

1. Take note of the file name that got the conflict
2. Check the web server access log and grep for that file name. Some status codes there might tell us whether the conflict was triggered by an unexpected status code.
3. Check nextcloud.log for that file name also
4. Export the Android logs and grep for that name, too
5. Post the log snippets here

**Comment by piknew** [comment]
https://github.com/nextcloud/android/issues/7944

**Comment by PVince81** [comment]
this hasn't happened to me any more, not sure if the issue got fixed in an update or if I was just lucky

**Comment by PVince81** [comment]
unless anyone else has seen this in the past month or so, I think we can close this issue

**Comment by szaimen** [comment]
I sometimes still experience this especially with big video files.
@PVince81 did you try the automatic upload with big video files, too?

**Comment by PVince81** [comment]
> I sometimes still experience this especially with big video files.
> @PVince81 did you try the automatic upload with big video files, too?

Yes, usually with about 3 minutes of video or so. It wasn't an issue.
But when I did the sync is done in my LAN as my Nextcloud is in the LAN, so it's rather fast.

Not sure if the conflict could be due to a resumed upload after timeout or something.
What about you @szaimen ?

**Comment by szaimen** [comment]
@PVince81, thanks for the fast respond!

It seems like videos get successfully uploaded but the Nextcloud app doesn't register them as successfully uploaded and tries to upload them again, then sees that the same file is already uploaded -> hence there is a new conflict. At least this happens reproducible with big video files on my instance. (not only automatic upload but also manual triggered upload)

Here is a logcat output:
[logcatOutput.txt](https://github.com/nextcloud/android/files/6133720/logcatOutput.txt)
Note: I've substituted my domain through `example.com`

**Comment by szaimen** [comment]
> Here is a logcat output:
> [logcatOutput.txt](https://github.com/nextcloud/android/files/6133720/logcatOutput.txt)
> Note: I've substituted my domain through `example.com`

Maybe @tobiasKaminsky can extract some useful info out of this?

**Comment by tobiasKaminsky** [comment]
@szaimen your bug is the same as #5609, thus closing it here, as the conflict dialog is then just a result of the problem, but not the cause.

**Comment by PVince81** [comment]
the conflict dialog has disappeared, however some files are still getting uploaded a second time
I'll keep an eye and raise a separate ticket for this
