### ISSUE TITLE
Photos just uploaded by Auto Upload then appear on device with size zero

### ISSUE THREAD

**Issue by roger-whittaker** [nextcloud/android#801]
### Actual behaviour

I take a photo.  It gets uploaded.  Later, I navigate on the same device to the directory under InstantUpload where the photo should be.  I see a large warning triangle and text that says that the image can not be shown.

If I check in the local folder where the file should be, I see that a file with the correct filename exists, but it has size zero bytes.

If I delete that file locally, the actual file can be downloaded from the server and viewed normally.

### Expected behaviour

I would expect the photo to get downloaded from the server and displayed normally.

 
### Steps to reproduce
1.  Take a photo
2.  Wait for long enough for the auto upload to happen
3.  Check in the expected folder.

### Environment data
Android version: 7.0 / OxygenOS 4.0.3

Device model: Oneplus 3

Stock or customized system:

Nextcloud app version: 1.4.2

Nextcloud server version: 11.0.1

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

**Comment by roger-whittaker** [comment]
![screenshot_20170404-134337](https://cloud.githubusercontent.com/assets/26901568/24660692/195bccf6-1948-11e7-8ce4-a35b5b4bdb66.png)

**Comment by mario** [comment]
Should be solved.

**Comment by roger-whittaker** [comment]
It still happens with Android app version 1.4.3 and Nextcloud 12 server.

**Comment by mario** [comment]
This is solved in the master, and will be in 1.5 release. 1.4.2 was just about fixing login for V12.
