### ISSUE TITLE
Trying to look up user to share a file with results in "Server not found"

### ISSUE THREAD

**Issue by jalbstmeijer** [nextcloud/android#8890]
### Steps to reproduce
1. select the share icon behind a filename
2. select "share" in app selection popup
3. start typing a string in the search field and see the error "Server no found"

### Expected behaviour
- Users to select from should appear

### Actual behaviour
- On the client I get "Server not found"
- On the server I get: GET /ocs/v2.php/apps/files_sharing/api/v1/sharees?format=json&itemType=file&search=i&page=1&perPage=50&lookup=false HTTP/1.1" 404 1111 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.17.0

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version: 22.1.0

Nextcloud server version: 3.17

Reverse proxy: nginx

#### Web server error log
```
[24/Aug/2021:08:07:16 +0000] "GET /ocs/v2.php/apps/files_sharing/api/v1/sharees?format=json&itemType=file&search=i&page=1&perPage=50&lookup=false HTTP/1.1" 404 1111 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.17.0"
```

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"hgRGNtx2c6JMHj5OwFoJ","level":3,"time":"2021-08-24T08:19:27+00:00","remoteAddr":"xxx","user":"xxx","app":"no app in context","method":"GET","url":"/ocs/v2.php/apps/files_sharing/api/v1/sharees?format=json&itemType=file&search=g&page=1&perPage=50&lookup=false","message":"in_array() expects parameter 2 to be array, null given","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.17.0","version":"22.1.0.1","exception":{"Exception":"Exception","Message":"in_array() expects parameter 2 to be array, null given","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareesAPIController"},"search"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files_Sharing\\Controller\\ShareesAPIController","search",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"ocs.files_sharing.ShareesAPI.search"}]},{"file":"/var/www/html/ocs/v1.php","line":62,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/files_sharing/api/v1/sharees"]},{"file":"/var/www/html/ocs/v2.php","line":23,"args":["/var/www/html/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":158,"Previous":{"Exception":"TypeError","Message":"in_array() expects parameter 2 to be array, null given","Code":0,"Trace":[{"file":"/var/www/html/apps/circles/lib/Collaboration/v2/CollaboratorSearchPlugin.php","line":101,"function":"in_array","args":[10,null]},{"file":"/var/www/html/lib/private/Collaboration/Collaborators/Search.php","line":72,"function":"search","class":"OCA\\Circles\\Collaboration\\v2\\CollaboratorSearchPlugin","type":"->","args":["g",25,0,{"__class__":"OC\\Collaboration\\Collaborators\\SearchResult"}]},{"file":"/var/www/html/apps/files_sharing/lib/Controller/ShareesAPIController.php","line":228,"function":"search","class":"OC\\Collaboration\\Collaborators\\Search","type":"->","args":["g",[0,1,4,6,7,"And 3 more entries, set log level to debug to see all entries"],false,25,0]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"search","class":"OCA\\Files_Sharing\\Controller\\ShareesAPIController","type":"->","args":["g","file",1,25,null,false]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareesAPIController"},"search"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareesAPIController"},"search"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files_Sharing\\Controller\\ShareesAPIController","search",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"ocs.files_sharing.ShareesAPI.search"}]},{"file":"/var/www/html/ocs/v1.php","line":62,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/files_sharing/api/v1/sharees"]},{"file":"/var/www/html/ocs/v2.php","line":23,"args":["/var/www/html/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/apps/circles/lib/Collaboration/v2/CollaboratorSearchPlugin.php","Line":101},"CustomMessage":"--"}}

```

**Comment by jalbstmeijer** [comment]
For me this issue was solved.

**Comment by MhhhxX** [comment]
I still have this issue with Nextcloud server 22.2.3 and Nextcloud Android 3.18.0

**Comment by AlvaroBrey** [comment]
> I still have this issue with Nextcloud server 22.2.3 and Nextcloud Android 3.18.0

@MhhhxX do you have the "Server not found" issue only when looking for sharees, or at more parts throughout the app?

**Comment by MhhhxX** [comment]
For now I only noticed it when looking for shares

**Comment by MhhhxX** [comment]
The issue is now solved for me. The search works now.
