### ISSUE TITLE
calendar backup not working

### ISSUE THREAD

**Issue by henningaround** [nextcloud/android#9527]
I've enabled daily contacts and calendar backup.

Backup of contacts is working for a long time now and it's backup up all contacts to a single .vcf file in .Contacts-Backup on the nextcloud server home of the user (I would like to specify the folder but that's another topic :) )

However the newly introduced calendar backup doesn't do anything. Or where should I find the backup files?

It's Nextcloud files for android 3.18.0 on Android 11.

Best
Henning

**Comment by Jerome-Herbinet** [comment]
Same for me ; The contact backup feature works great (I have been using it for years). I have noticed that the backup files are stored in a hidden "Contacts-Backup" folder.
On the other hand, the calendar backup seams not to work. I imagine that if it worked, a hidden backup folder would be available (and would contain dated ics files, for each calendar).

**Comment by gryban1** [comment]
I have 4 calendars and its only backing up 3 of them. The "main" calendar "Termine" is not backed up.

**Comment by gryban1** [comment]
The backup of my calendar "Termine" is now working. Don't know why.

**Comment by henningaround** [comment]
Nothing has changed here so far. I still only have backup files of contacts in the /.Contacts-Backup folder.

**Comment by henningaround** [comment]
> I use DAVx^5 to sync my calendars, Nextcloud would only backup calendars from other accounts, not the ones saved on my server. It also saved the calendars on my own server two month ago but stopped suddenly, I see this in the files in the .calendar-backup folder.

I do also you DAVx^5. But the directory ".calendar-backup" doesn't show up.

**Comment by Simplenuity** [comment]
Here similar:

* calendar backup not working at all

* contacts backup works only manually (via "Back up now" button) - while "Restore backup" giving me the possibility to choose any date from a certain date on (April 2022, can't remember whether I activated the backup back then)

System info:
Nextcloud Android app: 3.20.3
Android 10 (MIUI Global 12.0.1)

**Comment by Jobode** [comment]
I also have the same error. The contacts are backed up in the folder .Contacts-Backup. 
But my calendars are not backed up. There is also NO folder .calendar.Backup. Even if I create it manually, nothing happens. 
The calendar backup just does not work.

System info:
Nexcloud version 24.0.2 and DavX5 version 4.2.2-ose. My phone is running Nextcloud Android App 3.20.3.

**Comment by ljep42** [comment]
Also having issues...

Android 12, nextcloud 3.20.3 

- Calendar backup does not work
- Contacts backup used to work but now does not. I tried toggling the slider but still doesn't work. Manual back up does work.

May try reinstalling the app if I continue to have issues with contacts but any suggestions are appreciated.

**Comment by svenb1234** [comment]
How can I check whether this works in 3.21.1? Clicking on "backup now" creates a new file in .contacts-backup but nothing else, although "backup calendar" is enabled. No error message either. 

The activity tab does also only show the vcf file and nothing else.

**Comment by Jerome-Herbinet** [comment]
> How can I check whether this works in 3.21.1? Clicking on "backup now" creates a new file in .contacts-backup but nothing else, although "backup calendar" is enabled. No error message either.
> 
> The activity tab does also only show the vcf file and nothing else.

Same.

**Comment by svenb1234** [comment]
I have another phone where it worked. With that phone the backup was enabled after the update to 3.21.1

**Comment by AlvaroBrey** [comment]
> How can I check whether this works in 3.21.1? Clicking on "backup now" creates a new file in .contacts-backup but nothing else, although "backup calendar" is enabled. No error message either.
> 
> The activity tab does also only show the vcf file and nothing else.

Try removing and re-granting calendar permissions for the app

**Comment by Simplenuity** [comment]
> > How can I check whether this works in 3.21.1? Clicking on "backup now" creates a new file in .contacts-backup but nothing else, although "backup calendar" is enabled. No error message either.
> > The activity tab does also only show the vcf file and nothing else.
> 
> Try removing and re-granting calendar permissions for the app

I tried this to no avail. Starting a manual backup only created a backup of the contacts.

**Comment by Jerome-Herbinet** [comment]
> > > How can I check whether this works in 3.21.1? Clicking on "backup now" creates a new file in .contacts-backup but nothing else, although "backup calendar" is enabled. No error message either.
> > > The activity tab does also only show the vcf file and nothing else.
> > 
> > 
> > Try removing and re-granting calendar permissions for the app
> 
> I tried this to no avail. Starting a manual backup only created a backup of the contacts.

Same (still no calendar backup after disabling and enabling it)

**Comment by AlvaroBrey** [comment]
@Jerome-Herbinet @Simplenuity  can either of you post some logs?

Instructions here: https://github.com/nextcloud/android#getting-debug-info-via-logcat-mag

Feel free to search and replace the server URL, username and other file names in the output.Can either of you post some logs?

**Comment by Jerome-Herbinet** [comment]
[logcatOutput.txt](https://github.com/nextcloud/android/files/9443374/logcatOutput.txt)

**Comment by Jerome-Herbinet** [comment]
> @Jerome-Herbinet @Simplenuity can either of you post some logs?
> 
> Instructions here: https://github.com/nextcloud/android#getting-debug-info-via-logcat-mag
> 
> Feel free to search and replace the server URL, username and other file names in the output.

@AlvaroBrey 
[logcatOutput.txt](https://github.com/nextcloud/android/files/9443378/logcatOutput.txt)

**Comment by AlvaroBrey** [comment]
From the above log:

```java
08-29 11:16:41.606 14654 14672 E WM-WorkerWrapper: Work [ id=a948a45c-10cf-49c1-bb5d-0fe9bda45e1c, tags={ name:immediate_calendar_backup <account id> timestamp:1661764601420, *, user:<user id>, com.nextcloud.client.jobs.CalendarBackupWork } ] failed because it threw an exception/error
08-29 11:16:41.606 14654 14672 E WM-WorkerWrapper: java.util.concurrent.ExecutionException: net.fortuna.ical4j.model.ValidationException: Calendar must contain at least one component
08-29 11:16:41.606 14654 14672 E WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
08-29 11:16:41.606 14654 14672 E WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
08-29 11:16:41.606 14654 14672 E WM-WorkerWrapper: 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:311)
08-29 11:16:41.606 14654 14672 E WM-WorkerWrapper: 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
08-29 11:16:41.606 14654 14672 E WM-WorkerWrapper: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-29 11:16:41.606 14654 14672 E WM-WorkerWrapper: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-29 11:16:41.606 14654 14672 E WM-WorkerWrapper: 	at java.lang.Thread.run(Thread.java:920)
08-29 11:16:41.606 14654 14672 E WM-WorkerWrapper: Caused by: net.fortuna.ical4j.model.ValidationException: Calendar must contain at least one component
08-29 11:16:41.606 14654 14672 E WM-WorkerWrapper: 	at net.fortuna.ical4j.model.Calendar.validate(Calendar.java:287)
08-29 11:16:41.606 14654 14672 E WM-WorkerWrapper: 	at net.fortuna.ical4j.model.Calendar.validate(Calendar.java:257)
08-29 11:16:41.606 14654 14672 E WM-WorkerWrapper: 	at net.fortuna.ical4j.data.CalendarOutputter.output(CalendarOutputter.java:96)
08-29 11:16:41.606 14654 14672 E WM-WorkerWrapper: 	at net.fortuna.ical4j.data.CalendarOutputter.output(CalendarOutputter.java:83)
08-29 11:16:41.606 14654 14672 E WM-WorkerWrapper: 	at third_parties.sufficientlysecure.SaveCalendar.start(SaveCalendar.java:193)
08-29 11:16:41.606 14654 14672 E WM-WorkerWrapper: 	at com.nextcloud.client.jobs.CalendarBackupWork.doWork(CalendarBackupWork.kt:69)
08-29 11:16:41.606 14654 14672 E WM-WorkerWrapper: 	at androidx.work.Worker$1.run(Worker.java:86)
```
I have no idea what `Calendar must contain at least one component`, I'll try to figure it out.

**Comment by Jerome-Herbinet** [comment]
> > @Jerome-Herbinet @Simplenuity can either of you post some logs?
> > Instructions here: https://github.com/nextcloud/android#getting-debug-info-via-logcat-mag
> > Feel free to search and replace the server URL, username and other file names in the output.
> 
> @AlvaroBrey [logcatOutput.txt](https://github.com/nextcloud/android/files/9443378/logcatOutput.txt)

@AlvaroBrey, this is strange ... so, I have just made sure that none of my 9 calendars are empty. They all contain events.

**Comment by Simplenuity** [comment]
> @Jerome-Herbinet @Simplenuity can either of you post some logs?
> 
> Instructions here: https://github.com/nextcloud/android#getting-debug-info-via-logcat-mag
> 
> Feel free to search and replace the server URL, username and other file names in the output.

Sorry for the delay, @AlvaroBrey 
Would it still be helpful to provide some logs?

**Comment by AlvaroBrey** [comment]
@Simplenuity yes please, the most probable thing is that it's the same error as the one above, but it may be the case that it's not

**Comment by Simplenuity** [comment]
@AlvaroBrey, please find logcat attached
[logcat.txt](https://github.com/nextcloud/android/files/9557093/logcat.txt)

**Comment by Kalytis** [comment]
Hi, calendar backup still doesn't work for me either.

Need logs ?

**Comment by Kalytis** [comment]
![Screenshot_20221022-143039](https://user-images.githubusercontent.com/31107370/197339138-a4904d9b-69dc-4225-8d97-fad8d5354516.jpg)
Fixed ! 🔥

**Comment by strelitzer** [comment]
The bug has apparently been fixed at least since v3.22.0. 👍🏻

**Comment by repsorp** [comment]
Still not working here
Android 12
Nextcloud client 3.22.1

Not all calendars are saved, some are still missing

**Comment by Jerome-Herbinet** [comment]
**Still not working for me :**
Android 12 on a Xiami 11T
Nextcloud Android client : 3.22.1
Nextcloud server : 24.0.6
Calendar app : 3.5.1
Contacts app : 4.2.2

**Comment by Kalytis** [comment]
@repsorp @Jerome-Herbinet Have you tried going into the settings and activating calendar backup ? It seems to reset with 3.22

**Comment by Jerome-Herbinet** [comment]
> @repsorp @Jerome-Herbinet Have you tried going into the settings and activating calendar backup ? It seems to reset with 3.22

Already tried before writing my comment 😟

**Comment by repsorp** [comment]
> > @repsorp @Jerome-Herbinet Have you tried going into the settings and activating calendar backup ? It seems to reset with 3.22
> 
> Already tried before writing my comment 😟

Yep... Same

**Comment by henningaround** [comment]
Yes it resets. But once you re-enabled it it backups only my personal calendar with birthdays. Not the 12+ calendars I'm using the most.

**Comment by repsorp** [comment]
Does not work here either
My main calendar (size 1.5 MB) is still missing

Pixel4
Android 11
Nextcloud 3.22.1

`10-24 05:19:16.715 I/ActivityTaskManager(1536): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity bnds=[838,990][1038,1314]} from uid 10237
10-24 05:19:17.121 D/ArtManagerInternalImpl(1536): /data/misc/iorapd/com.nextcloud.client/30220190/com.owncloud.android.ui.activity.FileDisplayActivity/compiled_traces/compiled_trace.pb doesn't exist
10-24 05:19:17.123 I/ActivityTaskManager(1536): Displayed com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity: +398ms
10-24 05:19:17.208 I/GoogleInputMethodService(22332): GoogleInputMethodService.onStartInput():1960 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x0 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=com.nextcloud.client fieldId=-1 fieldName=null extras=null}, false)
10-24 05:19:17.747 I/UpdateOCVersionOperation(15698): Check for update of Nextcloud server version at https://xxx.com/remote.php/dav/files/xxx: Operation finished with HTTP status code -1 (success)
10-24 05:19:17.797 I/UpdateOCVersionOperation(15698): Check for update of Nextcloud server version at https://xxx.com/remote.php/dav/files/xxx: Operation finished with HTTP status code -1 (success)
10-24 05:19:21.594 I/ActivityTaskManager(1536): START u0 {cmp=com.nextcloud.client/com.owncloud.android.ui.activity.SettingsActivity} from uid 10284
10-24 05:19:21.728 I/ActivityTaskManager(1536): Displayed com.nextcloud.client/com.owncloud.android.ui.activity.SettingsActivity: +133ms
10-24 05:19:21.766 I/GoogleInputMethodService(22332): GoogleInputMethodService.onStartInput():1960 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x0 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=com.nextcloud.client fieldId=-1 fieldName=null extras=null}, false)
10-24 05:19:23.855 I/ActivityTaskManager(1536): START u0 {cmp=com.nextcloud.client/com.owncloud.android.ui.activity.ContactsPreferenceActivity (has extras)} from uid 10284
10-24 05:19:23.985 I/GoogleInputMethodService(22332): GoogleInputMethodService.onStartInput():1960 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x0 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=com.nextcloud.client fieldId=-1 fieldName=null extras=null}, false)
10-24 05:19:25.884 I/ICS_SaveCalendar(15698): Save id 1 to file /data/user/0/com.nextcloud.client/cache/Test_2022-10-24_05-19-25.ics
10-24 05:19:26.018 I/ICS_SaveCalendar(15698): Save id 2 to file /data/user/0/com.nextcloud.client/cache/Moon/Astro_2022-10-24_05-19-26.ics
10-24 05:19:26.086 E/WM-WorkerWrapper(15698): Work [ id=a05649ef-6c9a-422c-be4e-c794c8afd7a7, tags={ name:immediate_calendar_backup xxx@xxx.com, *, user:xxx@xxx.com, timestamp:1666581565757, com.nextcloud.client.jobs.CalendarBackupWork } ] failed because it threw an exception/error
10-24 05:19:26.086 E/WM-WorkerWrapper(15698): java.util.concurrent.ExecutionException: java.io.FileNotFoundException: /data/user/0/com.nextcloud.client/cache/Moon/Astro_2022-10-24_05-19-26.ics: open failed: ENOENT (No such file or directory)
10-24 05:19:26.086 E/WM-WorkerWrapper(15698): Caused by: java.io.FileNotFoundException: /data/user/0/com.nextcloud.client/cache/Moon/Astro_2022-10-24_05-19-26.ics: open failed: ENOENT (No such file or directory)
10-24 05:19:26.086 E/WM-WorkerWrapper(15698): 	at com.nextcloud.client.jobs.CalendarBackupWork.doWork(CalendarBackupWork.kt:68)
10-24 05:19:26.087 I/WM-WorkerWrapper(15698): Worker result FAILURE for Work [ id=a05649ef-6c9a-422c-be4e-c794c8afd7a7, tags={ name:immediate_calendar_backup xxx@xxx.com, *, user:xxx@xxx.com, timestamp:1666581565757, com.nextcloud.client.jobs.CalendarBackupWork } ]
10-24 05:19:26.222 D/NotificationService(1536): 0|com.nextcloud.client|1000000|null|10284: granting content://settings/system/notification_sound
10-24 05:19:26.226 D/NotificationService(1536): 0|com.nextcloud.client|1000000|null|10284: granting content://settings/system/notification_sound
10-24 05:19:26.247 D/InterruptionStateProvider(2114): No bubble up: not allowed to bubble: 0|com.nextcloud.client|1000000|null|10284
10-24 05:19:26.248 D/InterruptionStateProvider(2114): No heads up: unimportant notification: 0|com.nextcloud.client|1000000|null|10284
10-24 05:19:26.255 D/InterruptionStateProvider(2114): No bubble up: not allowed to bubble: 0|com.nextcloud.client|1000000|null|10284
10-24 05:19:26.255 D/InterruptionStateProvider(2114): No heads up: unimportant notification: 0|com.nextcloud.client|1000000|null|10284
10-24 05:19:29.051 I/UploadFileOperation(15698): Upload of /data/user/0/com.nextcloud.client/cache/Test_2022-10-24_05-19-25.ics to /.Calendar-Backup/Test_2022-10-24_05-19-25.ics: Operation finished with HTTP status code 201 (success)
10-24 05:19:35.732 I/GoogleInputMethodService(22332): GoogleInputMethodService.onStartInput():1960 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x0 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=com.nextcloud.client fieldId=-1 fieldName=null extras=null}, false)
10-24 05:19:36.849 W/ActivityTaskManager(1536): Duplicate finish request for r=ActivityRecord{1f767f9 u0 com.nextcloud.client/com.owncloud.android.ui.activity.SettingsActivity t1648 f}}
10-24 05:19:37.002 I/GoogleInputMethodService(22332): GoogleInputMethodService.onStartInput():1960 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x0 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=com.nextcloud.client fieldId=-1 fieldName=null extras=null}, false)
10-24 05:19:37.716 I/UpdateOCVersionOperation(15698): Check for update of Nextcloud server version at https://xxx.com/remote.php/dav/files/xxx: Operation finished with HTTP status code -1 (success)`

**Comment by snetat** [comment]
The same error still exists

Poco F3, Android 12, Nextcloud App 3.22.2, ´Nextcloud 24.0.6

`10-25 09:32:21.853 31054 31253 I ICS_SaveCalendar: Save id 1 to file /data/user/0/com.nextcloud.client/cache/calendar_displayname_local_2022-10-25_09-32-21.ics
10-25 09:32:21.860 31054 31096 E WM-WorkerWrapper: Work [ id=78c7c770-3d29-4251-9c6d-00523855c838, tags={ timestamp:1666683141799, name:immediate_calendar_backup xxxxxx.xxxxxl@xxxx.xx@xxxx.xxx, *, user:xxxxxx.xxxxxl@xxxx.xx@xxxx.xxx, com.nextcloud.client.jobs.CalendarBackupWork } ] failed because it threw an exception/error
10-25 09:32:21.860 31054 31096 E WM-WorkerWrapper: java.util.concurrent.ExecutionException: net.fortuna.ical4j.validate.ValidationException: Calendar must contain at least one component
`

**Comment by snetat** [comment]
@AlvaroBrey

YES, with qa apk it works as expected.

**Comment by Jerome-Herbinet** [comment]
> @Jerome-Herbinet can you try the QA APK in https://github.com/nextcloud/android/pull/10928 and see if that backs up your calendars correctly?

@AlvaroBrey, the QA APK does have exactly the same behavior as my 3.22.2.

**Comment by AlvaroBrey** [comment]
Dangit, I tried to reproduce it yesterday but I can't figure out how to create a calendar that lets me reproduce the error. As far as I understand, it really should only trigger that if a calendar is empty, and all my tests worked :(

For those of you that have some calendars working but others not working, can you think of anything that makes the working ones different from the non-working ones? Examples of possible things:
- Special characters in calendar names
- Different account
- Handled by different app
etc etc

**Comment by ristein** [comment]
@AlvaroBrey 
I have eight calendars, one private, two shared with group, one shared with group and public, one shared public, two from another NC-user shared to me via group.
The only calendar that gets backed up daily is the alphabetically first by name.
I just renamed one existing and created a new calendar both with names alphabetically before the one getting backed up, but a manual "backup now" via nextcloud-app still copies the one it always does.
App version 3.22.1 via F-Droid
Hub version 3 (25.0.0)

**Comment by repsorp** [comment]
> Dangit, I tried to reproduce it yesterday but I can't figure out how to create a calendar that lets me reproduce the error. As far as I understand, it really should only trigger that if a calendar is empty, and all my tests worked :(
> 
> For those of you that have some calendars working but others not working, can you think of anything that makes the working ones different from the non-working ones? Examples of possible things:
> 
> * Special characters in calendar names
> * Different account
> * Handled by different app
>   etc etc

No special characters in calendar names
Not different account
Not handled by different app

Below 3 test versions of calendars that do not appear in nextcloud android backup

[calendar_test.zip](https://github.com/nextcloud/android/files/9868849/calendar_test.zip)

**Comment by strelitzer** [comment]
Before v3.22 of Nextcloud client, calendar backup did not work at all and contacts backup worked regularly. With v3.22.0 calendar **and** contacts backup worked exactly twice. Now with v3.22.2 _neither calendar nor contacts_ backup works.

**Comment by tobiasKaminsky** [comment]
@AlvaroBrey when you work on this, please also check https://github.com/nextcloud/android/issues/11016?notification_referrer_id=NT_kwDOAFkQN7I0NzkzNDc0ODg1OjU4MzY4NTU&notifications_query=is%3Aunread

**Comment by AlvaroBrey** [comment]
Can any of the affected users check if they can select/export the affected calendars with this app? https://github.com/SufficientlySecure/calendar-import-export

**Comment by ristein** [comment]
@AlvaroBrey 
I can select and export any calendar.
But the one that gets backed up by nextcloud is the one selected by default and has the number (1)

**Comment by AlvaroBrey** [comment]
@ristein if you can, please test the following APK: https://github.com/nextcloud/android/pull/10928#issuecomment-1322410744 and provide logs

**Comment by ristein** [comment]
@AlvaroBrey 
it's working. I clicked on "backup now" and I got a file for each calendar (except empty ones) in my backup-dir.

btw: I didn't setup sync via next cloud app but installed davx5 seperately

**Comment by AlvaroBrey** [comment]
> @AlvaroBrey it's working. I clicked on "backup now" and I got a file for each calendar (except empty ones) in my backup-dir.
> 
> btw: I didn't setup sync via next cloud app but installed davx5 seperately
> 
> edit: don't wanna send my logs like this, need to find&replace private stuff first. will do that tomorrow if you are still interested

If it's working properly, then I don't need logs :)

Can other affected people try the above APK?

**Comment by AlvaroBrey** [comment]
> Can other affected people try the above APK?
@Jerome-Herbinet @henningaround

**Comment by Thovi98** [comment]
I confirm it works also for me (first time it does) ! Congrats and thank you

**Comment by BexoDust** [comment]
> > Can other affected people try the above APK?
> > @Jerome-Herbinet @henningaround

I can also confirm, that this version now does a proper manual backup, which it didn't before.

**Comment by ristein** [comment]
🥳

**Comment by henningaround** [comment]
I can confirm too that it works as expected 🎉

**Comment by alexjung** [comment]
I checked the feature out and can confirm that both contacts and calendar are being backed up when initiating the backup manually. 

I used to use the daily contacts backup when there was no calendar backup and it always worked flawlessly. 
But now I didn't use it for a while and it does seem like only manually triggering it works for me now. Does the automatic daily backup work for you guys? 

I'm on a Samsung Galaxy S10 (Android 12), latest version of the Nextcloud App and have "Battery Optimization" disabled for the Nextcloud App.

**Comment by Jerome-Herbinet** [comment]
Calendar backup is still not working for me.

**Comment by ljep42** [comment]
Same auto back up is not working. I'm in ver 3.23.1

**Comment by Jerome-Herbinet** [comment]
Still not working with 3.26.0 Android app and Nextcloud 27.1.0
I've deleted several of my calendars, including the one with the biggest history ... but the backup refuses to work.

**Comment by svenb1234** [comment]
Does it work, if you trigger it manually?

**Comment by Jerome-Herbinet** [comment]
> Does it work, if you trigger it manually?

Yes 🙁

**Comment by svenb1234** [comment]
Did you deactivate the battery optimisation for the Nextcloud App? Maybe the app is not active in the background and thus does not trigger the backup.

**Comment by Jerome-Herbinet** [comment]
> Did you deactivate the battery optimisation for the Nextcloud App? Maybe the app is not active in the background and thus does not trigger the backup.

It has always been disabled for this app.
