### ISSUE TITLE
Nextcloud app keeps crashing on OnePlus Nord2 5G

### ISSUE THREAD

**Issue by the-living-cup** [nextcloud/android#9693]
After logging in and giving the app storage permissions, it starts loading the files and crashes with the error below. It works on a different phone (galaxy a71)

************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=1
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1011)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:153)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:140)
	at android.content.ContentResolver.query(ContentResolver.java:1225)
	at android.content.ContentResolver.query(ContentResolver.java:1131)
	at android.content.ContentResolver.query(ContentResolver.java:1087)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileCursorForValue(FileDataStorageManager.java:965)
	at com.owncloud.android.datamodel.FileDataStorageManager.fileExists(FileDataStorageManager.java:948)
	at com.owncloud.android.datamodel.FileDataStorageManager.fileExists(FileDataStorageManager.java:189)
	at com.owncloud.android.datamodel.FileDataStorageManager.saveFile(FileDataStorageManager.java:260)
	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:252)
	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:363)
	at java.lang.Thread.run(Thread.java:923)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30180190
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OP515BL1
Model: DN2103
Id: RP1A.200720.011
Product: DN2103EEA

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 1640787928920

**Comment by the-living-cup** [comment]
Well, not directly, but Photos do have 12 folders per year, each month with about 150-200 items. Photos folder has 6,737 files, counting subfolders

**Comment by AlvaroBrey** [comment]
Probably then a duplicate of #5926

**Comment by AlvaroBrey** [comment]
> Probably then a duplicate of #5926

Nevermind, this doesn't seem like a comparable crash trace. Does the issue persist after uninstalling the app and reinstalling it?

**Comment by the-living-cup** [comment]
Yes it does. I tried installing it from F-Droid instead of gplay, crashes with the same error

**Comment by AlvaroBrey** [comment]
@the-living-cup this has probably been fixed in 3.19.0. Can you verify that?

**Comment by the-living-cup** [comment]
@AlvaroBrey installed 3.19.0 just now, sadly it still crashes

```
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=1
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1011)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:153)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:140)
	at android.content.ContentResolver.query(ContentResolver.java:1225)
	at android.content.ContentResolver.query(ContentResolver.java:1131)
	at android.content.ContentResolver.query(ContentResolver.java:1087)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileCursorForValue(FileDataStorageManager.java:956)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:121)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByEncryptedRemotePath(FileDataStorageManager.java:111)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFileByPath(FileDataStorageManager.java:107)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:2402)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1442)
	at android.app.Activity.performStart(Activity.java:8175)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3851)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2414)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:265)
	at android.app.ActivityThread.main(ActivityThread.java:8360)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30190090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OP515BL1
Model: DN2103
Id: RP1A.200720.011
Product: DN2103EEA

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 1640787928920
```

**Comment by AlvaroBrey** [comment]
> @AlvaroBrey I've also removed my Photos folder completely (~7000 files), still crashes even after a reinstall

The crash is related to something in you server account (too many files in the root folder? or something like that). More specifically there's a file or directory (again, most likely the root folder) that somehow has too much data.

I unfortunately can't reproduce it , so I can't see what's causing the issue exactly.

**Comment by the-living-cup** [comment]
> > @AlvaroBrey I've also removed my Photos folder completely (~7000 files), still crashes even after a reinstall
> 
> The crash is related to something in you server account (too many files in the root folder? or something like that). More specifically there's a file or directory (again, most likely the root folder) that somehow has too much data.
> 
> I unfortunately can't reproduce it , so I can't see what's causing the issue exactly.

Alright, great, removed everything from the root folder, (currently 0 B used, "No files here"), and the app doesn't crash.
Moved back just the Photos folder, still doesn't crash.

I'll try to find which folder / file is causing the crash.

Also, I need to clear the cache+data on my phone to get rid of the crash screen, even if I remove everything on the server side.

**Comment by AlvaroBrey** [comment]
> 
> I'll try to find which folder / file is causing the crash.
> 

If you do, please do post back here as I'm very interested to see if I can reproduce this somehow with a similar file or folder.

**Comment by the-living-cup** [comment]
> > I'll try to find which folder / file is causing the crash.
> 
> If you do, please do post back here as I'm very interested to see if I can reproduce this somehow with a similar file or folder.

Found the issue... I don't know when, or how, but I made a 9.8MB Readme.md, with 13 fairly high-res screenshots embedded in it...
That was the only file left, that's when I noticed its size..

**Comment by the-living-cup** [comment]
> > Found the issue... I don't know when, or how, but I made a 9.8MB Readme.md, with 13 fairly high-res screenshots embedded in it... That was the only file left, that's when I noticed its size..
> 
> Can you please send that file to [alvaro.brey@nextcloud.com](mailto:alvaro.brey@nextcloud.com) (or attach it here), so I can see if I can reproduce this in my test server? This shouldn't be crashing...
> 
> If the file contains private information, don't worry, I will just try to reproduce that sort of file myself.

The original contained some work related stuff, but I've managed to reproduce the crash with this file:
[test.md](https://github.com/nextcloud/android/files/8051269/test.md)

**Comment by AlvaroBrey** [comment]
> > > Found the issue... I don't know when, or how, but I made a 9.8MB Readme.md, with 13 fairly high-res screenshots embedded in it... That was the only file left, that's when I noticed its size..
> > 
> > 
> > Can you please send that file to [alvaro.brey@nextcloud.com](mailto:alvaro.brey@nextcloud.com) (or attach it here), so I can see if I can reproduce this in my test server? This shouldn't be crashing...
> > If the file contains private information, don't worry, I will just try to reproduce that sort of file myself.
> 
> The original contained some work related stuff, but I've managed to reproduce the crash with this file: [test.md](https://github.com/nextcloud/android/files/8051269/test.md)

THANK YOU! Reproducible 100% of the time with this file (when renamed as `README.md`). I'm reopening the issue to track this bug.
